<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Airline;
use VisaAcceptanceMergedSpecLib\Models\AncillaryInformation;
use VisaAcceptanceMergedSpecLib\Models\Leg;
use VisaAcceptanceMergedSpecLib\Models\TicketIssuer;

/**
 * Builder for model Airline
 *
 * @see Airline
 */
class AirlineBuilder
{
    /**
     * @var Airline
     */
    private $instance;

    private function __construct(Airline $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Airline Builder object.
     */
    public static function init(): self
    {
        return new self(new Airline());
    }

    /**
     * Sets is Domestic field.
     *
     * @param string|null $value
     */
    public function isDomestic(?string $value): self
    {
        $this->instance->setIsDomestic($value);
        return $this;
    }

    /**
     * Sets booking Reference Number field.
     *
     * @param string|null $value
     */
    public function bookingReferenceNumber(?string $value): self
    {
        $this->instance->setBookingReferenceNumber($value);
        return $this;
    }

    /**
     * Sets carrier Name field.
     *
     * @param string|null $value
     */
    public function carrierName(?string $value): self
    {
        $this->instance->setCarrierName($value);
        return $this;
    }

    /**
     * Sets ticket Issuer field.
     *
     * @param TicketIssuer|null $value
     */
    public function ticketIssuer(?TicketIssuer $value): self
    {
        $this->instance->setTicketIssuer($value);
        return $this;
    }

    /**
     * Sets ticket Number field.
     *
     * @param string|null $value
     */
    public function ticketNumber(?string $value): self
    {
        $this->instance->setTicketNumber($value);
        return $this;
    }

    /**
     * Sets check Digit field.
     *
     * @param string|null $value
     */
    public function checkDigit(?string $value): self
    {
        $this->instance->setCheckDigit($value);
        return $this;
    }

    /**
     * Sets restricted Ticket Indicator field.
     *
     * @param int|null $value
     */
    public function restrictedTicketIndicator(?int $value): self
    {
        $this->instance->setRestrictedTicketIndicator($value);
        return $this;
    }

    /**
     * Sets transaction Type field.
     *
     * @param int|null $value
     */
    public function transactionType(?int $value): self
    {
        $this->instance->setTransactionType($value);
        return $this;
    }

    /**
     * Sets extended Payment Code field.
     *
     * @param string|null $value
     */
    public function extendedPaymentCode(?string $value): self
    {
        $this->instance->setExtendedPaymentCode($value);
        return $this;
    }

    /**
     * Sets passenger Name field.
     *
     * @param string|null $value
     */
    public function passengerName(?string $value): self
    {
        $this->instance->setPassengerName($value);
        return $this;
    }

    /**
     * Sets customer Code field.
     *
     * @param string|null $value
     */
    public function customerCode(?string $value): self
    {
        $this->instance->setCustomerCode($value);
        return $this;
    }

    /**
     * Sets document Type field.
     *
     * @param string|null $value
     */
    public function documentType(?string $value): self
    {
        $this->instance->setDocumentType($value);
        return $this;
    }

    /**
     * Sets document Number field.
     *
     * @param string|null $value
     */
    public function documentNumber(?string $value): self
    {
        $this->instance->setDocumentNumber($value);
        return $this;
    }

    /**
     * Sets document Number Of Parts field.
     *
     * @param int|null $value
     */
    public function documentNumberOfParts(?int $value): self
    {
        $this->instance->setDocumentNumberOfParts($value);
        return $this;
    }

    /**
     * Sets invoice Number field.
     *
     * @param string|null $value
     */
    public function invoiceNumber(?string $value): self
    {
        $this->instance->setInvoiceNumber($value);
        return $this;
    }

    /**
     * Sets invoice Date field.
     *
     * @param int|null $value
     */
    public function invoiceDate(?int $value): self
    {
        $this->instance->setInvoiceDate($value);
        return $this;
    }

    /**
     * Sets additional Charges field.
     *
     * @param string|null $value
     */
    public function additionalCharges(?string $value): self
    {
        $this->instance->setAdditionalCharges($value);
        return $this;
    }

    /**
     * Sets total Fee Amount field.
     *
     * @param string|null $value
     */
    public function totalFeeAmount(?string $value): self
    {
        $this->instance->setTotalFeeAmount($value);
        return $this;
    }

    /**
     * Sets clearing Sequence field.
     *
     * @param string|null $value
     */
    public function clearingSequence(?string $value): self
    {
        $this->instance->setClearingSequence($value);
        return $this;
    }

    /**
     * Sets clearing Count field.
     *
     * @param string|null $value
     */
    public function clearingCount(?string $value): self
    {
        $this->instance->setClearingCount($value);
        return $this;
    }

    /**
     * Sets total Clearing Amount field.
     *
     * @param string|null $value
     */
    public function totalClearingAmount(?string $value): self
    {
        $this->instance->setTotalClearingAmount($value);
        return $this;
    }

    /**
     * Sets number Of Passengers field.
     *
     * @param int|null $value
     */
    public function numberOfPassengers(?int $value): self
    {
        $this->instance->setNumberOfPassengers($value);
        return $this;
    }

    /**
     * Sets reservation System Code field.
     *
     * @param string|null $value
     */
    public function reservationSystemCode(?string $value): self
    {
        $this->instance->setReservationSystemCode($value);
        return $this;
    }

    /**
     * Sets process Identifier field.
     *
     * @param string|null $value
     */
    public function processIdentifier(?string $value): self
    {
        $this->instance->setProcessIdentifier($value);
        return $this;
    }

    /**
     * Sets ticket Issue Date field.
     *
     * @param string|null $value
     */
    public function ticketIssueDate(?string $value): self
    {
        $this->instance->setTicketIssueDate($value);
        return $this;
    }

    /**
     * Sets electronic Ticket Indicator field.
     *
     * @param bool|null $value
     */
    public function electronicTicketIndicator(?bool $value): self
    {
        $this->instance->setElectronicTicketIndicator($value);
        return $this;
    }

    /**
     * Sets original Ticket Number field.
     *
     * @param string|null $value
     */
    public function originalTicketNumber(?string $value): self
    {
        $this->instance->setOriginalTicketNumber($value);
        return $this;
    }

    /**
     * Sets purchase Type field.
     *
     * @param string|null $value
     */
    public function purchaseType(?string $value): self
    {
        $this->instance->setPurchaseType($value);
        return $this;
    }

    /**
     * Sets credit Reason Indicator field.
     *
     * @param string|null $value
     */
    public function creditReasonIndicator(?string $value): self
    {
        $this->instance->setCreditReasonIndicator($value);
        return $this;
    }

    /**
     * Sets ticket Change Indicator field.
     *
     * @param string|null $value
     */
    public function ticketChangeIndicator(?string $value): self
    {
        $this->instance->setTicketChangeIndicator($value);
        return $this;
    }

    /**
     * Sets plan Number field.
     *
     * @param string|null $value
     */
    public function planNumber(?string $value): self
    {
        $this->instance->setPlanNumber($value);
        return $this;
    }

    /**
     * Sets arrival Date field.
     *
     * @param string|null $value
     */
    public function arrivalDate(?string $value): self
    {
        $this->instance->setArrivalDate($value);
        return $this;
    }

    /**
     * Sets restricted Ticket Desciption field.
     *
     * @param string|null $value
     */
    public function restrictedTicketDesciption(?string $value): self
    {
        $this->instance->setRestrictedTicketDesciption($value);
        return $this;
    }

    /**
     * Sets exchange Ticket Amount field.
     *
     * @param string|null $value
     */
    public function exchangeTicketAmount(?string $value): self
    {
        $this->instance->setExchangeTicketAmount($value);
        return $this;
    }

    /**
     * Sets exchange Ticket Fee Amount field.
     *
     * @param string|null $value
     */
    public function exchangeTicketFeeAmount(?string $value): self
    {
        $this->instance->setExchangeTicketFeeAmount($value);
        return $this;
    }

    /**
     * Sets reservation Type field.
     *
     * @param string|null $value
     */
    public function reservationType(?string $value): self
    {
        $this->instance->setReservationType($value);
        return $this;
    }

    /**
     * Sets boarding Fee Amount field.
     *
     * @param string|null $value
     */
    public function boardingFeeAmount(?string $value): self
    {
        $this->instance->setBoardingFeeAmount($value);
        return $this;
    }

    /**
     * Sets legs field.
     *
     * @param Leg[]|null $value
     */
    public function legs(?array $value): self
    {
        $this->instance->setLegs($value);
        return $this;
    }

    /**
     * Sets ancillary Information field.
     *
     * @param AncillaryInformation|null $value
     */
    public function ancillaryInformation(?AncillaryInformation $value): self
    {
        $this->instance->setAncillaryInformation($value);
        return $this;
    }

    /**
     * Sets flight Type field.
     *
     * @param string|null $value
     */
    public function flightType(?string $value): self
    {
        $this->instance->setFlightType($value);
        return $this;
    }

    /**
     * Sets insurance Amount field.
     *
     * @param string|null $value
     */
    public function insuranceAmount(?string $value): self
    {
        $this->instance->setInsuranceAmount($value);
        return $this;
    }

    /**
     * Sets frequent Flyer Number field.
     *
     * @param string|null $value
     */
    public function frequentFlyerNumber(?string $value): self
    {
        $this->instance->setFrequentFlyerNumber($value);
        return $this;
    }

    /**
     * Sets third Party Status field.
     *
     * @param string|null $value
     */
    public function thirdPartyStatus(?string $value): self
    {
        $this->instance->setThirdPartyStatus($value);
        return $this;
    }

    /**
     * Sets passenger Type field.
     *
     * @param string|null $value
     */
    public function passengerType(?string $value): self
    {
        $this->instance->setPassengerType($value);
        return $this;
    }

    /**
     * Sets total Insurance Amount field.
     *
     * @param string|null $value
     */
    public function totalInsuranceAmount(?string $value): self
    {
        $this->instance->setTotalInsuranceAmount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Airline object.
     */
    public function build(): Airline
    {
        return CoreHelper::clone($this->instance);
    }
}
