<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\AmexAdditionalAmount;
use VisaAcceptanceMergedSpecLib\Models\AmountDetails;
use VisaAcceptanceMergedSpecLib\Models\CurrencyConversion;
use VisaAcceptanceMergedSpecLib\Models\OctSurcharge;
use VisaAcceptanceMergedSpecLib\Models\Order;
use VisaAcceptanceMergedSpecLib\Models\Surcharge;
use VisaAcceptanceMergedSpecLib\Models\TaxDetail;

/**
 * Builder for model AmountDetails
 *
 * @see AmountDetails
 */
class AmountDetailsBuilder
{
    /**
     * @var AmountDetails
     */
    private $instance;

    private function __construct(AmountDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amount Details Builder object.
     */
    public static function init(): self
    {
        return new self(new AmountDetails());
    }

    /**
     * Sets gift Wrap Amount field.
     *
     * @param string|null $value
     */
    public function giftWrapAmount(?string $value): self
    {
        $this->instance->setGiftWrapAmount($value);
        return $this;
    }

    /**
     * Sets invoice Amount field.
     *
     * @param string|null $value
     */
    public function invoiceAmount(?string $value): self
    {
        $this->instance->setInvoiceAmount($value);
        return $this;
    }

    /**
     * Sets total Amount field.
     *
     * @param string|null $value
     */
    public function totalAmount(?string $value): self
    {
        $this->instance->setTotalAmount($value);
        return $this;
    }

    /**
     * Sets sub Total Amount field.
     *
     * @param string|null $value
     */
    public function subTotalAmount(?string $value): self
    {
        $this->instance->setSubTotalAmount($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets discount Amount field.
     *
     * @param string|null $value
     */
    public function discountAmount(?string $value): self
    {
        $this->instance->setDiscountAmount($value);
        return $this;
    }

    /**
     * Sets duty Amount field.
     *
     * @param string|null $value
     */
    public function dutyAmount(?string $value): self
    {
        $this->instance->setDutyAmount($value);
        return $this;
    }

    /**
     * Sets gratuity Amount field.
     *
     * @param string|null $value
     */
    public function gratuityAmount(?string $value): self
    {
        $this->instance->setGratuityAmount($value);
        return $this;
    }

    /**
     * Sets tax Amount field.
     *
     * @param string|null $value
     */
    public function taxAmount(?string $value): self
    {
        $this->instance->setTaxAmount($value);
        return $this;
    }

    /**
     * Sets national Tax Included field.
     *
     * @param string|null $value
     */
    public function nationalTaxIncluded(?string $value): self
    {
        $this->instance->setNationalTaxIncluded($value);
        return $this;
    }

    /**
     * Sets tax Applied After Discount field.
     *
     * @param string|null $value
     */
    public function taxAppliedAfterDiscount(?string $value): self
    {
        $this->instance->setTaxAppliedAfterDiscount($value);
        return $this;
    }

    /**
     * Sets tax Applied Level field.
     *
     * @param string|null $value
     */
    public function taxAppliedLevel(?string $value): self
    {
        $this->instance->setTaxAppliedLevel($value);
        return $this;
    }

    /**
     * Sets tax Type Code field.
     *
     * @param string|null $value
     */
    public function taxTypeCode(?string $value): self
    {
        $this->instance->setTaxTypeCode($value);
        return $this;
    }

    /**
     * Sets freight Amount field.
     *
     * @param string|null $value
     */
    public function freightAmount(?string $value): self
    {
        $this->instance->setFreightAmount($value);
        return $this;
    }

    /**
     * Sets foreign Amount field.
     *
     * @param string|null $value
     */
    public function foreignAmount(?string $value): self
    {
        $this->instance->setForeignAmount($value);
        return $this;
    }

    /**
     * Sets foreign Currency field.
     *
     * @param string|null $value
     */
    public function foreignCurrency(?string $value): self
    {
        $this->instance->setForeignCurrency($value);
        return $this;
    }

    /**
     * Sets exchange Rate field.
     *
     * @param string|null $value
     */
    public function exchangeRate(?string $value): self
    {
        $this->instance->setExchangeRate($value);
        return $this;
    }

    /**
     * Sets exchange Rate Time Stamp field.
     *
     * @param string|null $value
     */
    public function exchangeRateTimeStamp(?string $value): self
    {
        $this->instance->setExchangeRateTimeStamp($value);
        return $this;
    }

    /**
     * Sets surcharge field.
     *
     * @param Surcharge|null $value
     */
    public function surcharge(?Surcharge $value): self
    {
        $this->instance->setSurcharge($value);
        return $this;
    }

    /**
     * Sets settlement Amount field.
     *
     * @param string|null $value
     */
    public function settlementAmount(?string $value): self
    {
        $this->instance->setSettlementAmount($value);
        return $this;
    }

    /**
     * Sets settlement Currency field.
     *
     * @param string|null $value
     */
    public function settlementCurrency(?string $value): self
    {
        $this->instance->setSettlementCurrency($value);
        return $this;
    }

    /**
     * Sets amex Additional Amounts field.
     *
     * @param AmexAdditionalAmount[]|null $value
     */
    public function amexAdditionalAmounts(?array $value): self
    {
        $this->instance->setAmexAdditionalAmounts($value);
        return $this;
    }

    /**
     * Sets tax Details field.
     *
     * @param TaxDetail[]|null $value
     */
    public function taxDetails(?array $value): self
    {
        $this->instance->setTaxDetails($value);
        return $this;
    }

    /**
     * Sets service Fee Amount field.
     *
     * @param string|null $value
     */
    public function serviceFeeAmount(?string $value): self
    {
        $this->instance->setServiceFeeAmount($value);
        return $this;
    }

    /**
     * Sets original Amount field.
     *
     * @param string|null $value
     */
    public function originalAmount(?string $value): self
    {
        $this->instance->setOriginalAmount($value);
        return $this;
    }

    /**
     * Sets original Currency field.
     *
     * @param string|null $value
     */
    public function originalCurrency(?string $value): self
    {
        $this->instance->setOriginalCurrency($value);
        return $this;
    }

    /**
     * Sets cashback Amount field.
     *
     * @param string|null $value
     */
    public function cashbackAmount(?string $value): self
    {
        $this->instance->setCashbackAmount($value);
        return $this;
    }

    /**
     * Sets currency Conversion field.
     *
     * @param CurrencyConversion|null $value
     */
    public function currencyConversion(?CurrencyConversion $value): self
    {
        $this->instance->setCurrencyConversion($value);
        return $this;
    }

    /**
     * Sets oct-surcharge field.
     *
     * @param OctSurcharge|null $value
     */
    public function octSurcharge(?OctSurcharge $value): self
    {
        $this->instance->setOctSurcharge($value);
        return $this;
    }

    /**
     * Sets order field.
     *
     * @param Order|null $value
     */
    public function order(?Order $value): self
    {
        $this->instance->setOrder($value);
        return $this;
    }

    /**
     * Sets anticipated Amount field.
     *
     * @param string|null $value
     */
    public function anticipatedAmount(?string $value): self
    {
        $this->instance->setAnticipatedAmount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Amount Details object.
     */
    public function build(): AmountDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
