<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\AmountDetails6;

/**
 * Builder for model AmountDetails6
 *
 * @see AmountDetails6
 */
class AmountDetails6Builder
{
    /**
     * @var AmountDetails6
     */
    private $instance;

    private function __construct(AmountDetails6 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amount Details 6 Builder object.
     */
    public static function init(): self
    {
        return new self(new AmountDetails6());
    }

    /**
     * Sets service Fee Amount field.
     *
     * @param string|null $value
     */
    public function serviceFeeAmount(?string $value): self
    {
        $this->instance->setServiceFeeAmount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Amount Details 6 object.
     */
    public function build(): AmountDetails6
    {
        return CoreHelper::clone($this->instance);
    }
}
