<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\AuthorizationOptions6;
use VisaAcceptanceMergedSpecLib\Models\Initiator26;

/**
 * Builder for model AuthorizationOptions6
 *
 * @see AuthorizationOptions6
 */
class AuthorizationOptions6Builder
{
    /**
     * @var AuthorizationOptions6
     */
    private $instance;

    private function __construct(AuthorizationOptions6 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Authorization Options 6 Builder object.
     */
    public static function init(): self
    {
        return new self(new AuthorizationOptions6());
    }

    /**
     * Sets auth Type field.
     *
     * @param string|null $value
     */
    public function authType(?string $value): self
    {
        $this->instance->setAuthType($value);
        return $this;
    }

    /**
     * Sets auth Indicator field.
     *
     * @param string|null $value
     */
    public function authIndicator(?string $value): self
    {
        $this->instance->setAuthIndicator($value);
        return $this;
    }

    /**
     * Sets extend Auth Indicator field.
     *
     * @param string|null $value
     */
    public function extendAuthIndicator(?string $value): self
    {
        $this->instance->setExtendAuthIndicator($value);
        return $this;
    }

    /**
     * Sets card Verification Indicator field.
     *
     * @param bool|null $value
     */
    public function cardVerificationIndicator(?bool $value): self
    {
        $this->instance->setCardVerificationIndicator($value);
        return $this;
    }

    /**
     * Sets initiator field.
     *
     * @param Initiator26|null $value
     */
    public function initiator(?Initiator26 $value): self
    {
        $this->instance->setInitiator($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Authorization Options 6 object.
     */
    public function build(): AuthorizationOptions6
    {
        return CoreHelper::clone($this->instance);
    }
}
