<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\BankTransferOptions1;

/**
 * Builder for model BankTransferOptions1
 *
 * @see BankTransferOptions1
 */
class BankTransferOptions1Builder
{
    /**
     * @var BankTransferOptions1
     */
    private $instance;

    private function __construct(BankTransferOptions1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bank Transfer Options 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new BankTransferOptions1());
    }

    /**
     * Sets settlement Method field.
     *
     * @param string|null $value
     */
    public function settlementMethod(?string $value): self
    {
        $this->instance->setSettlementMethod($value);
        return $this;
    }

    /**
     * Sets fraud Screening Level field.
     *
     * @param string|null $value
     */
    public function fraudScreeningLevel(?string $value): self
    {
        $this->instance->setFraudScreeningLevel($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Bank Transfer Options 1 object.
     */
    public function build(): BankTransferOptions1
    {
        return CoreHelper::clone($this->instance);
    }
}
