<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\BankTransferOptions2;

/**
 * Builder for model BankTransferOptions2
 *
 * @see BankTransferOptions2
 */
class BankTransferOptions2Builder
{
    /**
     * @var BankTransferOptions2
     */
    private $instance;

    private function __construct(BankTransferOptions2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bank Transfer Options 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new BankTransferOptions2());
    }

    /**
     * Sets customer Memo field.
     *
     * @param string|null $value
     */
    public function customerMemo(?string $value): self
    {
        $this->instance->setCustomerMemo($value);
        return $this;
    }

    /**
     * Sets sec Code field.
     *
     * @param string|null $value
     */
    public function secCode(?string $value): self
    {
        $this->instance->setSecCode($value);
        return $this;
    }

    /**
     * Sets terminal City field.
     *
     * @param string|null $value
     */
    public function terminalCity(?string $value): self
    {
        $this->instance->setTerminalCity($value);
        return $this;
    }

    /**
     * Sets terminal State field.
     *
     * @param string|null $value
     */
    public function terminalState(?string $value): self
    {
        $this->instance->setTerminalState($value);
        return $this;
    }

    /**
     * Sets effective Date field.
     *
     * @param string|null $value
     */
    public function effectiveDate(?string $value): self
    {
        $this->instance->setEffectiveDate($value);
        return $this;
    }

    /**
     * Sets partial Payment Id field.
     *
     * @param string|null $value
     */
    public function partialPaymentId(?string $value): self
    {
        $this->instance->setPartialPaymentId($value);
        return $this;
    }

    /**
     * Sets settlement Method field.
     *
     * @param string|null $value
     */
    public function settlementMethod(?string $value): self
    {
        $this->instance->setSettlementMethod($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Bank Transfer Options 2 object.
     */
    public function build(): BankTransferOptions2
    {
        return CoreHelper::clone($this->instance);
    }
}
