<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\BillTo14;

/**
 * Builder for model BillTo14
 *
 * @see BillTo14
 */
class BillTo14Builder
{
    /**
     * @var BillTo14
     */
    private $instance;

    private function __construct(BillTo14 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bill To 14 Builder object.
     */
    public static function init(): self
    {
        return new self(new BillTo14());
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Bill To 14 object.
     */
    public function build(): BillTo14
    {
        return CoreHelper::clone($this->instance);
    }
}
