<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Brand24;

/**
 * Builder for model Brand24
 *
 * @see Brand24
 */
class Brand24Builder
{
    /**
     * @var Brand24
     */
    private $instance;

    private function __construct(Brand24 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Brand 24 Builder object.
     */
    public static function init(): self
    {
        return new self(new Brand24());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets brand Name field.
     *
     * @param string|null $value
     */
    public function brandName(?string $value): self
    {
        $this->instance->setBrandName($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Brand 24 object.
     */
    public function build(): Brand24
    {
        return CoreHelper::clone($this->instance);
    }
}
