<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Customer15;

/**
 * Builder for model Customer15
 *
 * @see Customer15
 */
class Customer15Builder
{
    /**
     * @var Customer15
     */
    private $instance;

    private function __construct(Customer15 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Customer 15 Builder object.
     */
    public static function init(): self
    {
        return new self(new Customer15());
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Customer 15 object.
     */
    public function build(): Customer15
    {
        return CoreHelper::clone($this->instance);
    }
}
