<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Customer4;

/**
 * Builder for model Customer4
 *
 * @see Customer4
 */
class Customer4Builder
{
    /**
     * @var Customer4
     */
    private $instance;

    private function __construct(Customer4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Customer 4 Builder object.
     */
    public static function init(): self
    {
        return new self(new Customer4());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Customer 4 object.
     */
    public function build(): Customer4
    {
        return CoreHelper::clone($this->instance);
    }
}
