<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\EWallet;

/**
 * Builder for model EWallet
 *
 * @see EWallet
 */
class EWalletBuilder
{
    /**
     * @var EWallet
     */
    private $instance;

    private function __construct(EWallet $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new E Wallet Builder object.
     */
    public static function init(): self
    {
        return new self(new EWallet());
    }

    /**
     * Sets account Id field.
     *
     * @param string|null $value
     */
    public function accountId(?string $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets funding Source field.
     *
     * @param string|null $value
     */
    public function fundingSource(?string $value): self
    {
        $this->instance->setFundingSource($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new E Wallet object.
     */
    public function build(): EWallet
    {
        return CoreHelper::clone($this->instance);
    }
}
