<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Features;

/**
 * Builder for model Features
 *
 * @see Features
 */
class FeaturesBuilder
{
    /**
     * @var Features
     */
    private $instance;

    private function __construct(Features $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Features Builder object.
     */
    public static function init(): self
    {
        return new self(new Features());
    }

    /**
     * Sets account Funding Source field.
     *
     * @param string|null $value
     */
    public function accountFundingSource(?string $value): self
    {
        $this->instance->setAccountFundingSource($value);
        return $this;
    }

    /**
     * Sets account Funding Source Sub Type field.
     *
     * @param string|null $value
     */
    public function accountFundingSourceSubType(?string $value): self
    {
        $this->instance->setAccountFundingSourceSubType($value);
        return $this;
    }

    /**
     * Sets card Product field.
     *
     * @param string|null $value
     */
    public function cardProduct(?string $value): self
    {
        $this->instance->setCardProduct($value);
        return $this;
    }

    /**
     * Sets message Type field.
     *
     * @param string|null $value
     */
    public function messageType(?string $value): self
    {
        $this->instance->setMessageType($value);
        return $this;
    }

    /**
     * Sets acceptance Level field.
     *
     * @param string|null $value
     */
    public function acceptanceLevel(?string $value): self
    {
        $this->instance->setAcceptanceLevel($value);
        return $this;
    }

    /**
     * Sets card Platform field.
     *
     * @param string|null $value
     */
    public function cardPlatform(?string $value): self
    {
        $this->instance->setCardPlatform($value);
        return $this;
    }

    /**
     * Sets combo Card field.
     *
     * @param string|null $value
     */
    public function comboCard(?string $value): self
    {
        $this->instance->setComboCard($value);
        return $this;
    }

    /**
     * Sets corporate Purchase field.
     *
     * @param bool|null $value
     */
    public function corporatePurchase(?bool $value): self
    {
        $this->instance->setCorporatePurchase($value);
        return $this;
    }

    /**
     * Sets health Card field.
     *
     * @param bool|null $value
     */
    public function healthCard(?bool $value): self
    {
        $this->instance->setHealthCard($value);
        return $this;
    }

    /**
     * Sets shared BIN field.
     *
     * @param bool|null $value
     */
    public function sharedBin(?bool $value): self
    {
        $this->instance->setSharedBin($value);
        return $this;
    }

    /**
     * Sets pos Domestic Only field.
     *
     * @param bool|null $value
     */
    public function posDomesticOnly(?bool $value): self
    {
        $this->instance->setPosDomesticOnly($value);
        return $this;
    }

    /**
     * Sets gambling Allowed field.
     *
     * @param bool|null $value
     */
    public function gamblingAllowed(?bool $value): self
    {
        $this->instance->setGamblingAllowed($value);
        return $this;
    }

    /**
     * Sets commercial Card Level 2 field.
     *
     * @param bool|null $value
     */
    public function commercialCardLevel2(?bool $value): self
    {
        $this->instance->setCommercialCardLevel2($value);
        return $this;
    }

    /**
     * Sets commercial Card Level 3 field.
     *
     * @param bool|null $value
     */
    public function commercialCardLevel3(?bool $value): self
    {
        $this->instance->setCommercialCardLevel3($value);
        return $this;
    }

    /**
     * Sets exempt BIN field.
     *
     * @param bool|null $value
     */
    public function exemptBin(?bool $value): self
    {
        $this->instance->setExemptBin($value);
        return $this;
    }

    /**
     * Sets account Level Management field.
     *
     * @param bool|null $value
     */
    public function accountLevelManagement(?bool $value): self
    {
        $this->instance->setAccountLevelManagement($value);
        return $this;
    }

    /**
     * Sets online Gambling Block field.
     *
     * @param bool|null $value
     */
    public function onlineGamblingBlock(?bool $value): self
    {
        $this->instance->setOnlineGamblingBlock($value);
        return $this;
    }

    /**
     * Sets auto Substantiation field.
     *
     * @param bool|null $value
     */
    public function autoSubstantiation(?bool $value): self
    {
        $this->instance->setAutoSubstantiation($value);
        return $this;
    }

    /**
     * Sets flex Credential field.
     *
     * @param bool|null $value
     */
    public function flexCredential(?bool $value): self
    {
        $this->instance->setFlexCredential($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Features object.
     */
    public function build(): Features
    {
        return CoreHelper::clone($this->instance);
    }
}
