<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\FluidData;

/**
 * Builder for model FluidData
 *
 * @see FluidData
 */
class FluidDataBuilder
{
    /**
     * @var FluidData
     */
    private $instance;

    private function __construct(FluidData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fluid Data Builder object.
     */
    public static function init(): self
    {
        return new self(new FluidData());
    }

    /**
     * Sets key Serial Number field.
     *
     * @param string|null $value
     */
    public function keySerialNumber(?string $value): self
    {
        $this->instance->setKeySerialNumber($value);
        return $this;
    }

    /**
     * Sets descriptor field.
     *
     * @param string|null $value
     */
    public function descriptor(?string $value): self
    {
        $this->instance->setDescriptor($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Sets encoding field.
     *
     * @param string|null $value
     */
    public function encoding(?string $value): self
    {
        $this->instance->setEncoding($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Fluid Data object.
     */
    public function build(): FluidData
    {
        return CoreHelper::clone($this->instance);
    }
}
