<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\InstallmentInformation10;

/**
 * Builder for model InstallmentInformation10
 *
 * @see InstallmentInformation10
 */
class InstallmentInformation10Builder
{
    /**
     * @var InstallmentInformation10
     */
    private $instance;

    private function __construct(InstallmentInformation10 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Installment Information 10 Builder object.
     */
    public static function init(): self
    {
        return new self(new InstallmentInformation10());
    }

    /**
     * Sets number Of Installments field.
     *
     * @param string|null $value
     */
    public function numberOfInstallments(?string $value): self
    {
        $this->instance->setNumberOfInstallments($value);
        return $this;
    }

    /**
     * Sets identifier field.
     *
     * @param string|null $value
     */
    public function identifier(?string $value): self
    {
        $this->instance->setIdentifier($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Installment Information 10 object.
     */
    public function build(): InstallmentInformation10
    {
        return CoreHelper::clone($this->instance);
    }
}
