<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\IssuerInformation2;

/**
 * Builder for model IssuerInformation2
 *
 * @see IssuerInformation2
 */
class IssuerInformation2Builder
{
    /**
     * @var IssuerInformation2
     */
    private $instance;

    private function __construct(IssuerInformation2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Issuer Information 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new IssuerInformation2());
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets discretionary Data field.
     *
     * @param string|null $value
     */
    public function discretionaryData(?string $value): self
    {
        $this->instance->setDiscretionaryData($value);
        return $this;
    }

    /**
     * Sets country Specific Discretionary Data field.
     *
     * @param string|null $value
     */
    public function countrySpecificDiscretionaryData(?string $value): self
    {
        $this->instance->setCountrySpecificDiscretionaryData($value);
        return $this;
    }

    /**
     * Sets response Code field.
     *
     * @param string|null $value
     */
    public function responseCode(?string $value): self
    {
        $this->instance->setResponseCode($value);
        return $this;
    }

    /**
     * Sets pin Request Indicator field.
     *
     * @param string|null $value
     */
    public function pinRequestIndicator(?string $value): self
    {
        $this->instance->setPinRequestIndicator($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Issuer Information 2 object.
     */
    public function build(): IssuerInformation2
    {
        return CoreHelper::clone($this->instance);
    }
}
