<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Issuer4;

/**
 * Builder for model Issuer4
 *
 * @see Issuer4
 */
class Issuer4Builder
{
    /**
     * @var Issuer4
     */
    private $instance;

    private function __construct(Issuer4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Issuer 4 Builder object.
     */
    public static function init(): self
    {
        return new self(new Issuer4());
    }

    /**
     * Sets payment Account Reference field.
     *
     * @param string|null $value
     */
    public function paymentAccountReference(?string $value): self
    {
        $this->instance->setPaymentAccountReference($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Issuer 4 object.
     */
    public function build(): Issuer4
    {
        return CoreHelper::clone($this->instance);
    }
}
