<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Links20;
use VisaAcceptanceMergedSpecLib\Models\Self18;
use VisaAcceptanceMergedSpecLib\Models\Self19;

/**
 * Builder for model Links20
 *
 * @see Links20
 */
class Links20Builder
{
    /**
     * @var Links20
     */
    private $instance;

    private function __construct(Links20 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Links 20 Builder object.
     */
    public static function init(): self
    {
        return new self(new Links20());
    }

    /**
     * Sets self field.
     *
     * @param Self19|null $value
     */
    public function self(?Self19 $value): self
    {
        $this->instance->setSelf($value);
        return $this;
    }

    /**
     * Sets customer field.
     *
     * @param Self18|null $value
     */
    public function customer(?Self18 $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Links 20 object.
     */
    public function build(): Links20
    {
        return CoreHelper::clone($this->instance);
    }
}
