<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\MerchantDescriptor1;

/**
 * Builder for model MerchantDescriptor1
 *
 * @see MerchantDescriptor1
 */
class MerchantDescriptor1Builder
{
    /**
     * @var MerchantDescriptor1
     */
    private $instance;

    private function __construct(MerchantDescriptor1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchant Descriptor 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new MerchantDescriptor1());
    }

    /**
     * Sets store Id field.
     *
     * @param string|null $value
     */
    public function storeId(?string $value): self
    {
        $this->instance->setStoreId($value);
        return $this;
    }

    /**
     * Sets store Name field.
     *
     * @param string|null $value
     */
    public function storeName(?string $value): self
    {
        $this->instance->setStoreName($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Merchant Descriptor 1 object.
     */
    public function build(): MerchantDescriptor1
    {
        return CoreHelper::clone($this->instance);
    }
}
