<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\MerchantDefinedSecureInformation;

/**
 * Builder for model MerchantDefinedSecureInformation
 *
 * @see MerchantDefinedSecureInformation
 */
class MerchantDefinedSecureInformationBuilder
{
    /**
     * @var MerchantDefinedSecureInformation
     */
    private $instance;

    private function __construct(MerchantDefinedSecureInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchant Defined Secure Information Builder object.
     */
    public static function init(): self
    {
        return new self(new MerchantDefinedSecureInformation());
    }

    /**
     * Sets secure 1 field.
     *
     * @param string|null $value
     */
    public function secure1(?string $value): self
    {
        $this->instance->setSecure1($value);
        return $this;
    }

    /**
     * Sets secure 2 field.
     *
     * @param string|null $value
     */
    public function secure2(?string $value): self
    {
        $this->instance->setSecure2($value);
        return $this;
    }

    /**
     * Sets secure 3 field.
     *
     * @param string|null $value
     */
    public function secure3(?string $value): self
    {
        $this->instance->setSecure3($value);
        return $this;
    }

    /**
     * Sets secure 4 field.
     *
     * @param string|null $value
     */
    public function secure4(?string $value): self
    {
        $this->instance->setSecure4($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Merchant Defined Secure Information object.
     */
    public function build(): MerchantDefinedSecureInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
