<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\MerchantDescriptor1;
use VisaAcceptanceMergedSpecLib\Models\MerchantInformation1;

/**
 * Builder for model MerchantInformation1
 *
 * @see MerchantInformation1
 */
class MerchantInformation1Builder
{
    /**
     * @var MerchantInformation1
     */
    private $instance;

    private function __construct(MerchantInformation1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchant Information 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new MerchantInformation1());
    }

    /**
     * Sets merchant Name field.
     *
     * @param string|null $value
     */
    public function merchantName(?string $value): self
    {
        $this->instance->setMerchantName($value);
        return $this;
    }

    /**
     * Sets merchant Descriptor field.
     *
     * @param MerchantDescriptor1|null $value
     */
    public function merchantDescriptor(?MerchantDescriptor1 $value): self
    {
        $this->instance->setMerchantDescriptor($value);
        return $this;
    }

    /**
     * Sets return Url field.
     *
     * @param string|null $value
     */
    public function returnUrl(?string $value): self
    {
        $this->instance->setReturnUrl($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Merchant Information 1 object.
     */
    public function build(): MerchantInformation1
    {
        return CoreHelper::clone($this->instance);
    }
}
