<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Metadata4;

/**
 * Builder for model Metadata4
 *
 * @see Metadata4
 */
class Metadata4Builder
{
    /**
     * @var Metadata4
     */
    private $instance;

    private function __construct(Metadata4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Metadata 4 Builder object.
     */
    public static function init(): self
    {
        return new self(new Metadata4());
    }

    /**
     * Sets creator field.
     *
     * @param string|null $value
     */
    public function creator(?string $value): self
    {
        $this->instance->setCreator($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Metadata 4 object.
     */
    public function build(): Metadata4
    {
        return CoreHelper::clone($this->instance);
    }
}
