<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Network;

/**
 * Builder for model Network
 *
 * @see Network
 */
class NetworkBuilder
{
    /**
     * @var Network
     */
    private $instance;

    private function __construct(Network $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Network Builder object.
     */
    public static function init(): self
    {
        return new self(new Network());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Network object.
     */
    public function build(): Network
    {
        return CoreHelper::clone($this->instance);
    }
}
