<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\OctSurcharge;

/**
 * Builder for model OctSurcharge
 *
 * @see OctSurcharge
 */
class OctSurchargeBuilder
{
    /**
     * @var OctSurcharge
     */
    private $instance;

    private function __construct(OctSurcharge $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Oct Surcharge Builder object.
     */
    public static function init(): self
    {
        return new self(new OctSurcharge());
    }

    /**
     * Sets amount field.
     *
     * @param string|null $value
     */
    public function amount(?string $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Oct Surcharge object.
     */
    public function build(): OctSurcharge
    {
        return CoreHelper::clone($this->instance);
    }
}
