<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\AccountFeatures2;
use VisaAcceptanceMergedSpecLib\Models\Bank13;
use VisaAcceptanceMergedSpecLib\Models\Brand24;
use VisaAcceptanceMergedSpecLib\Models\Card105;
use VisaAcceptanceMergedSpecLib\Models\Customer42;
use VisaAcceptanceMergedSpecLib\Models\Features24;
use VisaAcceptanceMergedSpecLib\Models\FluidData4;
use VisaAcceptanceMergedSpecLib\Models\InstrumentIdentifier27;
use VisaAcceptanceMergedSpecLib\Models\Invoice;
use VisaAcceptanceMergedSpecLib\Models\IssuerInformation30;
use VisaAcceptanceMergedSpecLib\Models\Network24;
use VisaAcceptanceMergedSpecLib\Models\PaymentInformation31;
use VisaAcceptanceMergedSpecLib\Models\PaymentInstrument4;
use VisaAcceptanceMergedSpecLib\Models\PaymentType22;
use VisaAcceptanceMergedSpecLib\Models\ShippingAddress4;

/**
 * Builder for model PaymentInformation31
 *
 * @see PaymentInformation31
 */
class PaymentInformation31Builder
{
    /**
     * @var PaymentInformation31
     */
    private $instance;

    private function __construct(PaymentInformation31 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Information 31 Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentInformation31());
    }

    /**
     * Sets payment Type field.
     *
     * @param PaymentType22|null $value
     */
    public function paymentType(?PaymentType22 $value): self
    {
        $this->instance->setPaymentType($value);
        return $this;
    }

    /**
     * Sets customer field.
     *
     * @param Customer42|null $value
     */
    public function customer(?Customer42 $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Sets card field.
     *
     * @param Card105|null $value
     */
    public function card(?Card105 $value): self
    {
        $this->instance->setCard($value);
        return $this;
    }

    /**
     * Sets brands field.
     *
     * @param Brand24[]|null $value
     */
    public function brands(?array $value): self
    {
        $this->instance->setBrands($value);
        return $this;
    }

    /**
     * Sets features field.
     *
     * @param Features24|null $value
     */
    public function features(?Features24 $value): self
    {
        $this->instance->setFeatures($value);
        return $this;
    }

    /**
     * Sets invoice field.
     *
     * @param Invoice|null $value
     */
    public function invoice(?Invoice $value): self
    {
        $this->instance->setInvoice($value);
        return $this;
    }

    /**
     * Sets network field.
     *
     * @param Network24|null $value
     */
    public function network(?Network24 $value): self
    {
        $this->instance->setNetwork($value);
        return $this;
    }

    /**
     * Sets issuer Information field.
     *
     * @param IssuerInformation30|null $value
     */
    public function issuerInformation(?IssuerInformation30 $value): self
    {
        $this->instance->setIssuerInformation($value);
        return $this;
    }

    /**
     * Sets bank field.
     *
     * @param Bank13|null $value
     */
    public function bank(?Bank13 $value): self
    {
        $this->instance->setBank($value);
        return $this;
    }

    /**
     * Sets account Features field.
     *
     * @param AccountFeatures2|null $value
     */
    public function accountFeatures(?AccountFeatures2 $value): self
    {
        $this->instance->setAccountFeatures($value);
        return $this;
    }

    /**
     * Sets payment Instrument field.
     *
     * @param PaymentInstrument4|null $value
     */
    public function paymentInstrument(?PaymentInstrument4 $value): self
    {
        $this->instance->setPaymentInstrument($value);
        return $this;
    }

    /**
     * Sets instrument Identifier field.
     *
     * @param InstrumentIdentifier27|null $value
     */
    public function instrumentIdentifier(?InstrumentIdentifier27 $value): self
    {
        $this->instance->setInstrumentIdentifier($value);
        return $this;
    }

    /**
     * Sets shipping Address field.
     *
     * @param ShippingAddress4|null $value
     */
    public function shippingAddress(?ShippingAddress4 $value): self
    {
        $this->instance->setShippingAddress($value);
        return $this;
    }

    /**
     * Sets fluid Data field.
     *
     * @param FluidData4|null $value
     */
    public function fluidData(?FluidData4 $value): self
    {
        $this->instance->setFluidData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Payment Information 31 object.
     */
    public function build(): PaymentInformation31
    {
        return CoreHelper::clone($this->instance);
    }
}
