<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\PaymentType22;

/**
 * Builder for model PaymentType22
 *
 * @see PaymentType22
 */
class PaymentType22Builder
{
    /**
     * @var PaymentType22
     */
    private $instance;

    private function __construct(PaymentType22 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Type 22 Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentType22());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets method field.
     *
     * @param string|null $value
     */
    public function method(?string $value): self
    {
        $this->instance->setMethod($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Payment Type 22 object.
     */
    public function build(): PaymentType22
    {
        return CoreHelper::clone($this->instance);
    }
}
