<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Card1;
use VisaAcceptanceMergedSpecLib\Models\PaymentAccountInformation;

/**
 * Builder for model PaymentAccountInformation
 *
 * @see PaymentAccountInformation
 */
class PaymentAccountInformationBuilder
{
    /**
     * @var PaymentAccountInformation
     */
    private $instance;

    private function __construct(PaymentAccountInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Account Information Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentAccountInformation());
    }

    /**
     * Sets card field.
     *
     * @param Card1|null $value
     */
    public function card(?Card1 $value): self
    {
        $this->instance->setCard($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Payment Account Information object.
     */
    public function build(): PaymentAccountInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
