<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\ProcessingInformation13;

/**
 * Builder for model ProcessingInformation13
 *
 * @see ProcessingInformation13
 */
class ProcessingInformation13Builder
{
    /**
     * @var ProcessingInformation13
     */
    private $instance;

    private function __construct(ProcessingInformation13 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Processing Information 13 Builder object.
     */
    public static function init(): self
    {
        return new self(new ProcessingInformation13());
    }

    /**
     * Sets action List field.
     *
     * @param string[]|null $value
     */
    public function actionList(?array $value): self
    {
        $this->instance->setActionList($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Processing Information 13 object.
     */
    public function build(): ProcessingInformation13
    {
        return CoreHelper::clone($this->instance);
    }
}
