<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Avs1;
use VisaAcceptanceMergedSpecLib\Models\ProcessorInformation19;
use VisaAcceptanceMergedSpecLib\Models\SellerProtection3;

/**
 * Builder for model ProcessorInformation19
 *
 * @see ProcessorInformation19
 */
class ProcessorInformation19Builder
{
    /**
     * @var ProcessorInformation19
     */
    private $instance;

    private function __construct(ProcessorInformation19 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Processor Information 19 Builder object.
     */
    public static function init(): self
    {
        return new self(new ProcessorInformation19());
    }

    /**
     * Sets seller Protection field.
     *
     * @param SellerProtection3|null $value
     */
    public function sellerProtection(?SellerProtection3 $value): self
    {
        $this->instance->setSellerProtection($value);
        return $this;
    }

    /**
     * Sets avs field.
     *
     * @param Avs1|null $value
     */
    public function avs(?Avs1 $value): self
    {
        $this->instance->setAvs($value);
        return $this;
    }

    /**
     * Sets transaction Id field.
     *
     * @param string|null $value
     */
    public function transactionId(?string $value): self
    {
        $this->instance->setTransactionId($value);
        return $this;
    }

    /**
     * Sets response Details field.
     *
     * @param string|null $value
     */
    public function responseDetails(?string $value): self
    {
        $this->instance->setResponseDetails($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Processor Information 19 object.
     */
    public function build(): ProcessorInformation19
    {
        return CoreHelper::clone($this->instance);
    }
}
