<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\ProcessorInformation22;
use VisaAcceptanceMergedSpecLib\Models\PtsV2UpdateOrderPatch201Response;

/**
 * Builder for model PtsV2UpdateOrderPatch201Response
 *
 * @see PtsV2UpdateOrderPatch201Response
 */
class PtsV2UpdateOrderPatch201ResponseBuilder
{
    /**
     * @var PtsV2UpdateOrderPatch201Response
     */
    private $instance;

    private function __construct(PtsV2UpdateOrderPatch201Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pts V2 Update Order Patch 201 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PtsV2UpdateOrderPatch201Response());
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets processor Information field.
     *
     * @param ProcessorInformation22|null $value
     */
    public function processorInformation(?ProcessorInformation22 $value): self
    {
        $this->instance->setProcessorInformation($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Pts V2 Update Order Patch 201 Response object.
     */
    public function build(): PtsV2UpdateOrderPatch201Response
    {
        return CoreHelper::clone($this->instance);
    }
}
