<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\PurchaseOptions;

/**
 * Builder for model PurchaseOptions
 *
 * @see PurchaseOptions
 */
class PurchaseOptionsBuilder
{
    /**
     * @var PurchaseOptions
     */
    private $instance;

    private function __construct(PurchaseOptions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Purchase Options Builder object.
     */
    public static function init(): self
    {
        return new self(new PurchaseOptions());
    }

    /**
     * Sets is Electronic Benefits Transfer field.
     *
     * @param bool|null $value
     */
    public function isElectronicBenefitsTransfer(?bool $value): self
    {
        $this->instance->setIsElectronicBenefitsTransfer($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets eligibility Indicator field.
     *
     * @param string|null $value
     */
    public function eligibilityIndicator(?string $value): self
    {
        $this->instance->setEligibilityIndicator($value);
        return $this;
    }

    /**
     * Sets benefit Amount field.
     *
     * @param string|null $value
     */
    public function benefitAmount(?string $value): self
    {
        $this->instance->setBenefitAmount($value);
        return $this;
    }

    /**
     * Sets benefit Type field.
     *
     * @param string|null $value
     */
    public function benefitType(?string $value): self
    {
        $this->instance->setBenefitType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Purchase Options object.
     */
    public function build(): PurchaseOptions
    {
        return CoreHelper::clone($this->instance);
    }
}
