<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\RecurringOptions1;

/**
 * Builder for model RecurringOptions1
 *
 * @see RecurringOptions1
 */
class RecurringOptions1Builder
{
    /**
     * @var RecurringOptions1
     */
    private $instance;

    private function __construct(RecurringOptions1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Recurring Options 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new RecurringOptions1());
    }

    /**
     * Sets loan Payment field.
     *
     * @param bool|null $value
     */
    public function loanPayment(?bool $value): self
    {
        $this->instance->setLoanPayment($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Recurring Options 1 object.
     */
    public function build(): RecurringOptions1
    {
        return CoreHelper::clone($this->instance);
    }
}
