<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\RefundOptions2;

/**
 * Builder for model RefundOptions2
 *
 * @see RefundOptions2
 */
class RefundOptions2Builder
{
    /**
     * @var RefundOptions2
     */
    private $instance;

    private function __construct(RefundOptions2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Refund Options 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new RefundOptions2());
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Refund Options 2 object.
     */
    public function build(): RefundOptions2
    {
        return CoreHelper::clone($this->instance);
    }
}
