<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\SellerProtection3;

/**
 * Builder for model SellerProtection3
 *
 * @see SellerProtection3
 */
class SellerProtection3Builder
{
    /**
     * @var SellerProtection3
     */
    private $instance;

    private function __construct(SellerProtection3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Seller Protection 3 Builder object.
     */
    public static function init(): self
    {
        return new self(new SellerProtection3());
    }

    /**
     * Sets eligibilty field.
     *
     * @param string|null $value
     */
    public function eligibilty(?string $value): self
    {
        $this->instance->setEligibilty($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Seller Protection 3 object.
     */
    public function build(): SellerProtection3
    {
        return CoreHelper::clone($this->instance);
    }
}
