<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\ShipTo7;

/**
 * Builder for model ShipTo7
 *
 * @see ShipTo7
 */
class ShipTo7Builder
{
    /**
     * @var ShipTo7
     */
    private $instance;

    private function __construct(ShipTo7 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ship To 7 Builder object.
     */
    public static function init(): self
    {
        return new self(new ShipTo7());
    }

    /**
     * Sets first Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets address 1 field.
     *
     * @param string|null $value
     */
    public function address1(?string $value): self
    {
        $this->instance->setAddress1($value);
        return $this;
    }

    /**
     * Sets address 2 field.
     *
     * @param string|null $value
     */
    public function address2(?string $value): self
    {
        $this->instance->setAddress2($value);
        return $this;
    }

    /**
     * Sets locality field.
     *
     * @param string|null $value
     */
    public function locality(?string $value): self
    {
        $this->instance->setLocality($value);
        return $this;
    }

    /**
     * Sets administrative Area field.
     *
     * @param string|null $value
     */
    public function administrativeArea(?string $value): self
    {
        $this->instance->setAdministrativeArea($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Ship To 7 object.
     */
    public function build(): ShipTo7
    {
        return CoreHelper::clone($this->instance);
    }
}
