<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Links27;
use VisaAcceptanceMergedSpecLib\Models\Metadata4;
use VisaAcceptanceMergedSpecLib\Models\ShippingAddress16;
use VisaAcceptanceMergedSpecLib\Models\ShipTo14;

/**
 * Builder for model ShippingAddress16
 *
 * @see ShippingAddress16
 */
class ShippingAddress16Builder
{
    /**
     * @var ShippingAddress16
     */
    private $instance;

    private function __construct(ShippingAddress16 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shipping Address 16 Builder object.
     */
    public static function init(): self
    {
        return new self(new ShippingAddress16());
    }

    /**
     * Sets links field.
     *
     * @param Links27|null $value
     */
    public function links(?Links27 $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets default field.
     *
     * @param bool|null $value
     */
    public function default(?bool $value): self
    {
        $this->instance->setDefault($value);
        return $this;
    }

    /**
     * Sets ship To field.
     *
     * @param ShipTo14|null $value
     */
    public function shipTo(?ShipTo14 $value): self
    {
        $this->instance->setShipTo($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param Metadata4|null $value
     */
    public function metadata(?Metadata4 $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shipping Address 16 object.
     */
    public function build(): ShippingAddress16
    {
        return CoreHelper::clone($this->instance);
    }
}
