<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\Status;

/**
 * Builder for model Status
 *
 * @see Status
 */
class StatusBuilder
{
    /**
     * @var Status
     */
    private $instance;

    private function __construct(Status $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Status Builder object.
     */
    public static function init(): self
    {
        return new self(new Status());
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets method field.
     *
     * @param string|null $value
     */
    public function method(?string $value): self
    {
        $this->instance->setMethod($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Status object.
     */
    public function build(): Status
    {
        return CoreHelper::clone($this->instance);
    }
}
