<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\SubMerchant1;

/**
 * Builder for model SubMerchant1
 *
 * @see SubMerchant1
 */
class SubMerchant1Builder
{
    /**
     * @var SubMerchant1
     */
    private $instance;

    private function __construct(SubMerchant1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sub Merchant 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new SubMerchant1());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets address 1 field.
     *
     * @param string|null $value
     */
    public function address1(?string $value): self
    {
        $this->instance->setAddress1($value);
        return $this;
    }

    /**
     * Sets locality field.
     *
     * @param string|null $value
     */
    public function locality(?string $value): self
    {
        $this->instance->setLocality($value);
        return $this;
    }

    /**
     * Sets administrative Area field.
     *
     * @param string|null $value
     */
    public function administrativeArea(?string $value): self
    {
        $this->instance->setAdministrativeArea($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets phone Number field.
     *
     * @param string|null $value
     */
    public function phoneNumber(?string $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Sub Merchant 1 object.
     */
    public function build(): SubMerchant1
    {
        return CoreHelper::clone($this->instance);
    }
}
