<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\TaxDetails1;

/**
 * Builder for model TaxDetails1
 *
 * @see TaxDetails1
 */
class TaxDetails1Builder
{
    /**
     * @var TaxDetails1
     */
    private $instance;

    private function __construct(TaxDetails1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tax Details 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new TaxDetails1());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param string|null $value
     */
    public function amount(?string $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets rate field.
     *
     * @param string|null $value
     */
    public function rate(?string $value): self
    {
        $this->instance->setRate($value);
        return $this;
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets tax Id field.
     *
     * @param string|null $value
     */
    public function taxId(?string $value): self
    {
        $this->instance->setTaxId($value);
        return $this;
    }

    /**
     * Sets applied field.
     *
     * @param bool|null $value
     */
    public function applied(?bool $value): self
    {
        $this->instance->setApplied($value);
        return $this;
    }

    /**
     * Sets exemption Code field.
     *
     * @param string|null $value
     */
    public function exemptionCode(?string $value): self
    {
        $this->instance->setExemptionCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Tax Details 1 object.
     */
    public function build(): TaxDetails1
    {
        return CoreHelper::clone($this->instance);
    }
}
