<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\TravelInformation1;

/**
 * Builder for model TravelInformation1
 *
 * @see TravelInformation1
 */
class TravelInformation1Builder
{
    /**
     * @var TravelInformation1
     */
    private $instance;

    private function __construct(TravelInformation1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Travel Information 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new TravelInformation1());
    }

    /**
     * Sets duration field.
     *
     * @param string|null $value
     */
    public function duration(?string $value): self
    {
        $this->instance->setDuration($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Travel Information 1 object.
     */
    public function build(): TravelInformation1
    {
        return CoreHelper::clone($this->instance);
    }
}
