<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models\Builders;

use Core\Utils\CoreHelper;
use VisaAcceptanceMergedSpecLib\Models\UnscheduledPaymentInformation;

/**
 * Builder for model UnscheduledPaymentInformation
 *
 * @see UnscheduledPaymentInformation
 */
class UnscheduledPaymentInformationBuilder
{
    /**
     * @var UnscheduledPaymentInformation
     */
    private $instance;

    private function __construct(UnscheduledPaymentInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Unscheduled Payment Information Builder object.
     */
    public static function init(): self
    {
        return new self(new UnscheduledPaymentInformation());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Unscheduled Payment Information object.
     */
    public function build(): UnscheduledPaymentInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
