<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Exceptions;

use VisaAcceptanceMergedSpecLib\ApiHelper;

class PtsV1TransactionBatchesGet400Response1Exception extends ApiException
{
    /**
     * @var \VisaAcceptanceMergedSpecLib\Models\ErrorInformation2|null
     */
    private $errorInformation;

    /**
     * @var string|null
     */
    private $submitTimeUtc;

    /**
     * Returns Error Information.
     */
    public function getErrorInformation(): ?\VisaAcceptanceMergedSpecLib\Models\ErrorInformation2
    {
        return $this->errorInformation;
    }

    /**
     * Sets Error Information.
     *
     * @maps errorInformation
     */
    public function setErrorInformation(?\VisaAcceptanceMergedSpecLib\Models\ErrorInformation2 $errorInformation): void
    {
        $this->errorInformation = $errorInformation;
    }

    /**
     * Returns Submit Time Utc.
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`
     * **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.).
     * The `T` separates the date and the time. The `Z` indicates UTC.
     *
     * Returned by Visa Acceptance for all services.
     */
    public function getSubmitTimeUtc(): ?string
    {
        return $this->submitTimeUtc;
    }

    /**
     * Sets Submit Time Utc.
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`
     * **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.).
     * The `T` separates the date and the time. The `Z` indicates UTC.
     *
     * Returned by Visa Acceptance for all services.
     *
     * @maps submitTimeUtc
     */
    public function setSubmitTimeUtc(?string $submitTimeUtc): void
    {
        $this->submitTimeUtc = $submitTimeUtc;
    }

    /**
     * Converts the PtsV1TransactionBatchesGet400Response1Exception object to a human-readable string
     * representation.
     *
     * @return string The string representation of the PtsV1TransactionBatchesGet400Response1Exception object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PtsV1TransactionBatchesGet400Response1Exception',
            [
                'errorInformation' => $this->errorInformation,
                'submitTimeUtc' => $this->submitTimeUtc,
                'additionalProperties' => $this->additionalProperties
            ],
            parent::__toString()
        );
    }

    protected $propertyNames = ['errorInformation', 'submitTimeUtc'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
