<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class Account12 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $number;

    /**
     * @var string|null
     */
    private $iban;

    /**
     * Returns Number.
     * Account number.
     *
     * When processing encoded account numbers, use this field for the encoded account number.
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * Sets Number.
     * Account number.
     *
     * When processing encoded account numbers, use this field for the encoded account number.
     *
     * @maps number
     */
    public function setNumber(?string $number): void
    {
        $this->number = $number;
    }

    /**
     * Returns Iban.
     * International Bank Account Number (IBAN) for the bank account. For some countries you can provide
     * this number instead of the traditional bank account information. You can use this field only when
     * scoring a direct debit transaction.
     */
    public function getIban(): ?string
    {
        return $this->iban;
    }

    /**
     * Sets Iban.
     * International Bank Account Number (IBAN) for the bank account. For some countries you can provide
     * this number instead of the traditional bank account information. You can use this field only when
     * scoring a direct debit transaction.
     *
     * @maps iban
     */
    public function setIban(?string $iban): void
    {
        $this->iban = $iban;
    }

    /**
     * Converts the Account12 object to a human-readable string representation.
     *
     * @return string The string representation of the Account12 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Account12',
            [
                'number' => $this->number,
                'iban' => $this->iban,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['number', 'iban'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->number)) {
            $json['number'] = $this->number;
        }
        if (isset($this->iban)) {
            $json['iban']   = $this->iban;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
