<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class ActualFinalDestination implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $locality;

    /**
     * @var string|null
     */
    private $latitude;

    /**
     * @var string|null
     */
    private $longitude;

    /**
     * Returns Country.
     * Country of actual final destination on the route.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * Country of actual final destination on the route.
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Locality.
     * City of actual final destination on the route.
     */
    public function getLocality(): ?string
    {
        return $this->locality;
    }

    /**
     * Sets Locality.
     * City of actual final destination on the route.
     *
     * @maps locality
     */
    public function setLocality(?string $locality): void
    {
        $this->locality = $locality;
    }

    /**
     * Returns Latitude.
     * Latitude of actual final destination on the route.
     */
    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    /**
     * Sets Latitude.
     * Latitude of actual final destination on the route.
     *
     * @maps latitude
     */
    public function setLatitude(?string $latitude): void
    {
        $this->latitude = $latitude;
    }

    /**
     * Returns Longitude.
     * Longitude of actual final destination on the route.
     */
    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    /**
     * Sets Longitude.
     * Longitude of actual final destination on the route.
     *
     * @maps longitude
     */
    public function setLongitude(?string $longitude): void
    {
        $this->longitude = $longitude;
    }

    /**
     * Converts the ActualFinalDestination object to a human-readable string representation.
     *
     * @return string The string representation of the ActualFinalDestination object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ActualFinalDestination',
            [
                'country' => $this->country,
                'locality' => $this->locality,
                'latitude' => $this->latitude,
                'longitude' => $this->longitude,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['country', 'locality', 'latitude', 'longitude'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->country)) {
            $json['country']   = $this->country;
        }
        if (isset($this->locality)) {
            $json['locality']  = $this->locality;
        }
        if (isset($this->latitude)) {
            $json['latitude']  = $this->latitude;
        }
        if (isset($this->longitude)) {
            $json['longitude'] = $this->longitude;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
