<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class AuthorizationOptions implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $authType;

    /**
     * @var string|null
     */
    private $panReturnIndicator;

    /**
     * @var string|null
     */
    private $verbalAuthCode;

    /**
     * @var string|null
     */
    private $verbalAuthTransactionId;

    /**
     * @var string|null
     */
    private $authIndicator;

    /**
     * @var bool|null
     */
    private $partialAuthIndicator;

    /**
     * @var string|null
     */
    private $extendAuthIndicator;

    /**
     * @var bool|null
     */
    private $balanceInquiry;

    /**
     * @var bool|null
     */
    private $ignoreAvsResult = false;

    /**
     * @var string[]|null
     */
    private $declineAvsFlags;

    /**
     * @var bool|null
     */
    private $ignoreCvResult = false;

    /**
     * @var Initiator|null
     */
    private $initiator;

    /**
     * @var bool|null
     */
    private $billPayment;

    /**
     * @var string|null
     */
    private $billPaymentType;

    /**
     * @var bool|null
     */
    private $redemptionInquiry;

    /**
     * @var string|null
     */
    private $transportationMode;

    /**
     * @var string|null
     */
    private $aggregatedAuthIndicator;

    /**
     * @var string|null
     */
    private $debtRecoveryIndicator;

    /**
     * @var bool|null
     */
    private $deferredAuthIndicator;

    /**
     * @var bool|null
     */
    private $cashAdvanceIndicator;

    /**
     * @var bool|null
     */
    private $splitPaymentTransaction;

    /**
     * @var bool|null
     */
    private $cardVerificationIndicator;

    /**
     * @var string|null
     */
    private $transactionMode;

    /**
     * @var bool|null
     */
    private $aftIndicator;

    /**
     * @var string|null
     */
    private $serviceType;

    /**
     * @var bool|null
     */
    private $balanceUpdate;

    /**
     * @var bool|null
     */
    private $moneyLoad;

    /**
     * Returns Auth Type.
     * Authorization type. Possible values:
     *
     * - `AUTOCAPTURE`: automatic capture.
     * - `STANDARDCAPTURE`: standard capture.
     * - `VERBAL`: forced capture. Include it in the payment request for a forced capture. Include it in
     * the capture request for a verbal payment.
     *
     * #### Asia, Middle East, and Africa Gateway; Cielo; Comercio Latino; and Visa Acceptance Latin
     * American Processing
     * Set this field to `AUTOCAPTURE` and include it in a bundled request to indicate that you are
     * requesting an automatic capture. If your account is configured to enable automatic captures, set
     * this field to `STANDARDCAPTURE` and include it in a standard authorization or bundled request to
     * indicate that you are overriding an automatic capture.
     *
     * #### Forced Capture
     * Set this field to `VERBAL` and include it in the authorization request to indicate that you are
     * performing a forced capture; therefore, you receive the authorization code outside the Visa
     * Acceptance system.
     *
     * #### Verbal Authorization
     * Set this field to `VERBAL` and include it in the capture request to indicate that the request is for
     * a verbal authorization.
     *
     * #### for PayPal ptsV2CreateOrderPost400Response
     * Set this field to 'AUTHORIZE' or 'CAPTURE' depending on whether you want to invoke delayed capture
     * or sale respectively.
     */
    public function getAuthType(): ?string
    {
        return $this->authType;
    }

    /**
     * Sets Auth Type.
     * Authorization type. Possible values:
     *
     * - `AUTOCAPTURE`: automatic capture.
     * - `STANDARDCAPTURE`: standard capture.
     * - `VERBAL`: forced capture. Include it in the payment request for a forced capture. Include it in
     * the capture request for a verbal payment.
     *
     * #### Asia, Middle East, and Africa Gateway; Cielo; Comercio Latino; and Visa Acceptance Latin
     * American Processing
     * Set this field to `AUTOCAPTURE` and include it in a bundled request to indicate that you are
     * requesting an automatic capture. If your account is configured to enable automatic captures, set
     * this field to `STANDARDCAPTURE` and include it in a standard authorization or bundled request to
     * indicate that you are overriding an automatic capture.
     *
     * #### Forced Capture
     * Set this field to `VERBAL` and include it in the authorization request to indicate that you are
     * performing a forced capture; therefore, you receive the authorization code outside the Visa
     * Acceptance system.
     *
     * #### Verbal Authorization
     * Set this field to `VERBAL` and include it in the capture request to indicate that the request is for
     * a verbal authorization.
     *
     * #### for PayPal ptsV2CreateOrderPost400Response
     * Set this field to 'AUTHORIZE' or 'CAPTURE' depending on whether you want to invoke delayed capture
     * or sale respectively.
     *
     * @maps authType
     */
    public function setAuthType(?string $authType): void
    {
        $this->authType = $authType;
    }

    /**
     * Returns Pan Return Indicator.
     * #### Visa Platform Connect
     * The field contains the PAN translation indicator for American Express Contactless Transaction. Valid
     * value is
     *
     * 1- Expresspay Translation, PAN request
     * 2- Expresspay Translation, PAN and Expiry date request
     */
    public function getPanReturnIndicator(): ?string
    {
        return $this->panReturnIndicator;
    }

    /**
     * Sets Pan Return Indicator.
     * #### Visa Platform Connect
     * The field contains the PAN translation indicator for American Express Contactless Transaction. Valid
     * value is
     *
     * 1- Expresspay Translation, PAN request
     * 2- Expresspay Translation, PAN and Expiry date request
     *
     * @maps panReturnIndicator
     */
    public function setPanReturnIndicator(?string $panReturnIndicator): void
    {
        $this->panReturnIndicator = $panReturnIndicator;
    }

    /**
     * Returns Verbal Auth Code.
     * Authorization code.
     *
     * #### Forced Capture
     * Use this field to send the authorization code you received from a payment that you authorized
     * outside the Visa Acceptance system.
     *
     * #### PIN debit
     * Authorization code that is returned by the processor.
     *
     * Returned by PIN debit purchase.
     *
     * #### Verbal Authorization
     * Use this field in CAPTURE API to send the verbally received authorization code.
     */
    public function getVerbalAuthCode(): ?string
    {
        return $this->verbalAuthCode;
    }

    /**
     * Sets Verbal Auth Code.
     * Authorization code.
     *
     * #### Forced Capture
     * Use this field to send the authorization code you received from a payment that you authorized
     * outside the Visa Acceptance system.
     *
     * #### PIN debit
     * Authorization code that is returned by the processor.
     *
     * Returned by PIN debit purchase.
     *
     * #### Verbal Authorization
     * Use this field in CAPTURE API to send the verbally received authorization code.
     *
     * @maps verbalAuthCode
     */
    public function setVerbalAuthCode(?string $verbalAuthCode): void
    {
        $this->verbalAuthCode = $verbalAuthCode;
    }

    /**
     * Returns Verbal Auth Transaction Id.
     * Transaction ID (TID).
     *
     * #### FDMS South
     * This field is required for verbal authorizations and forced captures with the American Express card
     * type to comply
     * with the CAPN requirements:
     * - Forced capture: Obtain the value for this field from the authorization response.
     * - Verbal authorization: You cannot obtain a value for this field so Visa Acceptance uses the default
     * value of `000000000000000` (15
     * zeros).
     */
    public function getVerbalAuthTransactionId(): ?string
    {
        return $this->verbalAuthTransactionId;
    }

    /**
     * Sets Verbal Auth Transaction Id.
     * Transaction ID (TID).
     *
     * #### FDMS South
     * This field is required for verbal authorizations and forced captures with the American Express card
     * type to comply
     * with the CAPN requirements:
     * - Forced capture: Obtain the value for this field from the authorization response.
     * - Verbal authorization: You cannot obtain a value for this field so Visa Acceptance uses the default
     * value of `000000000000000` (15
     * zeros).
     *
     * @maps verbalAuthTransactionId
     */
    public function setVerbalAuthTransactionId(?string $verbalAuthTransactionId): void
    {
        $this->verbalAuthTransactionId = $verbalAuthTransactionId;
    }

    /**
     * Returns Auth Indicator.
     * Flag that specifies the purpose of the authorization.
     *
     * Possible values:
     * - **0**: Preauthorization
     * - **1**: Final authorization
     *
     * To set the default for this field, contact Visa Acceptance Customer Support.
     *
     * #### Barclays and Elavon
     * The default for Barclays and Elavon is 1 (final authorization). To change the default for this field,
     * contact Visa Acceptance Customer Support.
     *
     * #### Visa Acceptance through VisaNet
     * When the value for this field is 0, it corresponds to the following data in the TC 33 capture file:
     * - Record: CP01 TCR0
     * - Position: 164
     * - Field: Additional Authorization Indicators
     * When the value for this field is 1, it does not correspond to any data in the TC 33 capture file.
     */
    public function getAuthIndicator(): ?string
    {
        return $this->authIndicator;
    }

    /**
     * Sets Auth Indicator.
     * Flag that specifies the purpose of the authorization.
     *
     * Possible values:
     * - **0**: Preauthorization
     * - **1**: Final authorization
     *
     * To set the default for this field, contact Visa Acceptance Customer Support.
     *
     * #### Barclays and Elavon
     * The default for Barclays and Elavon is 1 (final authorization). To change the default for this field,
     * contact Visa Acceptance Customer Support.
     *
     * #### Visa Acceptance through VisaNet
     * When the value for this field is 0, it corresponds to the following data in the TC 33 capture file:
     * - Record: CP01 TCR0
     * - Position: 164
     * - Field: Additional Authorization Indicators
     * When the value for this field is 1, it does not correspond to any data in the TC 33 capture file.
     *
     * @maps authIndicator
     */
    public function setAuthIndicator(?string $authIndicator): void
    {
        $this->authIndicator = $authIndicator;
    }

    /**
     * Returns Partial Auth Indicator.
     * Flag that indicates whether the transaction is enabled for partial authorization. When the request
     * includes this
     * field, this value overrides the information in your account. Possible values:
     * - `true`: Enable the transaction for partial authorization.
     * - `false`: Do not enable the transaction for partial authorization.
     *
     * #### PIN debit
     * Required field for partial authorizations that use PIN debit purchase; otherwise, not used.
     *
     * #### Used by
     * **Authorization**
     * Optional field.
     *
     * #### Visa Acceptance through VisaNet
     * To set the default for this field, contact Visa Acceptance Customer Support.
     * The value for this field corresponds to the following data in the TC 33 capture file5:
     * - Record: CP01 TCR0
     * - Position: 164
     * - Field: Additional Authorization Indicators
     */
    public function getPartialAuthIndicator(): ?bool
    {
        return $this->partialAuthIndicator;
    }

    /**
     * Sets Partial Auth Indicator.
     * Flag that indicates whether the transaction is enabled for partial authorization. When the request
     * includes this
     * field, this value overrides the information in your account. Possible values:
     * - `true`: Enable the transaction for partial authorization.
     * - `false`: Do not enable the transaction for partial authorization.
     *
     * #### PIN debit
     * Required field for partial authorizations that use PIN debit purchase; otherwise, not used.
     *
     * #### Used by
     * **Authorization**
     * Optional field.
     *
     * #### Visa Acceptance through VisaNet
     * To set the default for this field, contact Visa Acceptance Customer Support.
     * The value for this field corresponds to the following data in the TC 33 capture file5:
     * - Record: CP01 TCR0
     * - Position: 164
     * - Field: Additional Authorization Indicators
     *
     * @maps partialAuthIndicator
     */
    public function setPartialAuthIndicator(?bool $partialAuthIndicator): void
    {
        $this->partialAuthIndicator = $partialAuthIndicator;
    }

    /**
     * Returns Extend Auth Indicator.
     * Indicates Authorization extension transaction. Extension transaction is used to prolong the
     * settlement period by one additional settlement cycle period.
     *
     * Possible values:
     * - true: Transaction is an Authorization Extension transaction.
     * - false: Transaction is not an Authorization Extension transaction.
     */
    public function getExtendAuthIndicator(): ?string
    {
        return $this->extendAuthIndicator;
    }

    /**
     * Sets Extend Auth Indicator.
     * Indicates Authorization extension transaction. Extension transaction is used to prolong the
     * settlement period by one additional settlement cycle period.
     *
     * Possible values:
     * - true: Transaction is an Authorization Extension transaction.
     * - false: Transaction is not an Authorization Extension transaction.
     *
     * @maps extendAuthIndicator
     */
    public function setExtendAuthIndicator(?string $extendAuthIndicator): void
    {
        $this->extendAuthIndicator = $extendAuthIndicator;
    }

    /**
     * Returns Balance Inquiry.
     * Flag that indicates whether to return balance information.
     *
     * Possible values:
     * - `true`: Return balance information.
     * - `false`: Do not return balance information.
     *
     * #### Used by
     * **Authorization**
     * Required for a balance inquiry; otherwise, not used.
     *
     * #### PIN debit
     * Required for a balance inquiry request of a PIN debit purchase; otherwise, not used.
     */
    public function getBalanceInquiry(): ?bool
    {
        return $this->balanceInquiry;
    }

    /**
     * Sets Balance Inquiry.
     * Flag that indicates whether to return balance information.
     *
     * Possible values:
     * - `true`: Return balance information.
     * - `false`: Do not return balance information.
     *
     * #### Used by
     * **Authorization**
     * Required for a balance inquiry; otherwise, not used.
     *
     * #### PIN debit
     * Required for a balance inquiry request of a PIN debit purchase; otherwise, not used.
     *
     * @maps balanceInquiry
     */
    public function setBalanceInquiry(?bool $balanceInquiry): void
    {
        $this->balanceInquiry = $balanceInquiry;
    }

    /**
     * Returns Ignore Avs Result.
     * Flag for a sale request that indicates whether to allow the capture service to run even when the
     * authorization
     * receives an AVS decline, as indicated by a reply flag value of DAVSNO.
     *
     * Possible values:
     * - `true`: Ignore the results of AVS checking and run the capture service.
     * - `false` (default): If the authorization receives an AVS decline, do not run the capture service.
     * When the value of this field is `true`, the list in the `processingInformation.authorizationOptions.
     * declineAvsFlags` field is ignored.
     *
     * #### Used by
     * **Authorization**
     * Optional field.
     * String (3)
     */
    public function getIgnoreAvsResult(): ?bool
    {
        return $this->ignoreAvsResult;
    }

    /**
     * Sets Ignore Avs Result.
     * Flag for a sale request that indicates whether to allow the capture service to run even when the
     * authorization
     * receives an AVS decline, as indicated by a reply flag value of DAVSNO.
     *
     * Possible values:
     * - `true`: Ignore the results of AVS checking and run the capture service.
     * - `false` (default): If the authorization receives an AVS decline, do not run the capture service.
     * When the value of this field is `true`, the list in the `processingInformation.authorizationOptions.
     * declineAvsFlags` field is ignored.
     *
     * #### Used by
     * **Authorization**
     * Optional field.
     * String (3)
     *
     * @maps ignoreAvsResult
     */
    public function setIgnoreAvsResult(?bool $ignoreAvsResult): void
    {
        $this->ignoreAvsResult = $ignoreAvsResult;
    }

    /**
     * Returns Decline Avs Flags.
     * Comma-separated list of AVS flags that cause the reply flag `DAVSNO` to be returned.
     *
     * **Important** To receive declines for the AVS code `N`, you must include the value `N` in the comma-
     * separated
     * list.
     *
     * ### AVS Codes for Cielo 3.0 and Visa Acceptance Latin American Processing
     *
     * **Note** Visa Acceptance Latin American Processing is the name of a specific processing connection
     * that Visa Acceptance supports.
     * In the Visa Acceptance API documentation, Visa Acceptance Latin American Processing does not refer
     * to the general topic of processing in Latin America.
     * The information in this section is for the specific processing connection called Visa Acceptance
     * Latin American Processing.
     * It is not for any other Latin American processors that Visa Acceptance supports.
     *
     * |AVS Code|Description|
     * |--- |--- |
     * |D|Partial match: postal code and address match.|
     * |E|Not supported: AVS is not supported for this card type. _or_ Invalid: the acquirer returned an
     * unrecognized value for the AVS response.|
     * |F|Partial match: postal code matches, but CPF and address do not match.*|
     * |G|Not supported: AVS not supported or not verified.|
     * |I|No match: AVS information is not available.|
     * |K|Partial match: CPF matches, but postal code and address do not match.*|
     * |L|Partial match: postal code and CPF match, but address does not match.*|
     * |N|No match: postal code, CPF, and address do not match.*|
     * |O|Partial match: CPF and address match, but postal code does not match.*|
     * |R|Not supported: your implementation does not support AVS _or_ System unavailable.|
     * |T|Partial match: address matches, but postal code and CPF do not match.*|
     * |V|Match: postal code, CPF, and address match.*|
     * |* CPF (Cadastro de Pessoas Fisicas) is required only for Redecard in Brazil.||
     *
     * ### AVS Codes for All Other Processors
     *
     * **Note** The list of AVS codes for all other processors follows these descriptions of the processor-
     * specific information for these codes.
     *
     * #### American Express Cards
     * For American Express cards only, you can receive Visa and Visa Acceptance
     * AVS codes in addition to the American Express AVS codes.
     *
     * **Note** For Visa Acceptance through VisaNet, the American Express AVS codes are converted to Visa
     * AVS codes before they are returned to you. As a result, you will not receive American Express AVS
     * codes for
     * the American Express card type.<br/><br/>
     *
     * _American Express Card codes_: `F`, `H`, `K`, `L`, `O`, `T`, `V`
     *
     * #### Domestic and International Visa Cards
     * The international and domestic alphabetic AVS codes are the Visa standard AVS codes. Visa Acceptance
     * maps
     * the standard AVS return codes for other types of payment cards, including American Express cards,
     * to
     * the Visa standard AVS codes.
     *
     * AVS is considered either domestic or international, depending on the location of the bank that
     * issued the
     * customer's payment card:
     * - When the bank is in the U.S., the AVS is domestic.
     * - When the bank is outside the U.S., the AVS is international.
     *
     * You should be prepared to handle both domestic and international AVS result codes:
     * - For international cards, you can receive domestic AVS codes in addition to the international AVS
     * codes.
     * - For domestic cards, you can receive international AVS codes in addition to the domestic AVS codes.
     *
     * _International Visa Codes_: `B`, `C`, `D`, `G`, `I`, `M`, `P`
     *
     * _Domestic Visa Codes_: `A`, `E`,`N`, `R`, `S`, `U`, `W`, `X`, `Y`, `Z`
     *
     * #### Visa Acceptance Codes
     * The numeric AVS codes are created by Visa Acceptance
     * and are not standard Visa codes. These AVS codes
     * can be returned for any card type.
     *
     * _Visa Acceptance Codes_: `1`, `2`, `3`, `4`
     *
     * ### Table of AVS Codes for All Other Processors
     *
     * |AVS Code|Description|
     * |--- |--- |
     * |A|Partial match: street address matches, but 5-digit and 9-digit postal codes do not match.|
     * |B|Partial match: street address matches, but postal code is not verified. Returned only for Visa
     * cards not issued in the U.S.|
     * |C|No match: street address and postal code do not match. Returned only for Visa cards not issued in
     * the U.S.|
     * |D & M|Match: street address and postal code match. Returned only for Visa cards not issued in the U.
     * S.|
     * |E|Invalid: AVS data is invalid or AVS is not allowed for this card type.|
     * |F|Partial match: card member’s name does not match, but billing postal code matches.|
     * |G|Not supported: issuing bank outside the U.S. does not support AVS.|
     * |H|Partial match: card member’s name does not match, but street address and postal code match.
     * Returned only for the American Express card type.|
     * |I|No match: address not verified. Returned only for Visa cards not issued in the U.S.|
     * |K|Partial match: card member’s name matches, but billing address and billing postal code do not
     * match. Returned only for the American Express card type.|
     * |L|Partial match: card member’s name and billing postal code match, but billing address does not
     * match. Returned only for the American Express card type.|
     * |M|See the entry for D & M.|
     * |N|No match: one of the following: street address and postal code do not match _or_ (American
     * Express card type only) card member’s name, street address, and postal code do not match.|
     * |O|Partial match: card member’s name and billing address match, but billing postal code does not
     * match. Returned only for the American Express card type.|
     * |P|Partial match: postal code matches, but street address not verified. Returned only for Visa cards
     * not issued in the U.S.|
     * |R|System unavailable.|
     * |S|Not supported: issuing bank in the U.S. does not support AVS.|
     * |T|Partial match: card member’s name does not match, but street address matches. Returned only for
     * the American Express card type.|
     * |U|System unavailable: address information unavailable for one of these reasons: The U.S. bank does
     * not support AVS outside the U.S. _or_ The AVS in a U.S. bank is not functioning properly.|
     * |V|Match: card member’s name, billing address, and billing postal code match. Returned only for the
     * American Express card type.|
     * |W|Partial match: street address does not match, but 9-digit postal code matches.|
     * |X|Match: street address and 9-digit postal code match.|
     * |Y|Match: street address and 5-digit postal code match.|
     * |Z|Partial match: street address does not match, but 5-digit postal code matches.|
     * |1|Not supported: one of the following: AVS is not supported for this processor or card type _or_
     * AVS is disabled for your Visa Acceptance account. To enable AVS, contact Visa Acceptance Customer
     * Support.|
     * |2|Unrecognized: the processor returned an unrecognized value for the AVS response.|
     * |3|Match: address is confirmed. Returned only for PayPal Express Checkout.|
     * |4|No match: address is not confirmed. Returned only for PayPal Express Checkout.|
     * |5|No match: no AVS code was returned by the processor.|
     *
     * @return string[]|null
     */
    public function getDeclineAvsFlags(): ?array
    {
        return $this->declineAvsFlags;
    }

    /**
     * Sets Decline Avs Flags.
     * Comma-separated list of AVS flags that cause the reply flag `DAVSNO` to be returned.
     *
     * **Important** To receive declines for the AVS code `N`, you must include the value `N` in the comma-
     * separated
     * list.
     *
     * ### AVS Codes for Cielo 3.0 and Visa Acceptance Latin American Processing
     *
     * **Note** Visa Acceptance Latin American Processing is the name of a specific processing connection
     * that Visa Acceptance supports.
     * In the Visa Acceptance API documentation, Visa Acceptance Latin American Processing does not refer
     * to the general topic of processing in Latin America.
     * The information in this section is for the specific processing connection called Visa Acceptance
     * Latin American Processing.
     * It is not for any other Latin American processors that Visa Acceptance supports.
     *
     * |AVS Code|Description|
     * |--- |--- |
     * |D|Partial match: postal code and address match.|
     * |E|Not supported: AVS is not supported for this card type. _or_ Invalid: the acquirer returned an
     * unrecognized value for the AVS response.|
     * |F|Partial match: postal code matches, but CPF and address do not match.*|
     * |G|Not supported: AVS not supported or not verified.|
     * |I|No match: AVS information is not available.|
     * |K|Partial match: CPF matches, but postal code and address do not match.*|
     * |L|Partial match: postal code and CPF match, but address does not match.*|
     * |N|No match: postal code, CPF, and address do not match.*|
     * |O|Partial match: CPF and address match, but postal code does not match.*|
     * |R|Not supported: your implementation does not support AVS _or_ System unavailable.|
     * |T|Partial match: address matches, but postal code and CPF do not match.*|
     * |V|Match: postal code, CPF, and address match.*|
     * |* CPF (Cadastro de Pessoas Fisicas) is required only for Redecard in Brazil.||
     *
     * ### AVS Codes for All Other Processors
     *
     * **Note** The list of AVS codes for all other processors follows these descriptions of the processor-
     * specific information for these codes.
     *
     * #### American Express Cards
     * For American Express cards only, you can receive Visa and Visa Acceptance
     * AVS codes in addition to the American Express AVS codes.
     *
     * **Note** For Visa Acceptance through VisaNet, the American Express AVS codes are converted to Visa
     * AVS codes before they are returned to you. As a result, you will not receive American Express AVS
     * codes for
     * the American Express card type.<br/><br/>
     *
     * _American Express Card codes_: `F`, `H`, `K`, `L`, `O`, `T`, `V`
     *
     * #### Domestic and International Visa Cards
     * The international and domestic alphabetic AVS codes are the Visa standard AVS codes. Visa Acceptance
     * maps
     * the standard AVS return codes for other types of payment cards, including American Express cards,
     * to
     * the Visa standard AVS codes.
     *
     * AVS is considered either domestic or international, depending on the location of the bank that
     * issued the
     * customer's payment card:
     * - When the bank is in the U.S., the AVS is domestic.
     * - When the bank is outside the U.S., the AVS is international.
     *
     * You should be prepared to handle both domestic and international AVS result codes:
     * - For international cards, you can receive domestic AVS codes in addition to the international AVS
     * codes.
     * - For domestic cards, you can receive international AVS codes in addition to the domestic AVS codes.
     *
     * _International Visa Codes_: `B`, `C`, `D`, `G`, `I`, `M`, `P`
     *
     * _Domestic Visa Codes_: `A`, `E`,`N`, `R`, `S`, `U`, `W`, `X`, `Y`, `Z`
     *
     * #### Visa Acceptance Codes
     * The numeric AVS codes are created by Visa Acceptance
     * and are not standard Visa codes. These AVS codes
     * can be returned for any card type.
     *
     * _Visa Acceptance Codes_: `1`, `2`, `3`, `4`
     *
     * ### Table of AVS Codes for All Other Processors
     *
     * |AVS Code|Description|
     * |--- |--- |
     * |A|Partial match: street address matches, but 5-digit and 9-digit postal codes do not match.|
     * |B|Partial match: street address matches, but postal code is not verified. Returned only for Visa
     * cards not issued in the U.S.|
     * |C|No match: street address and postal code do not match. Returned only for Visa cards not issued in
     * the U.S.|
     * |D & M|Match: street address and postal code match. Returned only for Visa cards not issued in the U.
     * S.|
     * |E|Invalid: AVS data is invalid or AVS is not allowed for this card type.|
     * |F|Partial match: card member’s name does not match, but billing postal code matches.|
     * |G|Not supported: issuing bank outside the U.S. does not support AVS.|
     * |H|Partial match: card member’s name does not match, but street address and postal code match.
     * Returned only for the American Express card type.|
     * |I|No match: address not verified. Returned only for Visa cards not issued in the U.S.|
     * |K|Partial match: card member’s name matches, but billing address and billing postal code do not
     * match. Returned only for the American Express card type.|
     * |L|Partial match: card member’s name and billing postal code match, but billing address does not
     * match. Returned only for the American Express card type.|
     * |M|See the entry for D & M.|
     * |N|No match: one of the following: street address and postal code do not match _or_ (American
     * Express card type only) card member’s name, street address, and postal code do not match.|
     * |O|Partial match: card member’s name and billing address match, but billing postal code does not
     * match. Returned only for the American Express card type.|
     * |P|Partial match: postal code matches, but street address not verified. Returned only for Visa cards
     * not issued in the U.S.|
     * |R|System unavailable.|
     * |S|Not supported: issuing bank in the U.S. does not support AVS.|
     * |T|Partial match: card member’s name does not match, but street address matches. Returned only for
     * the American Express card type.|
     * |U|System unavailable: address information unavailable for one of these reasons: The U.S. bank does
     * not support AVS outside the U.S. _or_ The AVS in a U.S. bank is not functioning properly.|
     * |V|Match: card member’s name, billing address, and billing postal code match. Returned only for the
     * American Express card type.|
     * |W|Partial match: street address does not match, but 9-digit postal code matches.|
     * |X|Match: street address and 9-digit postal code match.|
     * |Y|Match: street address and 5-digit postal code match.|
     * |Z|Partial match: street address does not match, but 5-digit postal code matches.|
     * |1|Not supported: one of the following: AVS is not supported for this processor or card type _or_
     * AVS is disabled for your Visa Acceptance account. To enable AVS, contact Visa Acceptance Customer
     * Support.|
     * |2|Unrecognized: the processor returned an unrecognized value for the AVS response.|
     * |3|Match: address is confirmed. Returned only for PayPal Express Checkout.|
     * |4|No match: address is not confirmed. Returned only for PayPal Express Checkout.|
     * |5|No match: no AVS code was returned by the processor.|
     *
     * @maps declineAvsFlags
     *
     * @param string[]|null $declineAvsFlags
     */
    public function setDeclineAvsFlags(?array $declineAvsFlags): void
    {
        $this->declineAvsFlags = $declineAvsFlags;
    }

    /**
     * Returns Ignore Cv Result.
     * Flag for a sale request that indicates whether to allow the capture service to run even when the
     * authorization receives a CVN decline, as indicated by an `processorInformation.cardVerification.
     * resultCode` value of `D` or `N`.
     * Possible values:
     * - `true`: Ignore the results of CVN checking and run the capture service.
     * - `false` (default): If the authorization receives a CVN decline, do not run the capture service.
     *
     * #### Used by
     * **Authorization**
     * Optional field.
     */
    public function getIgnoreCvResult(): ?bool
    {
        return $this->ignoreCvResult;
    }

    /**
     * Sets Ignore Cv Result.
     * Flag for a sale request that indicates whether to allow the capture service to run even when the
     * authorization receives a CVN decline, as indicated by an `processorInformation.cardVerification.
     * resultCode` value of `D` or `N`.
     * Possible values:
     * - `true`: Ignore the results of CVN checking and run the capture service.
     * - `false` (default): If the authorization receives a CVN decline, do not run the capture service.
     *
     * #### Used by
     * **Authorization**
     * Optional field.
     *
     * @maps ignoreCvResult
     */
    public function setIgnoreCvResult(?bool $ignoreCvResult): void
    {
        $this->ignoreCvResult = $ignoreCvResult;
    }

    /**
     * Returns Initiator.
     */
    public function getInitiator(): ?Initiator
    {
        return $this->initiator;
    }

    /**
     * Sets Initiator.
     *
     * @maps initiator
     */
    public function setInitiator(?Initiator $initiator): void
    {
        $this->initiator = $initiator;
    }

    /**
     * Returns Bill Payment.
     * Indicates payment for bill or payment towards existing contractual loan.
     *
     * Possible values:
     * - `true`: Bill payment or loan payment.
     * - `false` (default): Not a bill payment or loan payment.
     *
     * Optional request field.
     */
    public function getBillPayment(): ?bool
    {
        return $this->billPayment;
    }

    /**
     * Sets Bill Payment.
     * Indicates payment for bill or payment towards existing contractual loan.
     *
     * Possible values:
     * - `true`: Bill payment or loan payment.
     * - `false` (default): Not a bill payment or loan payment.
     *
     * Optional request field.
     *
     * @maps billPayment
     */
    public function setBillPayment(?bool $billPayment): void
    {
        $this->billPayment = $billPayment;
    }

    /**
     * Returns Bill Payment Type.
     * Reason for the payment.
     *
     * Possible values:
     * - 001: Public utilities / Utility payment
     * - 002: Government services
     * - 003: Cellular / Mobile phone top-up
     * - 004: Coupon payment
     * - 005: Installment based repayment
     * - 006: Billing payment
     * - 007: Tax payment
     * - 008: Tax payment refunds
     *
     * The value for this field corresponds to the following data in the TC 33A capture file (applicable to
     * Brazil):
     * - Record: CP07 TCR0
     * - Position: 48-50
     * - Field: Bill Payment Transaction Type Identifier
     *
     * The value for this field corresponds to the following data in the TC 33A capture file (applicable to
     * Installment)
     * based Repayment):
     * - Record: CP01 TCR6
     * - Position: 154-156
     * - Field: Bill Payment Transaction Type Identifier
     *
     *
     * This field is supported for
     * 1. Bill payments in Brazil with Mastercard on Visa Acceptance through VisaNet.
     * 2. Installment based repayment transactions on Visa Acceptance through VisaNet.
     */
    public function getBillPaymentType(): ?string
    {
        return $this->billPaymentType;
    }

    /**
     * Sets Bill Payment Type.
     * Reason for the payment.
     *
     * Possible values:
     * - 001: Public utilities / Utility payment
     * - 002: Government services
     * - 003: Cellular / Mobile phone top-up
     * - 004: Coupon payment
     * - 005: Installment based repayment
     * - 006: Billing payment
     * - 007: Tax payment
     * - 008: Tax payment refunds
     *
     * The value for this field corresponds to the following data in the TC 33A capture file (applicable to
     * Brazil):
     * - Record: CP07 TCR0
     * - Position: 48-50
     * - Field: Bill Payment Transaction Type Identifier
     *
     * The value for this field corresponds to the following data in the TC 33A capture file (applicable to
     * Installment)
     * based Repayment):
     * - Record: CP01 TCR6
     * - Position: 154-156
     * - Field: Bill Payment Transaction Type Identifier
     *
     *
     * This field is supported for
     * 1. Bill payments in Brazil with Mastercard on Visa Acceptance through VisaNet.
     * 2. Installment based repayment transactions on Visa Acceptance through VisaNet.
     *
     * @maps billPaymentType
     */
    public function setBillPaymentType(?string $billPaymentType): void
    {
        $this->billPaymentType = $billPaymentType;
    }

    /**
     * Returns Redemption Inquiry.
     * Flag that indicates the payment request is a redemption inquiry.
     *
     * Possible values:
     * - `true`
     * - `false`
     */
    public function getRedemptionInquiry(): ?bool
    {
        return $this->redemptionInquiry;
    }

    /**
     * Sets Redemption Inquiry.
     * Flag that indicates the payment request is a redemption inquiry.
     *
     * Possible values:
     * - `true`
     * - `false`
     *
     * @maps redemptionInquiry
     */
    public function setRedemptionInquiry(?bool $redemptionInquiry): void
    {
        $this->redemptionInquiry = $redemptionInquiry;
    }

    /**
     * Returns Transportation Mode.
     * Type of transportation mode :
     *
     * Possible Values:
     * - 00 = Unknown
     * - 01 = Urban bus
     * - 02 = Interurban bus
     * - 03=Lighttrainmasstransit(Underground Metro LTR)
     * - 04 = Train
     * - 05 = Commuter train
     * - 06 = Water-borne vehicle
     * - 07 = Toll
     * - 08 = Parking
     * - 09 = Taxi
     * - 10 = High-speed train
     * - 11 = Rural bus
     * - 12 = Express commuter train
     * - 13 = Para transit
     * - 14 = Self drive vehicle
     * - 15 = Coach
     * - 16 = Locomotive
     * - 17 = Powered motor coach
     * - 18 = Trailer
     * - 19 = Regional train
     * - 20 = Inter-city
     * - 21 = Funicular train
     * - 22 = Cable car
     */
    public function getTransportationMode(): ?string
    {
        return $this->transportationMode;
    }

    /**
     * Sets Transportation Mode.
     * Type of transportation mode :
     *
     * Possible Values:
     * - 00 = Unknown
     * - 01 = Urban bus
     * - 02 = Interurban bus
     * - 03=Lighttrainmasstransit(Underground Metro LTR)
     * - 04 = Train
     * - 05 = Commuter train
     * - 06 = Water-borne vehicle
     * - 07 = Toll
     * - 08 = Parking
     * - 09 = Taxi
     * - 10 = High-speed train
     * - 11 = Rural bus
     * - 12 = Express commuter train
     * - 13 = Para transit
     * - 14 = Self drive vehicle
     * - 15 = Coach
     * - 16 = Locomotive
     * - 17 = Powered motor coach
     * - 18 = Trailer
     * - 19 = Regional train
     * - 20 = Inter-city
     * - 21 = Funicular train
     * - 22 = Cable car
     *
     * @maps transportationMode
     */
    public function setTransportationMode(?string $transportationMode): void
    {
        $this->transportationMode = $transportationMode;
    }

    /**
     * Returns Aggregated Auth Indicator.
     * Indicates if transaction is an aggregated auth
     *
     * Possible values:
     * - **true**
     * - **false**
     */
    public function getAggregatedAuthIndicator(): ?string
    {
        return $this->aggregatedAuthIndicator;
    }

    /**
     * Sets Aggregated Auth Indicator.
     * Indicates if transaction is an aggregated auth
     *
     * Possible values:
     * - **true**
     * - **false**
     *
     * @maps aggregatedAuthIndicator
     */
    public function setAggregatedAuthIndicator(?string $aggregatedAuthIndicator): void
    {
        $this->aggregatedAuthIndicator = $aggregatedAuthIndicator;
    }

    /**
     * Returns Debt Recovery Indicator.
     * Indicates if transaction is a debt recovery request
     *
     * Possible values:
     * - **true**
     * - **false**
     */
    public function getDebtRecoveryIndicator(): ?string
    {
        return $this->debtRecoveryIndicator;
    }

    /**
     * Sets Debt Recovery Indicator.
     * Indicates if transaction is a debt recovery request
     *
     * Possible values:
     * - **true**
     * - **false**
     *
     * @maps debtRecoveryIndicator
     */
    public function setDebtRecoveryIndicator(?string $debtRecoveryIndicator): void
    {
        $this->debtRecoveryIndicator = $debtRecoveryIndicator;
    }

    /**
     * Returns Deferred Auth Indicator.
     * Flag that indicates whether the authorization request was delayed because connectivity was
     * interrupted.
     *
     * Possible values:
     * - `true` (Deferred authorization)
     * - `false` (default: Not a deferred authorization)
     */
    public function getDeferredAuthIndicator(): ?bool
    {
        return $this->deferredAuthIndicator;
    }

    /**
     * Sets Deferred Auth Indicator.
     * Flag that indicates whether the authorization request was delayed because connectivity was
     * interrupted.
     *
     * Possible values:
     * - `true` (Deferred authorization)
     * - `false` (default: Not a deferred authorization)
     *
     * @maps deferredAuthIndicator
     */
    public function setDeferredAuthIndicator(?bool $deferredAuthIndicator): void
    {
        $this->deferredAuthIndicator = $deferredAuthIndicator;
    }

    /**
     * Returns Cash Advance Indicator.
     * This API field enables the merchant to indicate that a given transaction is Cash Advance.
     *
     * Cash advance or Cash disbursement functionality allows a merchant to dispense cash at a point of
     * sale.
     * It provides the ability of a POS system to act like an ATM. These terminals are typically seen in
     * bank
     * branches where customers can use their card and withdraw cash or at merchant locations where ATMs
     * are sparse.
     *
     * Possible values:
     * - `true` (Cash advance is supported)
     * - `false` (default: cash advance is not supported)
     */
    public function getCashAdvanceIndicator(): ?bool
    {
        return $this->cashAdvanceIndicator;
    }

    /**
     * Sets Cash Advance Indicator.
     * This API field enables the merchant to indicate that a given transaction is Cash Advance.
     *
     * Cash advance or Cash disbursement functionality allows a merchant to dispense cash at a point of
     * sale.
     * It provides the ability of a POS system to act like an ATM. These terminals are typically seen in
     * bank
     * branches where customers can use their card and withdraw cash or at merchant locations where ATMs
     * are sparse.
     *
     * Possible values:
     * - `true` (Cash advance is supported)
     * - `false` (default: cash advance is not supported)
     *
     * @maps cashAdvanceIndicator
     */
    public function setCashAdvanceIndicator(?bool $cashAdvanceIndicator): void
    {
        $this->cashAdvanceIndicator = $cashAdvanceIndicator;
    }

    /**
     * Returns Split Payment Transaction.
     * #### Visa Platform Connect
     * Indicates split payment transaction. A split payment allows the use of two payment methods for a
     * single transaction.
     *
     * Possible values:
     * - `true` (split payment transaction is supported)
     * - `false` (default: split payment transaction is not supported)
     */
    public function getSplitPaymentTransaction(): ?bool
    {
        return $this->splitPaymentTransaction;
    }

    /**
     * Sets Split Payment Transaction.
     * #### Visa Platform Connect
     * Indicates split payment transaction. A split payment allows the use of two payment methods for a
     * single transaction.
     *
     * Possible values:
     * - `true` (split payment transaction is supported)
     * - `false` (default: split payment transaction is not supported)
     *
     * @maps splitPaymentTransaction
     */
    public function setSplitPaymentTransaction(?bool $splitPaymentTransaction): void
    {
        $this->splitPaymentTransaction = $splitPaymentTransaction;
    }

    /**
     * Returns Card Verification Indicator.
     * This API field will indicate whether a card verification check is being performed during the
     * transaction
     *
     * Possible values:
     * - `true`
     * - `false` (default value)
     */
    public function getCardVerificationIndicator(): ?bool
    {
        return $this->cardVerificationIndicator;
    }

    /**
     * Sets Card Verification Indicator.
     * This API field will indicate whether a card verification check is being performed during the
     * transaction
     *
     * Possible values:
     * - `true`
     * - `false` (default value)
     *
     * @maps cardVerificationIndicator
     */
    public function setCardVerificationIndicator(?bool $cardVerificationIndicator): void
    {
        $this->cardVerificationIndicator = $cardVerificationIndicator;
    }

    /**
     * Returns Transaction Mode.
     * Transaction mode identifier. Identifies the specific channel from which the transaction originates.
     *
     * Possible values:
     * - M – Mobile Order
     * - T – Telephone Order
     */
    public function getTransactionMode(): ?string
    {
        return $this->transactionMode;
    }

    /**
     * Sets Transaction Mode.
     * Transaction mode identifier. Identifies the specific channel from which the transaction originates.
     *
     * Possible values:
     * - M – Mobile Order
     * - T – Telephone Order
     *
     * @maps transactionMode
     */
    public function setTransactionMode(?string $transactionMode): void
    {
        $this->transactionMode = $transactionMode;
    }

    /**
     * Returns Aft Indicator.
     * Indicates whether the transaction is an Account Funding Transaction (AFT).
     * This field is mandatory for Account Funding Transactions (AFT).
     *
     * Possible values:
     * - `true` (This is an AFT transaction)
     * - `false` (default value) (This is not an AFT transaction)
     */
    public function getAftIndicator(): ?bool
    {
        return $this->aftIndicator;
    }

    /**
     * Sets Aft Indicator.
     * Indicates whether the transaction is an Account Funding Transaction (AFT).
     * This field is mandatory for Account Funding Transactions (AFT).
     *
     * Possible values:
     * - `true` (This is an AFT transaction)
     * - `false` (default value) (This is not an AFT transaction)
     *
     * @maps aftIndicator
     */
    public function setAftIndicator(?bool $aftIndicator): void
    {
        $this->aftIndicator = $aftIndicator;
    }

    /**
     * Returns Service Type.
     * Field is used for back-to-back funding transaction and can be defined as a payment flow that
     * automatically transfers funds through a real-time
     * funding or a live-load. This type of transaction can also be connected to a purchase.
     * In back-to-back funding of general purpose card that is used to make a purchase, two separate
     * accounts are involved:
     * - account one is used to make the purchase
     * - account two is used to automatically fund or reimburse account one
     *
     * Possible values:
     * - 0B = back to back funding transaction
     * - 00 = normal transaction
     * - 01 = originator hold
     * - 02 = Visa deferred OCT hold, default interval
     * - 03 = Visa deferred OCT hold, user-defined interval
     * - 09 = Cancel pending deferred OCT request
     * - 0I = Visa Direct custom program 1
     * - 0Q = uery the status of the deferred OCT
     * - A0 = Alias Directory 2
     */
    public function getServiceType(): ?string
    {
        return $this->serviceType;
    }

    /**
     * Sets Service Type.
     * Field is used for back-to-back funding transaction and can be defined as a payment flow that
     * automatically transfers funds through a real-time
     * funding or a live-load. This type of transaction can also be connected to a purchase.
     * In back-to-back funding of general purpose card that is used to make a purchase, two separate
     * accounts are involved:
     * - account one is used to make the purchase
     * - account two is used to automatically fund or reimburse account one
     *
     * Possible values:
     * - 0B = back to back funding transaction
     * - 00 = normal transaction
     * - 01 = originator hold
     * - 02 = Visa deferred OCT hold, default interval
     * - 03 = Visa deferred OCT hold, user-defined interval
     * - 09 = Cancel pending deferred OCT request
     * - 0I = Visa Direct custom program 1
     * - 0Q = uery the status of the deferred OCT
     * - A0 = Alias Directory 2
     *
     * @maps serviceType
     */
    public function setServiceType(?string $serviceType): void
    {
        $this->serviceType = $serviceType;
    }

    /**
     * Returns Balance Update.
     * Merchant to inform Visa Acceptance whether a transaction is Money load with Balance Update.
     *
     * Possible values:
     * - `true` (This is a Money load with balance update transaction)
     * - `false` (default value) (This is not a Money load with balance update transaction)
     */
    public function getBalanceUpdate(): ?bool
    {
        return $this->balanceUpdate;
    }

    /**
     * Sets Balance Update.
     * Merchant to inform Visa Acceptance whether a transaction is Money load with Balance Update.
     *
     * Possible values:
     * - `true` (This is a Money load with balance update transaction)
     * - `false` (default value) (This is not a Money load with balance update transaction)
     *
     * @maps balanceUpdate
     */
    public function setBalanceUpdate(?bool $balanceUpdate): void
    {
        $this->balanceUpdate = $balanceUpdate;
    }

    /**
     * Returns Money Load.
     * Merchant to inform Visa Acceptance whether a transaction is Money load with Money load only.
     *
     * Possible values:
     * - `true` (This is a money load transaction)
     * - `false` (default value) (This is not a money load transaction)
     */
    public function getMoneyLoad(): ?bool
    {
        return $this->moneyLoad;
    }

    /**
     * Sets Money Load.
     * Merchant to inform Visa Acceptance whether a transaction is Money load with Money load only.
     *
     * Possible values:
     * - `true` (This is a money load transaction)
     * - `false` (default value) (This is not a money load transaction)
     *
     * @maps moneyLoad
     */
    public function setMoneyLoad(?bool $moneyLoad): void
    {
        $this->moneyLoad = $moneyLoad;
    }

    /**
     * Converts the AuthorizationOptions object to a human-readable string representation.
     *
     * @return string The string representation of the AuthorizationOptions object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthorizationOptions',
            [
                'authType' => $this->authType,
                'panReturnIndicator' => $this->panReturnIndicator,
                'verbalAuthCode' => $this->verbalAuthCode,
                'verbalAuthTransactionId' => $this->verbalAuthTransactionId,
                'authIndicator' => $this->authIndicator,
                'partialAuthIndicator' => $this->partialAuthIndicator,
                'extendAuthIndicator' => $this->extendAuthIndicator,
                'balanceInquiry' => $this->balanceInquiry,
                'ignoreAvsResult' => $this->ignoreAvsResult,
                'declineAvsFlags' => $this->declineAvsFlags,
                'ignoreCvResult' => $this->ignoreCvResult,
                'initiator' => $this->initiator,
                'billPayment' => $this->billPayment,
                'billPaymentType' => $this->billPaymentType,
                'redemptionInquiry' => $this->redemptionInquiry,
                'transportationMode' => $this->transportationMode,
                'aggregatedAuthIndicator' => $this->aggregatedAuthIndicator,
                'debtRecoveryIndicator' => $this->debtRecoveryIndicator,
                'deferredAuthIndicator' => $this->deferredAuthIndicator,
                'cashAdvanceIndicator' => $this->cashAdvanceIndicator,
                'splitPaymentTransaction' => $this->splitPaymentTransaction,
                'cardVerificationIndicator' => $this->cardVerificationIndicator,
                'transactionMode' => $this->transactionMode,
                'aftIndicator' => $this->aftIndicator,
                'serviceType' => $this->serviceType,
                'balanceUpdate' => $this->balanceUpdate,
                'moneyLoad' => $this->moneyLoad,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'authType',
        'panReturnIndicator',
        'verbalAuthCode',
        'verbalAuthTransactionId',
        'authIndicator',
        'partialAuthIndicator',
        'extendAuthIndicator',
        'balanceInquiry',
        'ignoreAvsResult',
        'declineAvsFlags',
        'ignoreCvResult',
        'initiator',
        'billPayment',
        'billPaymentType',
        'redemptionInquiry',
        'transportationMode',
        'aggregatedAuthIndicator',
        'debtRecoveryIndicator',
        'deferredAuthIndicator',
        'cashAdvanceIndicator',
        'splitPaymentTransaction',
        'cardVerificationIndicator',
        'transactionMode',
        'aftIndicator',
        'serviceType',
        'balanceUpdate',
        'moneyLoad'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->authType)) {
            $json['authType']                  = $this->authType;
        }
        if (isset($this->panReturnIndicator)) {
            $json['panReturnIndicator']        = $this->panReturnIndicator;
        }
        if (isset($this->verbalAuthCode)) {
            $json['verbalAuthCode']            = $this->verbalAuthCode;
        }
        if (isset($this->verbalAuthTransactionId)) {
            $json['verbalAuthTransactionId']   = $this->verbalAuthTransactionId;
        }
        if (isset($this->authIndicator)) {
            $json['authIndicator']             = $this->authIndicator;
        }
        if (isset($this->partialAuthIndicator)) {
            $json['partialAuthIndicator']      = $this->partialAuthIndicator;
        }
        if (isset($this->extendAuthIndicator)) {
            $json['extendAuthIndicator']       = $this->extendAuthIndicator;
        }
        if (isset($this->balanceInquiry)) {
            $json['balanceInquiry']            = $this->balanceInquiry;
        }
        if (isset($this->ignoreAvsResult)) {
            $json['ignoreAvsResult']           = $this->ignoreAvsResult;
        }
        if (isset($this->declineAvsFlags)) {
            $json['declineAvsFlags']           = $this->declineAvsFlags;
        }
        if (isset($this->ignoreCvResult)) {
            $json['ignoreCvResult']            = $this->ignoreCvResult;
        }
        if (isset($this->initiator)) {
            $json['initiator']                 = $this->initiator;
        }
        if (isset($this->billPayment)) {
            $json['billPayment']               = $this->billPayment;
        }
        if (isset($this->billPaymentType)) {
            $json['billPaymentType']           = $this->billPaymentType;
        }
        if (isset($this->redemptionInquiry)) {
            $json['redemptionInquiry']         = $this->redemptionInquiry;
        }
        if (isset($this->transportationMode)) {
            $json['transportationMode']        = $this->transportationMode;
        }
        if (isset($this->aggregatedAuthIndicator)) {
            $json['aggregatedAuthIndicator']   = $this->aggregatedAuthIndicator;
        }
        if (isset($this->debtRecoveryIndicator)) {
            $json['debtRecoveryIndicator']     = $this->debtRecoveryIndicator;
        }
        if (isset($this->deferredAuthIndicator)) {
            $json['deferredAuthIndicator']     = $this->deferredAuthIndicator;
        }
        if (isset($this->cashAdvanceIndicator)) {
            $json['cashAdvanceIndicator']      = $this->cashAdvanceIndicator;
        }
        if (isset($this->splitPaymentTransaction)) {
            $json['splitPaymentTransaction']   = $this->splitPaymentTransaction;
        }
        if (isset($this->cardVerificationIndicator)) {
            $json['cardVerificationIndicator'] = $this->cardVerificationIndicator;
        }
        if (isset($this->transactionMode)) {
            $json['transactionMode']           = $this->transactionMode;
        }
        if (isset($this->aftIndicator)) {
            $json['aftIndicator']              = $this->aftIndicator;
        }
        if (isset($this->serviceType)) {
            $json['serviceType']               = $this->serviceType;
        }
        if (isset($this->balanceUpdate)) {
            $json['balanceUpdate']             = $this->balanceUpdate;
        }
        if (isset($this->moneyLoad)) {
            $json['moneyLoad']                 = $this->moneyLoad;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
