<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class AutoRental implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $noShowIndicator;

    /**
     * @var string|null
     */
    private $customerName;

    /**
     * @var string|null
     */
    private $vehicleClass;

    /**
     * @var string|null
     */
    private $distanceTravelled;

    /**
     * @var string|null
     */
    private $distanceUnit;

    /**
     * @var string|null
     */
    private $returnDateTime;

    /**
     * @var string|null
     */
    private $rentalDateTime;

    /**
     * @var string|null
     */
    private $maxFreeDistance;

    /**
     * @var bool|null
     */
    private $insuranceIndicator;

    /**
     * @var string|null
     */
    private $programCode;

    /**
     * @var ReturnAddress|null
     */
    private $returnAddress;

    /**
     * @var RentalAddress|null
     */
    private $rentalAddress;

    /**
     * @var string|null
     */
    private $agreementNumber;

    /**
     * @var string|null
     */
    private $odometerReading;

    /**
     * @var string|null
     */
    private $vehicleIdentificationNumber;

    /**
     * @var string|null
     */
    private $companyId;

    /**
     * @var string|null
     */
    private $numberOfAdditionalDrivers;

    /**
     * @var string|null
     */
    private $driverAge;

    /**
     * @var string|null
     */
    private $specialProgramCode;

    /**
     * @var string|null
     */
    private $vehicleMake;

    /**
     * @var string|null
     */
    private $vehicleModel;

    /**
     * @var string|null
     */
    private $timePeriod;

    /**
     * @var string|null
     */
    private $commodityCode;

    /**
     * @var string|null
     */
    private $customerServicePhoneNumber;

    /**
     * @var TaxDetails|null
     */
    private $taxDetails;

    /**
     * @var string|null
     */
    private $insuranceAmount;

    /**
     * @var string|null
     */
    private $oneWayDropOffAmount;

    /**
     * @var string|null
     */
    private $adjustedAmountIndicator;

    /**
     * @var string|null
     */
    private $adjustedAmount;

    /**
     * @var string|null
     */
    private $fuelCharges;

    /**
     * @var string|null
     */
    private $weeklyRentalRate;

    /**
     * @var string|null
     */
    private $dailyRentalRate;

    /**
     * @var string|null
     */
    private $ratePerMile;

    /**
     * @var string|null
     */
    private $mileageCharge;

    /**
     * @var string|null
     */
    private $extraMileageCharge;

    /**
     * @var string|null
     */
    private $lateFeeAmount;

    /**
     * @var string|null
     */
    private $towingCharge;

    /**
     * @var string|null
     */
    private $extraCharge;

    /**
     * @var string|null
     */
    private $gpsCharge;

    /**
     * @var string|null
     */
    private $phoneCharge;

    /**
     * @var string|null
     */
    private $parkingViolationCharge;

    /**
     * @var string|null
     */
    private $otherCharges;

    /**
     * @var string|null
     */
    private $companyName;

    /**
     * @var string|null
     */
    private $affiliateName;

    /**
     * Returns No Show Indicator.
     * No Show Indicator provides an indicator noting that the individual did not show up after making a
     * reservation for a vehicle.
     * Possible values:
     * - true
     * - false
     */
    public function getNoShowIndicator(): ?bool
    {
        return $this->noShowIndicator;
    }

    /**
     * Sets No Show Indicator.
     * No Show Indicator provides an indicator noting that the individual did not show up after making a
     * reservation for a vehicle.
     * Possible values:
     * - true
     * - false
     *
     * @maps noShowIndicator
     */
    public function setNoShowIndicator(?bool $noShowIndicator): void
    {
        $this->noShowIndicator = $noShowIndicator;
    }

    /**
     * Returns Customer Name.
     * Name of the individual making the rental agreement.
     *
     * Valid data lengths by card:
     *
     * |Card Specific Validation|VISA|MasterCard|Discover|AMEX|
     * |--- |--- |--- |--- |
     * | Filed Length| 40| 40| 29| 26|
     * | Field Type| AN| ANS| AN| AN|
     * | M/O/C| O| M| M| M|
     */
    public function getCustomerName(): ?string
    {
        return $this->customerName;
    }

    /**
     * Sets Customer Name.
     * Name of the individual making the rental agreement.
     *
     * Valid data lengths by card:
     *
     * |Card Specific Validation|VISA|MasterCard|Discover|AMEX|
     * |--- |--- |--- |--- |
     * | Filed Length| 40| 40| 29| 26|
     * | Field Type| AN| ANS| AN| AN|
     * | M/O/C| O| M| M| M|
     *
     * @maps customerName
     */
    public function setCustomerName(?string $customerName): void
    {
        $this->customerName = $customerName;
    }

    /**
     * Returns Vehicle Class.
     * Classification of the rented auto.
     *
     * **NOTE** For VISA, this is a 2-byte optional code.
     *
     * Valid values for American Express & MasterCard:
     *
     * |American Express |MasterCard |Description|
     * |--- |--- |--- |
     * | 0001| 0001| Mini|
     * | 0002| 0002| Subcompact|
     * | 0003| 0003| Economy|
     * | 0004| 0004| Compact|
     * | 0005| 0005| Midsize|
     * | 0006| 0006| Intermediate|
     * | 0007| 0007| Standard|
     * | 0008| 0008| Fulll size|
     * | 0009| 0009| Luxury|
     * | 0010| 0010| Premium|
     * | 0011| 0011| Minivan|
     * | 0012| 0012| 12-passenger van|
     * | 0013| 0013| Moving van|
     * | 0014| 0014| 15-passenger van|
     * | 0015| 0015| Cargo van|
     * | 0016| 0016| 12-foot truck|
     * | 0017| 0017| 20-foot truck|
     * | 0018| 0018| 24-foot truck|
     * | 0019| 0019| 26-foot truck|
     * | 0020| 0020| Moped|
     * | 0021| 0021| Stretch|
     * | 0022| 0022| Regular|
     * | 0023| 0023| Unique|
     * | 0024| 0024| Exotic|
     * | 0025| 0025| Small/medium truck|
     * | 0026| 0026| Large truck|
     * | 0027| 0027| Small SUV|
     * | 0028| 0028| Medium SUV|
     * | 0029| 0029| Large SUV|
     * | 0030| 0030| Exotic SUV|
     * | 9999| 9999| Miscellaneous|
     *
     * Additional Values allowed **only** for `American Express`:
     *
     * |American Express|MasterCard|Description|
     * |--- |--- |--- |
     * | 0031| NA| Four Wheel Drive|
     * | 0032| NA| Special|
     * | 0099| NA| Taxi|
     */
    public function getVehicleClass(): ?string
    {
        return $this->vehicleClass;
    }

    /**
     * Sets Vehicle Class.
     * Classification of the rented auto.
     *
     * **NOTE** For VISA, this is a 2-byte optional code.
     *
     * Valid values for American Express & MasterCard:
     *
     * |American Express |MasterCard |Description|
     * |--- |--- |--- |
     * | 0001| 0001| Mini|
     * | 0002| 0002| Subcompact|
     * | 0003| 0003| Economy|
     * | 0004| 0004| Compact|
     * | 0005| 0005| Midsize|
     * | 0006| 0006| Intermediate|
     * | 0007| 0007| Standard|
     * | 0008| 0008| Fulll size|
     * | 0009| 0009| Luxury|
     * | 0010| 0010| Premium|
     * | 0011| 0011| Minivan|
     * | 0012| 0012| 12-passenger van|
     * | 0013| 0013| Moving van|
     * | 0014| 0014| 15-passenger van|
     * | 0015| 0015| Cargo van|
     * | 0016| 0016| 12-foot truck|
     * | 0017| 0017| 20-foot truck|
     * | 0018| 0018| 24-foot truck|
     * | 0019| 0019| 26-foot truck|
     * | 0020| 0020| Moped|
     * | 0021| 0021| Stretch|
     * | 0022| 0022| Regular|
     * | 0023| 0023| Unique|
     * | 0024| 0024| Exotic|
     * | 0025| 0025| Small/medium truck|
     * | 0026| 0026| Large truck|
     * | 0027| 0027| Small SUV|
     * | 0028| 0028| Medium SUV|
     * | 0029| 0029| Large SUV|
     * | 0030| 0030| Exotic SUV|
     * | 9999| 9999| Miscellaneous|
     *
     * Additional Values allowed **only** for `American Express`:
     *
     * |American Express|MasterCard|Description|
     * |--- |--- |--- |
     * | 0031| NA| Four Wheel Drive|
     * | 0032| NA| Special|
     * | 0099| NA| Taxi|
     *
     * @maps vehicleClass
     */
    public function setVehicleClass(?string $vehicleClass): void
    {
        $this->vehicleClass = $vehicleClass;
    }

    /**
     * Returns Distance Travelled.
     * Total number of miles driven by the customer.
     * This field is supported only for MasterCard and American Express.
     */
    public function getDistanceTravelled(): ?string
    {
        return $this->distanceTravelled;
    }

    /**
     * Sets Distance Travelled.
     * Total number of miles driven by the customer.
     * This field is supported only for MasterCard and American Express.
     *
     * @maps distanceTravelled
     */
    public function setDistanceTravelled(?string $distanceTravelled): void
    {
        $this->distanceTravelled = $distanceTravelled;
    }

    /**
     * Returns Distance Unit.
     * Miles/Kilometers Indicator shows whether the “miles” fields are expressed in miles or kilometers.
     *
     * Allowed values:
     * - `K` - Kilometers
     * - `M` - Miles
     */
    public function getDistanceUnit(): ?string
    {
        return $this->distanceUnit;
    }

    /**
     * Sets Distance Unit.
     * Miles/Kilometers Indicator shows whether the “miles” fields are expressed in miles or kilometers.
     *
     * Allowed values:
     * - `K` - Kilometers
     * - `M` - Miles
     *
     * @maps distanceUnit
     */
    public function setDistanceUnit(?string $distanceUnit): void
    {
        $this->distanceUnit = $distanceUnit;
    }

    /**
     * Returns Return Date Time.
     * Date/time the auto was returned to the rental agency.
     * Format: ``yyyy-MM-dd HH-mm-ss z``
     * This field is supported for Visa, MasterCard, and American Express.
     */
    public function getReturnDateTime(): ?string
    {
        return $this->returnDateTime;
    }

    /**
     * Sets Return Date Time.
     * Date/time the auto was returned to the rental agency.
     * Format: ``yyyy-MM-dd HH-mm-ss z``
     * This field is supported for Visa, MasterCard, and American Express.
     *
     * @maps returnDateTime
     */
    public function setReturnDateTime(?string $returnDateTime): void
    {
        $this->returnDateTime = $returnDateTime;
    }

    /**
     * Returns Rental Date Time.
     * Date/time the auto was picked up from the rental agency.
     * Format: `yyyy-MM-dd HH-mm-ss z`
     * This field is supported for Visa, MasterCard, and American Express.
     */
    public function getRentalDateTime(): ?string
    {
        return $this->rentalDateTime;
    }

    /**
     * Sets Rental Date Time.
     * Date/time the auto was picked up from the rental agency.
     * Format: `yyyy-MM-dd HH-mm-ss z`
     * This field is supported for Visa, MasterCard, and American Express.
     *
     * @maps rentalDateTime
     */
    public function setRentalDateTime(?string $rentalDateTime): void
    {
        $this->rentalDateTime = $rentalDateTime;
    }

    /**
     * Returns Max Free Distance.
     * Maximum number of free miles or kilometers allowed to a customer for the duration of the auto rental
     * agreement.
     * This field is supported only for MasterCard and American Express.
     */
    public function getMaxFreeDistance(): ?string
    {
        return $this->maxFreeDistance;
    }

    /**
     * Sets Max Free Distance.
     * Maximum number of free miles or kilometers allowed to a customer for the duration of the auto rental
     * agreement.
     * This field is supported only for MasterCard and American Express.
     *
     * @maps maxFreeDistance
     */
    public function setMaxFreeDistance(?string $maxFreeDistance): void
    {
        $this->maxFreeDistance = $maxFreeDistance;
    }

    /**
     * Returns Insurance Indicator.
     * Used for MC and Discover
     *
     * Valid values:
     * - `true` - Yes (insurance was purchased)
     * - `false` - No (insurance was not purchased)
     */
    public function getInsuranceIndicator(): ?bool
    {
        return $this->insuranceIndicator;
    }

    /**
     * Sets Insurance Indicator.
     * Used for MC and Discover
     *
     * Valid values:
     * - `true` - Yes (insurance was purchased)
     * - `false` - No (insurance was not purchased)
     *
     * @maps insuranceIndicator
     */
    public function setInsuranceIndicator(?bool $insuranceIndicator): void
    {
        $this->insuranceIndicator = $insuranceIndicator;
    }

    /**
     * Returns Program Code.
     * Used to identify special circumstances applicable to the Card Transaction or Cardholder, such as
     * "renter” or ”show”.
     *
     * This code is `2 digit` value agreed by Merchant and processor.
     */
    public function getProgramCode(): ?string
    {
        return $this->programCode;
    }

    /**
     * Sets Program Code.
     * Used to identify special circumstances applicable to the Card Transaction or Cardholder, such as
     * "renter” or ”show”.
     *
     * This code is `2 digit` value agreed by Merchant and processor.
     *
     * @maps programCode
     */
    public function setProgramCode(?string $programCode): void
    {
        $this->programCode = $programCode;
    }

    /**
     * Returns Return Address.
     */
    public function getReturnAddress(): ?ReturnAddress
    {
        return $this->returnAddress;
    }

    /**
     * Sets Return Address.
     *
     * @maps returnAddress
     */
    public function setReturnAddress(?ReturnAddress $returnAddress): void
    {
        $this->returnAddress = $returnAddress;
    }

    /**
     * Returns Rental Address.
     */
    public function getRentalAddress(): ?RentalAddress
    {
        return $this->rentalAddress;
    }

    /**
     * Sets Rental Address.
     *
     * @maps rentalAddress
     */
    public function setRentalAddress(?RentalAddress $rentalAddress): void
    {
        $this->rentalAddress = $rentalAddress;
    }

    /**
     * Returns Agreement Number.
     * Auto rental agency’s agreement (invoice) number provided to the customer. It is used to trace any
     * inquiries about transactions.
     * This field is supported for Visa, MasterCard, and American Express.
     * This Merchant-defined value, which may be composed of any combination of characters and/or numerals,
     * may become
     * part of the descriptive bill on the Cardmember's statement.
     */
    public function getAgreementNumber(): ?string
    {
        return $this->agreementNumber;
    }

    /**
     * Sets Agreement Number.
     * Auto rental agency’s agreement (invoice) number provided to the customer. It is used to trace any
     * inquiries about transactions.
     * This field is supported for Visa, MasterCard, and American Express.
     * This Merchant-defined value, which may be composed of any combination of characters and/or numerals,
     * may become
     * part of the descriptive bill on the Cardmember's statement.
     *
     * @maps agreementNumber
     */
    public function setAgreementNumber(?string $agreementNumber): void
    {
        $this->agreementNumber = $agreementNumber;
    }

    /**
     * Returns Odometer Reading.
     * Odometer reading at time of vehicle rental.
     */
    public function getOdometerReading(): ?string
    {
        return $this->odometerReading;
    }

    /**
     * Sets Odometer Reading.
     * Odometer reading at time of vehicle rental.
     *
     * @maps odometerReading
     */
    public function setOdometerReading(?string $odometerReading): void
    {
        $this->odometerReading = $odometerReading;
    }

    /**
     * Returns Vehicle Identification Number.
     * This field contains a unique identifier assigned by the company to the vehicle.
     */
    public function getVehicleIdentificationNumber(): ?string
    {
        return $this->vehicleIdentificationNumber;
    }

    /**
     * Sets Vehicle Identification Number.
     * This field contains a unique identifier assigned by the company to the vehicle.
     *
     * @maps vehicleIdentificationNumber
     */
    public function setVehicleIdentificationNumber(?string $vehicleIdentificationNumber): void
    {
        $this->vehicleIdentificationNumber = $vehicleIdentificationNumber;
    }

    /**
     * Returns Company Id.
     * Corporate Identifier provides the unique identifier of the corporation or entity renting the vehicle:
     *
     * |Card Specific Validation|VISA|MasterCard|Discover|AMEX|
     * |--- |--- |--- |--- |
     * | Filed Length| NA| 12| NA| NA|
     * | Field Type| NA| AN| NA| NA|
     * | M/O/C| NA| O| NA| NA|
     */
    public function getCompanyId(): ?string
    {
        return $this->companyId;
    }

    /**
     * Sets Company Id.
     * Corporate Identifier provides the unique identifier of the corporation or entity renting the vehicle:
     *
     * |Card Specific Validation|VISA|MasterCard|Discover|AMEX|
     * |--- |--- |--- |--- |
     * | Filed Length| NA| 12| NA| NA|
     * | Field Type| NA| AN| NA| NA|
     * | M/O/C| NA| O| NA| NA|
     *
     * @maps companyId
     */
    public function setCompanyId(?string $companyId): void
    {
        $this->companyId = $companyId;
    }

    /**
     * Returns Number of Additional Drivers.
     * The number of additional drivers included on the rental agreement not including the individual who
     * signed the rental agreement.
     */
    public function getNumberOfAdditionalDrivers(): ?string
    {
        return $this->numberOfAdditionalDrivers;
    }

    /**
     * Sets Number of Additional Drivers.
     * The number of additional drivers included on the rental agreement not including the individual who
     * signed the rental agreement.
     *
     * @maps numberOfAdditionalDrivers
     */
    public function setNumberOfAdditionalDrivers(?string $numberOfAdditionalDrivers): void
    {
        $this->numberOfAdditionalDrivers = $numberOfAdditionalDrivers;
    }

    /**
     * Returns Driver Age.
     * Age of the driver renting the vehicle.
     */
    public function getDriverAge(): ?string
    {
        return $this->driverAge;
    }

    /**
     * Sets Driver Age.
     * Age of the driver renting the vehicle.
     *
     * @maps driverAge
     */
    public function setDriverAge(?string $driverAge): void
    {
        $this->driverAge = $driverAge;
    }

    /**
     * Returns Special Program Code.
     * Program code used to identify special circumstances, such as “frequent renter” or “no show” status
     * for the renter.
     * Possible values:
     * - `0`: not applicable (default)
     * - `1`: frequent renter
     * - `2`: no show
     *
     * For authorizations, this field is supported only for Visa.
     *
     * For captures, this field is supported for Visa, MasterCard, and American Express.
     *
     * Code for special programs applicable to the Card Transaction or the Cardholder.
     */
    public function getSpecialProgramCode(): ?string
    {
        return $this->specialProgramCode;
    }

    /**
     * Sets Special Program Code.
     * Program code used to identify special circumstances, such as “frequent renter” or “no show” status
     * for the renter.
     * Possible values:
     * - `0`: not applicable (default)
     * - `1`: frequent renter
     * - `2`: no show
     *
     * For authorizations, this field is supported only for Visa.
     *
     * For captures, this field is supported for Visa, MasterCard, and American Express.
     *
     * Code for special programs applicable to the Card Transaction or the Cardholder.
     *
     * @maps specialProgramCode
     */
    public function setSpecialProgramCode(?string $specialProgramCode): void
    {
        $this->specialProgramCode = $specialProgramCode;
    }

    /**
     * Returns Vehicle Make.
     * Make of the vehicle being rented (e.g., Chevrolet or Ford).
     */
    public function getVehicleMake(): ?string
    {
        return $this->vehicleMake;
    }

    /**
     * Sets Vehicle Make.
     * Make of the vehicle being rented (e.g., Chevrolet or Ford).
     *
     * @maps vehicleMake
     */
    public function setVehicleMake(?string $vehicleMake): void
    {
        $this->vehicleMake = $vehicleMake;
    }

    /**
     * Returns Vehicle Model.
     * Model of the vehicle being rented (e.g., Cavalier or Focus).
     */
    public function getVehicleModel(): ?string
    {
        return $this->vehicleModel;
    }

    /**
     * Sets Vehicle Model.
     * Model of the vehicle being rented (e.g., Cavalier or Focus).
     *
     * @maps vehicleModel
     */
    public function setVehicleModel(?string $vehicleModel): void
    {
        $this->vehicleModel = $vehicleModel;
    }

    /**
     * Returns Time Period.
     * Indicates the time period for which the vehicle rental rate applies (e.g., daily, weekly or monthly).
     * Daily, Weekly and Monthly are valid values.
     */
    public function getTimePeriod(): ?string
    {
        return $this->timePeriod;
    }

    /**
     * Sets Time Period.
     * Indicates the time period for which the vehicle rental rate applies (e.g., daily, weekly or monthly).
     * Daily, Weekly and Monthly are valid values.
     *
     * @maps timePeriod
     */
    public function setTimePeriod(?string $timePeriod): void
    {
        $this->timePeriod = $timePeriod;
    }

    /**
     * Returns Commodity Code.
     * Commodity code or International description code used to classify the item. Contact your acquirer
     * for a list of
     * codes.
     */
    public function getCommodityCode(): ?string
    {
        return $this->commodityCode;
    }

    /**
     * Sets Commodity Code.
     * Commodity code or International description code used to classify the item. Contact your acquirer
     * for a list of
     * codes.
     *
     * @maps commodityCode
     */
    public function setCommodityCode(?string $commodityCode): void
    {
        $this->commodityCode = $commodityCode;
    }

    /**
     * Returns Customer Service Phone Number.
     * Customer service telephone number that is used to resolve questions or disputes. Include the area
     * code, exchange, and number.
     * This field is supported only for MasterCard and American Express.
     */
    public function getCustomerServicePhoneNumber(): ?string
    {
        return $this->customerServicePhoneNumber;
    }

    /**
     * Sets Customer Service Phone Number.
     * Customer service telephone number that is used to resolve questions or disputes. Include the area
     * code, exchange, and number.
     * This field is supported only for MasterCard and American Express.
     *
     * @maps customerServicePhoneNumber
     */
    public function setCustomerServicePhoneNumber(?string $customerServicePhoneNumber): void
    {
        $this->customerServicePhoneNumber = $customerServicePhoneNumber;
    }

    /**
     * Returns Tax Details.
     */
    public function getTaxDetails(): ?TaxDetails
    {
        return $this->taxDetails;
    }

    /**
     * Sets Tax Details.
     *
     * @maps taxDetails
     */
    public function setTaxDetails(?TaxDetails $taxDetails): void
    {
        $this->taxDetails = $taxDetails;
    }

    /**
     * Returns Insurance Amount.
     * Insurance charges.
     * Field is conditional and can include decimal point.
     */
    public function getInsuranceAmount(): ?string
    {
        return $this->insuranceAmount;
    }

    /**
     * Sets Insurance Amount.
     * Insurance charges.
     * Field is conditional and can include decimal point.
     *
     * @maps insuranceAmount
     */
    public function setInsuranceAmount(?string $insuranceAmount): void
    {
        $this->insuranceAmount = $insuranceAmount;
    }

    /**
     * Returns One Way Drop Off Amount.
     * Extra charges incurred for a one-way rental agreement for the auto.
     * This field is supported only for Visa.
     */
    public function getOneWayDropOffAmount(): ?string
    {
        return $this->oneWayDropOffAmount;
    }

    /**
     * Sets One Way Drop Off Amount.
     * Extra charges incurred for a one-way rental agreement for the auto.
     * This field is supported only for Visa.
     *
     * @maps oneWayDropOffAmount
     */
    public function setOneWayDropOffAmount(?string $oneWayDropOffAmount): void
    {
        $this->oneWayDropOffAmount = $oneWayDropOffAmount;
    }

    /**
     * Returns Adjusted Amount Indicator.
     * For **MasterCard** and **Discover**:
     * Adjusted amount indicator code that indicates
     * any miscellaneous charges incurred after the
     * auto was returned. Possible values:
     * - `A` - Drop-off charges
     * - `B` - Delivery charges
     * - `C` - Parking expenses
     * - `D` - Extra hours
     * - `E` - Violations
     * - `X` - More than one of the above charges
     *
     * For **American Express**:
     * Audit indicator code that indicates any
     * adjustment for mileage, fuel, auto damage,
     * etc. made to a rental agreement and whether
     * the cardholder was notified.
     *
     * Possible value for the authorization service:
     * - `A` (default): adjustment amount greater than 0 (zero)
     *
     * Possible values for the capture service:
     * - `X` - Multiple adjustments
     * - `Y` - One adjustment only; Cardmember notified
     * - `Z` - One adjustment only; Cardmember not notified. This value is used as the default if the
     * request does not include this field and includes an adjustment amount greater than 0 (zero).
     * This is an optional field.
     */
    public function getAdjustedAmountIndicator(): ?string
    {
        return $this->adjustedAmountIndicator;
    }

    /**
     * Sets Adjusted Amount Indicator.
     * For **MasterCard** and **Discover**:
     * Adjusted amount indicator code that indicates
     * any miscellaneous charges incurred after the
     * auto was returned. Possible values:
     * - `A` - Drop-off charges
     * - `B` - Delivery charges
     * - `C` - Parking expenses
     * - `D` - Extra hours
     * - `E` - Violations
     * - `X` - More than one of the above charges
     *
     * For **American Express**:
     * Audit indicator code that indicates any
     * adjustment for mileage, fuel, auto damage,
     * etc. made to a rental agreement and whether
     * the cardholder was notified.
     *
     * Possible value for the authorization service:
     * - `A` (default): adjustment amount greater than 0 (zero)
     *
     * Possible values for the capture service:
     * - `X` - Multiple adjustments
     * - `Y` - One adjustment only; Cardmember notified
     * - `Z` - One adjustment only; Cardmember not notified. This value is used as the default if the
     * request does not include this field and includes an adjustment amount greater than 0 (zero).
     * This is an optional field.
     *
     * @maps adjustedAmountIndicator
     */
    public function setAdjustedAmountIndicator(?string $adjustedAmountIndicator): void
    {
        $this->adjustedAmountIndicator = $adjustedAmountIndicator;
    }

    /**
     * Returns Adjusted Amount.
     * Adjusted Amount indicates whether any miscellaneous charges were incurred after the vehicle was
     * returned.
     *
     * For authorizations, this field is supported only for American Express.
     *
     * For captures, this field is supported only for MasterCard and American Express.
     * **NOTE** For American Express, this field is required if the `travelInformation.autoRental.
     * adjustedAmountIndicator` field
     * is included in the request and has a value; otherwise, this field is optional.
     *
     * For all other card types, this field is ignored.
     */
    public function getAdjustedAmount(): ?string
    {
        return $this->adjustedAmount;
    }

    /**
     * Sets Adjusted Amount.
     * Adjusted Amount indicates whether any miscellaneous charges were incurred after the vehicle was
     * returned.
     *
     * For authorizations, this field is supported only for American Express.
     *
     * For captures, this field is supported only for MasterCard and American Express.
     * **NOTE** For American Express, this field is required if the `travelInformation.autoRental.
     * adjustedAmountIndicator` field
     * is included in the request and has a value; otherwise, this field is optional.
     *
     * For all other card types, this field is ignored.
     *
     * @maps adjustedAmount
     */
    public function setAdjustedAmount(?string $adjustedAmount): void
    {
        $this->adjustedAmount = $adjustedAmount;
    }

    /**
     * Returns Fuel Charges.
     * Extra gasoline charges that extend beyond the basic rental agreement.
     * This field is supported only for Visa.
     */
    public function getFuelCharges(): ?string
    {
        return $this->fuelCharges;
    }

    /**
     * Sets Fuel Charges.
     * Extra gasoline charges that extend beyond the basic rental agreement.
     * This field is supported only for Visa.
     *
     * @maps fuelCharges
     */
    public function setFuelCharges(?string $fuelCharges): void
    {
        $this->fuelCharges = $fuelCharges;
    }

    /**
     * Returns Weekly Rental Rate.
     * Weekly Rental Amount provides the amount charged for a seven-day rental period. Field - Time Period
     * needs to be populated with Weekly if this field is present
     */
    public function getWeeklyRentalRate(): ?string
    {
        return $this->weeklyRentalRate;
    }

    /**
     * Sets Weekly Rental Rate.
     * Weekly Rental Amount provides the amount charged for a seven-day rental period. Field - Time Period
     * needs to be populated with Weekly if this field is present
     *
     * @maps weeklyRentalRate
     */
    public function setWeeklyRentalRate(?string $weeklyRentalRate): void
    {
        $this->weeklyRentalRate = $weeklyRentalRate;
    }

    /**
     * Returns Daily Rental Rate.
     * Daily auto rental rate charged.
     * This field is supported only for MasterCard and American Express.
     *
     * Field - Time Period needs to be populated with Daily if this field is present
     */
    public function getDailyRentalRate(): ?string
    {
        return $this->dailyRentalRate;
    }

    /**
     * Sets Daily Rental Rate.
     * Daily auto rental rate charged.
     * This field is supported only for MasterCard and American Express.
     *
     * Field - Time Period needs to be populated with Daily if this field is present
     *
     * @maps dailyRentalRate
     */
    public function setDailyRentalRate(?string $dailyRentalRate): void
    {
        $this->dailyRentalRate = $dailyRentalRate;
    }

    /**
     * Returns Rate Per Mile.
     * Rate charged for each mile.
     * This field is supported only for MasterCard and American Express.
     */
    public function getRatePerMile(): ?string
    {
        return $this->ratePerMile;
    }

    /**
     * Sets Rate Per Mile.
     * Rate charged for each mile.
     * This field is supported only for MasterCard and American Express.
     *
     * @maps ratePerMile
     */
    public function setRatePerMile(?string $ratePerMile): void
    {
        $this->ratePerMile = $ratePerMile;
    }

    /**
     * Returns Mileage Charge.
     * Regular Mileage Charge provides the amount charged for regular miles traveled during vehicle rental.
     * Two decimal places
     */
    public function getMileageCharge(): ?string
    {
        return $this->mileageCharge;
    }

    /**
     * Sets Mileage Charge.
     * Regular Mileage Charge provides the amount charged for regular miles traveled during vehicle rental.
     * Two decimal places
     *
     * @maps mileageCharge
     */
    public function setMileageCharge(?string $mileageCharge): void
    {
        $this->mileageCharge = $mileageCharge;
    }

    /**
     * Returns Extra Mileage Charge.
     * Extra mileage charges that extend beyond the basic rental agreement.
     * This field is supported only for Visa.
     */
    public function getExtraMileageCharge(): ?string
    {
        return $this->extraMileageCharge;
    }

    /**
     * Sets Extra Mileage Charge.
     * Extra mileage charges that extend beyond the basic rental agreement.
     * This field is supported only for Visa.
     *
     * @maps extraMileageCharge
     */
    public function setExtraMileageCharge(?string $extraMileageCharge): void
    {
        $this->extraMileageCharge = $extraMileageCharge;
    }

    /**
     * Returns Late Fee Amount.
     * Extra charges related to a late return of the rented auto.
     * This field is supported only for Visa.
     */
    public function getLateFeeAmount(): ?string
    {
        return $this->lateFeeAmount;
    }

    /**
     * Sets Late Fee Amount.
     * Extra charges related to a late return of the rented auto.
     * This field is supported only for Visa.
     *
     * @maps lateFeeAmount
     */
    public function setLateFeeAmount(?string $lateFeeAmount): void
    {
        $this->lateFeeAmount = $lateFeeAmount;
    }

    /**
     * Returns Towing Charge.
     * (Towing Charges) provides the amount charged to tow the rental vehicle.
     */
    public function getTowingCharge(): ?string
    {
        return $this->towingCharge;
    }

    /**
     * Sets Towing Charge.
     * (Towing Charges) provides the amount charged to tow the rental vehicle.
     *
     * @maps towingCharge
     */
    public function setTowingCharge(?string $towingCharge): void
    {
        $this->towingCharge = $towingCharge;
    }

    /**
     * Returns Extra Charge.
     * (Extra Charges) provides the extra charges associated with the vehicle rental.
     */
    public function getExtraCharge(): ?string
    {
        return $this->extraCharge;
    }

    /**
     * Sets Extra Charge.
     * (Extra Charges) provides the extra charges associated with the vehicle rental.
     *
     * @maps extraCharge
     */
    public function setExtraCharge(?string $extraCharge): void
    {
        $this->extraCharge = $extraCharge;
    }

    /**
     * Returns Gps Charge.
     * Amount charged for renting a Global Positioning Service (GPS).
     */
    public function getGpsCharge(): ?string
    {
        return $this->gpsCharge;
    }

    /**
     * Sets Gps Charge.
     * Amount charged for renting a Global Positioning Service (GPS).
     *
     * @maps gpsCharge
     */
    public function setGpsCharge(?string $gpsCharge): void
    {
        $this->gpsCharge = $gpsCharge;
    }

    /**
     * Returns Phone Charge.
     * Additional charges incurred for phone usage included on the total bill.
     */
    public function getPhoneCharge(): ?string
    {
        return $this->phoneCharge;
    }

    /**
     * Sets Phone Charge.
     * Additional charges incurred for phone usage included on the total bill.
     *
     * @maps phoneCharge
     */
    public function setPhoneCharge(?string $phoneCharge): void
    {
        $this->phoneCharge = $phoneCharge;
    }

    /**
     * Returns Parking Violation Charge.
     * Extra charges incurred due to a parking violation for the auto.
     * This field is supported only for Visa.
     */
    public function getParkingViolationCharge(): ?string
    {
        return $this->parkingViolationCharge;
    }

    /**
     * Sets Parking Violation Charge.
     * Extra charges incurred due to a parking violation for the auto.
     * This field is supported only for Visa.
     *
     * @maps parkingViolationCharge
     */
    public function setParkingViolationCharge(?string $parkingViolationCharge): void
    {
        $this->parkingViolationCharge = $parkingViolationCharge;
    }

    /**
     * Returns Other Charges.
     * Total amount charged for all other miscellaneous charges not previously defined.
     */
    public function getOtherCharges(): ?string
    {
        return $this->otherCharges;
    }

    /**
     * Sets Other Charges.
     * Total amount charged for all other miscellaneous charges not previously defined.
     *
     * @maps otherCharges
     */
    public function setOtherCharges(?string $otherCharges): void
    {
        $this->otherCharges = $otherCharges;
    }

    /**
     * Returns Company Name.
     * Merchant to send their auto rental company name
     */
    public function getCompanyName(): ?string
    {
        return $this->companyName;
    }

    /**
     * Sets Company Name.
     * Merchant to send their auto rental company name
     *
     * @maps companyName
     */
    public function setCompanyName(?string $companyName): void
    {
        $this->companyName = $companyName;
    }

    /**
     * Returns Affiliate Name.
     * When merchant wants to send the affiliate name.
     */
    public function getAffiliateName(): ?string
    {
        return $this->affiliateName;
    }

    /**
     * Sets Affiliate Name.
     * When merchant wants to send the affiliate name.
     *
     * @maps affiliateName
     */
    public function setAffiliateName(?string $affiliateName): void
    {
        $this->affiliateName = $affiliateName;
    }

    /**
     * Converts the AutoRental object to a human-readable string representation.
     *
     * @return string The string representation of the AutoRental object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AutoRental',
            [
                'noShowIndicator' => $this->noShowIndicator,
                'customerName' => $this->customerName,
                'vehicleClass' => $this->vehicleClass,
                'distanceTravelled' => $this->distanceTravelled,
                'distanceUnit' => $this->distanceUnit,
                'returnDateTime' => $this->returnDateTime,
                'rentalDateTime' => $this->rentalDateTime,
                'maxFreeDistance' => $this->maxFreeDistance,
                'insuranceIndicator' => $this->insuranceIndicator,
                'programCode' => $this->programCode,
                'returnAddress' => $this->returnAddress,
                'rentalAddress' => $this->rentalAddress,
                'agreementNumber' => $this->agreementNumber,
                'odometerReading' => $this->odometerReading,
                'vehicleIdentificationNumber' => $this->vehicleIdentificationNumber,
                'companyId' => $this->companyId,
                'numberOfAdditionalDrivers' => $this->numberOfAdditionalDrivers,
                'driverAge' => $this->driverAge,
                'specialProgramCode' => $this->specialProgramCode,
                'vehicleMake' => $this->vehicleMake,
                'vehicleModel' => $this->vehicleModel,
                'timePeriod' => $this->timePeriod,
                'commodityCode' => $this->commodityCode,
                'customerServicePhoneNumber' => $this->customerServicePhoneNumber,
                'taxDetails' => $this->taxDetails,
                'insuranceAmount' => $this->insuranceAmount,
                'oneWayDropOffAmount' => $this->oneWayDropOffAmount,
                'adjustedAmountIndicator' => $this->adjustedAmountIndicator,
                'adjustedAmount' => $this->adjustedAmount,
                'fuelCharges' => $this->fuelCharges,
                'weeklyRentalRate' => $this->weeklyRentalRate,
                'dailyRentalRate' => $this->dailyRentalRate,
                'ratePerMile' => $this->ratePerMile,
                'mileageCharge' => $this->mileageCharge,
                'extraMileageCharge' => $this->extraMileageCharge,
                'lateFeeAmount' => $this->lateFeeAmount,
                'towingCharge' => $this->towingCharge,
                'extraCharge' => $this->extraCharge,
                'gpsCharge' => $this->gpsCharge,
                'phoneCharge' => $this->phoneCharge,
                'parkingViolationCharge' => $this->parkingViolationCharge,
                'otherCharges' => $this->otherCharges,
                'companyName' => $this->companyName,
                'affiliateName' => $this->affiliateName,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'noShowIndicator',
        'customerName',
        'vehicleClass',
        'distanceTravelled',
        'distanceUnit',
        'returnDateTime',
        'rentalDateTime',
        'maxFreeDistance',
        'insuranceIndicator',
        'programCode',
        'returnAddress',
        'rentalAddress',
        'agreementNumber',
        'odometerReading',
        'vehicleIdentificationNumber',
        'companyId',
        'numberOfAdditionalDrivers',
        'driverAge',
        'specialProgramCode',
        'vehicleMake',
        'vehicleModel',
        'timePeriod',
        'commodityCode',
        'customerServicePhoneNumber',
        'taxDetails',
        'insuranceAmount',
        'oneWayDropOffAmount',
        'adjustedAmountIndicator',
        'adjustedAmount',
        'fuelCharges',
        'weeklyRentalRate',
        'dailyRentalRate',
        'ratePerMile',
        'mileageCharge',
        'extraMileageCharge',
        'lateFeeAmount',
        'towingCharge',
        'extraCharge',
        'gpsCharge',
        'phoneCharge',
        'parkingViolationCharge',
        'otherCharges',
        'companyName',
        'affiliateName'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->noShowIndicator)) {
            $json['noShowIndicator']             = $this->noShowIndicator;
        }
        if (isset($this->customerName)) {
            $json['customerName']                = $this->customerName;
        }
        if (isset($this->vehicleClass)) {
            $json['vehicleClass']                = $this->vehicleClass;
        }
        if (isset($this->distanceTravelled)) {
            $json['distanceTravelled']           = $this->distanceTravelled;
        }
        if (isset($this->distanceUnit)) {
            $json['distanceUnit']                = $this->distanceUnit;
        }
        if (isset($this->returnDateTime)) {
            $json['returnDateTime']              = $this->returnDateTime;
        }
        if (isset($this->rentalDateTime)) {
            $json['rentalDateTime']              = $this->rentalDateTime;
        }
        if (isset($this->maxFreeDistance)) {
            $json['maxFreeDistance']             = $this->maxFreeDistance;
        }
        if (isset($this->insuranceIndicator)) {
            $json['insuranceIndicator']          = $this->insuranceIndicator;
        }
        if (isset($this->programCode)) {
            $json['programCode']                 = $this->programCode;
        }
        if (isset($this->returnAddress)) {
            $json['returnAddress']               = $this->returnAddress;
        }
        if (isset($this->rentalAddress)) {
            $json['rentalAddress']               = $this->rentalAddress;
        }
        if (isset($this->agreementNumber)) {
            $json['agreementNumber']             = $this->agreementNumber;
        }
        if (isset($this->odometerReading)) {
            $json['odometerReading']             = $this->odometerReading;
        }
        if (isset($this->vehicleIdentificationNumber)) {
            $json['vehicleIdentificationNumber'] = $this->vehicleIdentificationNumber;
        }
        if (isset($this->companyId)) {
            $json['companyId']                   = $this->companyId;
        }
        if (isset($this->numberOfAdditionalDrivers)) {
            $json['numberOfAdditionalDrivers']   = $this->numberOfAdditionalDrivers;
        }
        if (isset($this->driverAge)) {
            $json['driverAge']                   = $this->driverAge;
        }
        if (isset($this->specialProgramCode)) {
            $json['specialProgramCode']          = $this->specialProgramCode;
        }
        if (isset($this->vehicleMake)) {
            $json['vehicleMake']                 = $this->vehicleMake;
        }
        if (isset($this->vehicleModel)) {
            $json['vehicleModel']                = $this->vehicleModel;
        }
        if (isset($this->timePeriod)) {
            $json['timePeriod']                  = $this->timePeriod;
        }
        if (isset($this->commodityCode)) {
            $json['commodityCode']               = $this->commodityCode;
        }
        if (isset($this->customerServicePhoneNumber)) {
            $json['customerServicePhoneNumber']  = $this->customerServicePhoneNumber;
        }
        if (isset($this->taxDetails)) {
            $json['taxDetails']                  = $this->taxDetails;
        }
        if (isset($this->insuranceAmount)) {
            $json['insuranceAmount']             = $this->insuranceAmount;
        }
        if (isset($this->oneWayDropOffAmount)) {
            $json['oneWayDropOffAmount']         = $this->oneWayDropOffAmount;
        }
        if (isset($this->adjustedAmountIndicator)) {
            $json['adjustedAmountIndicator']     = $this->adjustedAmountIndicator;
        }
        if (isset($this->adjustedAmount)) {
            $json['adjustedAmount']              = $this->adjustedAmount;
        }
        if (isset($this->fuelCharges)) {
            $json['fuelCharges']                 = $this->fuelCharges;
        }
        if (isset($this->weeklyRentalRate)) {
            $json['weeklyRentalRate']            = $this->weeklyRentalRate;
        }
        if (isset($this->dailyRentalRate)) {
            $json['dailyRentalRate']             = $this->dailyRentalRate;
        }
        if (isset($this->ratePerMile)) {
            $json['ratePerMile']                 = $this->ratePerMile;
        }
        if (isset($this->mileageCharge)) {
            $json['mileageCharge']               = $this->mileageCharge;
        }
        if (isset($this->extraMileageCharge)) {
            $json['extraMileageCharge']          = $this->extraMileageCharge;
        }
        if (isset($this->lateFeeAmount)) {
            $json['lateFeeAmount']               = $this->lateFeeAmount;
        }
        if (isset($this->towingCharge)) {
            $json['towingCharge']                = $this->towingCharge;
        }
        if (isset($this->extraCharge)) {
            $json['extraCharge']                 = $this->extraCharge;
        }
        if (isset($this->gpsCharge)) {
            $json['gpsCharge']                   = $this->gpsCharge;
        }
        if (isset($this->phoneCharge)) {
            $json['phoneCharge']                 = $this->phoneCharge;
        }
        if (isset($this->parkingViolationCharge)) {
            $json['parkingViolationCharge']      = $this->parkingViolationCharge;
        }
        if (isset($this->otherCharges)) {
            $json['otherCharges']                = $this->otherCharges;
        }
        if (isset($this->companyName)) {
            $json['companyName']                 = $this->companyName;
        }
        if (isset($this->affiliateName)) {
            $json['affiliateName']               = $this->affiliateName;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
