<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

/**
 * Contains auxiliary key-value pairs.
 */
class AuxiliaryDatum implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $key;

    /**
     * @var string|null
     */
    private $value;

    /**
     * Returns Key.
     * Fields that you can use to send additional data to Risk services.
     * **Warning** Auxiliary fields are not intended to and MUST NOT
     * be used to capture personally identifying information.
     * Accordingly, merchants are prohibited from capturing,
     * obtaining, and/or transmitting any personally identifying
     * information in or via the auxiliary data fields. Personally
     * identifying information includes, but is not limited to,
     * address, credit card number, social security number,
     * driver's license number, state-issued identification
     * number, passport number, and card verification numbers
     * (CVV, CVC2, CVV2, CID, CVN). In the event Visa Acceptance
     * discovers that a merchant is capturing and/or transmitting
     * personally identifying information via the auxiliary data
     * fields, whether or not intentionally, Visa Acceptance WILL
     * immediately suspend the merchant's account, which will
     * result in a rejection of any and all transaction requests
     * submitted by the merchant after the point of suspension.
     */
    public function getKey(): ?string
    {
        return $this->key;
    }

    /**
     * Sets Key.
     * Fields that you can use to send additional data to Risk services.
     * **Warning** Auxiliary fields are not intended to and MUST NOT
     * be used to capture personally identifying information.
     * Accordingly, merchants are prohibited from capturing,
     * obtaining, and/or transmitting any personally identifying
     * information in or via the auxiliary data fields. Personally
     * identifying information includes, but is not limited to,
     * address, credit card number, social security number,
     * driver's license number, state-issued identification
     * number, passport number, and card verification numbers
     * (CVV, CVC2, CVV2, CID, CVN). In the event Visa Acceptance
     * discovers that a merchant is capturing and/or transmitting
     * personally identifying information via the auxiliary data
     * fields, whether or not intentionally, Visa Acceptance WILL
     * immediately suspend the merchant's account, which will
     * result in a rejection of any and all transaction requests
     * submitted by the merchant after the point of suspension.
     *
     * @maps key
     */
    public function setKey(?string $key): void
    {
        $this->key = $key;
    }

    /**
     * Returns Value.
     * String value for the key
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * String value for the key
     *
     * @maps value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Converts the AuxiliaryDatum object to a human-readable string representation.
     *
     * @return string The string representation of the AuxiliaryDatum object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuxiliaryDatum',
            ['key' => $this->key, 'value' => $this->value, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['key', 'value'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->key)) {
            $json['key']   = $this->key;
        }
        if (isset($this->value)) {
            $json['value'] = $this->value;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
