<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class Bank1 implements \JsonSerializable
{
    /**
     * @var Account2|null
     */
    private $account;

    /**
     * @var string|null
     */
    private $correctedRoutingNumber;

    /**
     * Returns Account.
     */
    public function getAccount(): ?Account2
    {
        return $this->account;
    }

    /**
     * Sets Account.
     *
     * @maps account
     */
    public function setAccount(?Account2 $account): void
    {
        $this->account = $account;
    }

    /**
     * Returns Corrected Routing Number.
     * Corrected account number from the ACH verification service.
     */
    public function getCorrectedRoutingNumber(): ?string
    {
        return $this->correctedRoutingNumber;
    }

    /**
     * Sets Corrected Routing Number.
     * Corrected account number from the ACH verification service.
     *
     * @maps correctedRoutingNumber
     */
    public function setCorrectedRoutingNumber(?string $correctedRoutingNumber): void
    {
        $this->correctedRoutingNumber = $correctedRoutingNumber;
    }

    /**
     * Converts the Bank1 object to a human-readable string representation.
     *
     * @return string The string representation of the Bank1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Bank1',
            [
                'account' => $this->account,
                'correctedRoutingNumber' => $this->correctedRoutingNumber,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['account', 'correctedRoutingNumber'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->account)) {
            $json['account']                = $this->account;
        }
        if (isset($this->correctedRoutingNumber)) {
            $json['correctedRoutingNumber'] = $this->correctedRoutingNumber;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
