<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class CreatePaymentRequest implements \JsonSerializable
{
    /**
     * @var ClientReferenceInformation|null
     */
    private $clientReferenceInformation;

    /**
     * @var ProcessingInformation|null
     */
    private $processingInformation;

    /**
     * @var IssuerInformation|null
     */
    private $issuerInformation;

    /**
     * @var PaymentInformation|null
     */
    private $paymentInformation;

    /**
     * @var OrderInformation|null
     */
    private $orderInformation;

    /**
     * @var BuyerInformation|null
     */
    private $buyerInformation;

    /**
     * @var SenderInformation|null
     */
    private $senderInformation;

    /**
     * @var RecipientInformation|null
     */
    private $recipientInformation;

    /**
     * @var DeviceInformation|null
     */
    private $deviceInformation;

    /**
     * @var MerchantInformation|null
     */
    private $merchantInformation;

    /**
     * @var AggregatorInformation|null
     */
    private $aggregatorInformation;

    /**
     * @var ConsumerAuthenticationInformation|null
     */
    private $consumerAuthenticationInformation;

    /**
     * @var PointOfSaleInformation|null
     */
    private $pointOfSaleInformation;

    /**
     * @var MerchantDefinedInformation[]|null
     */
    private $merchantDefinedInformation;

    /**
     * @var MerchantDefinedSecureInformation2|null
     */
    private $merchantDefinedSecureInformation;

    /**
     * @var InstallmentInformation|null
     */
    private $installmentInformation;

    /**
     * @var TravelInformation|null
     */
    private $travelInformation;

    /**
     * @var HealthCareInformation|null
     */
    private $healthCareInformation;

    /**
     * @var PromotionInformation|null
     */
    private $promotionInformation;

    /**
     * @var TokenInformation|null
     */
    private $tokenInformation;

    /**
     * @var InvoiceDetails13|null
     */
    private $invoiceDetails;

    /**
     * @var ProcessorInformation5|null
     */
    private $processorInformation;

    /**
     * @var AgreementInformation|null
     */
    private $agreementInformation;

    /**
     * @var RiskInformation3|null
     */
    private $riskInformation;

    /**
     * @var AcquirerInformation|null
     */
    private $acquirerInformation;

    /**
     * @var RecurringPaymentInformation2|null
     */
    private $recurringPaymentInformation;

    /**
     * @var UnscheduledPaymentInformation|null
     */
    private $unscheduledPaymentInformation;

    /**
     * @var HostedPaymentInformation|null
     */
    private $hostedPaymentInformation;

    /**
     * @var WatchlistScreeningInformation|null
     */
    private $watchlistScreeningInformation;

    /**
     * Returns Client Reference Information.
     */
    public function getClientReferenceInformation(): ?ClientReferenceInformation
    {
        return $this->clientReferenceInformation;
    }

    /**
     * Sets Client Reference Information.
     *
     * @maps clientReferenceInformation
     */
    public function setClientReferenceInformation(?ClientReferenceInformation $clientReferenceInformation): void
    {
        $this->clientReferenceInformation = $clientReferenceInformation;
    }

    /**
     * Returns Processing Information.
     */
    public function getProcessingInformation(): ?ProcessingInformation
    {
        return $this->processingInformation;
    }

    /**
     * Sets Processing Information.
     *
     * @maps processingInformation
     */
    public function setProcessingInformation(?ProcessingInformation $processingInformation): void
    {
        $this->processingInformation = $processingInformation;
    }

    /**
     * Returns Issuer Information.
     */
    public function getIssuerInformation(): ?IssuerInformation
    {
        return $this->issuerInformation;
    }

    /**
     * Sets Issuer Information.
     *
     * @maps issuerInformation
     */
    public function setIssuerInformation(?IssuerInformation $issuerInformation): void
    {
        $this->issuerInformation = $issuerInformation;
    }

    /**
     * Returns Payment Information.
     */
    public function getPaymentInformation(): ?PaymentInformation
    {
        return $this->paymentInformation;
    }

    /**
     * Sets Payment Information.
     *
     * @maps paymentInformation
     */
    public function setPaymentInformation(?PaymentInformation $paymentInformation): void
    {
        $this->paymentInformation = $paymentInformation;
    }

    /**
     * Returns Order Information.
     */
    public function getOrderInformation(): ?OrderInformation
    {
        return $this->orderInformation;
    }

    /**
     * Sets Order Information.
     *
     * @maps orderInformation
     */
    public function setOrderInformation(?OrderInformation $orderInformation): void
    {
        $this->orderInformation = $orderInformation;
    }

    /**
     * Returns Buyer Information.
     */
    public function getBuyerInformation(): ?BuyerInformation
    {
        return $this->buyerInformation;
    }

    /**
     * Sets Buyer Information.
     *
     * @maps buyerInformation
     */
    public function setBuyerInformation(?BuyerInformation $buyerInformation): void
    {
        $this->buyerInformation = $buyerInformation;
    }

    /**
     * Returns Sender Information.
     */
    public function getSenderInformation(): ?SenderInformation
    {
        return $this->senderInformation;
    }

    /**
     * Sets Sender Information.
     *
     * @maps senderInformation
     */
    public function setSenderInformation(?SenderInformation $senderInformation): void
    {
        $this->senderInformation = $senderInformation;
    }

    /**
     * Returns Recipient Information.
     */
    public function getRecipientInformation(): ?RecipientInformation
    {
        return $this->recipientInformation;
    }

    /**
     * Sets Recipient Information.
     *
     * @maps recipientInformation
     */
    public function setRecipientInformation(?RecipientInformation $recipientInformation): void
    {
        $this->recipientInformation = $recipientInformation;
    }

    /**
     * Returns Device Information.
     */
    public function getDeviceInformation(): ?DeviceInformation
    {
        return $this->deviceInformation;
    }

    /**
     * Sets Device Information.
     *
     * @maps deviceInformation
     */
    public function setDeviceInformation(?DeviceInformation $deviceInformation): void
    {
        $this->deviceInformation = $deviceInformation;
    }

    /**
     * Returns Merchant Information.
     */
    public function getMerchantInformation(): ?MerchantInformation
    {
        return $this->merchantInformation;
    }

    /**
     * Sets Merchant Information.
     *
     * @maps merchantInformation
     */
    public function setMerchantInformation(?MerchantInformation $merchantInformation): void
    {
        $this->merchantInformation = $merchantInformation;
    }

    /**
     * Returns Aggregator Information.
     */
    public function getAggregatorInformation(): ?AggregatorInformation
    {
        return $this->aggregatorInformation;
    }

    /**
     * Sets Aggregator Information.
     *
     * @maps aggregatorInformation
     */
    public function setAggregatorInformation(?AggregatorInformation $aggregatorInformation): void
    {
        $this->aggregatorInformation = $aggregatorInformation;
    }

    /**
     * Returns Consumer Authentication Information.
     */
    public function getConsumerAuthenticationInformation(): ?ConsumerAuthenticationInformation
    {
        return $this->consumerAuthenticationInformation;
    }

    /**
     * Sets Consumer Authentication Information.
     *
     * @maps consumerAuthenticationInformation
     */
    public function setConsumerAuthenticationInformation(
        ?ConsumerAuthenticationInformation $consumerAuthenticationInformation
    ): void {
        $this->consumerAuthenticationInformation = $consumerAuthenticationInformation;
    }

    /**
     * Returns Point of Sale Information.
     */
    public function getPointOfSaleInformation(): ?PointOfSaleInformation
    {
        return $this->pointOfSaleInformation;
    }

    /**
     * Sets Point of Sale Information.
     *
     * @maps pointOfSaleInformation
     */
    public function setPointOfSaleInformation(?PointOfSaleInformation $pointOfSaleInformation): void
    {
        $this->pointOfSaleInformation = $pointOfSaleInformation;
    }

    /**
     * Returns Merchant Defined Information.
     * The object containing the custom data that the merchant defines.
     *
     * @return MerchantDefinedInformation[]|null
     */
    public function getMerchantDefinedInformation(): ?array
    {
        return $this->merchantDefinedInformation;
    }

    /**
     * Sets Merchant Defined Information.
     * The object containing the custom data that the merchant defines.
     *
     * @maps merchantDefinedInformation
     *
     * @param MerchantDefinedInformation[]|null $merchantDefinedInformation
     */
    public function setMerchantDefinedInformation(?array $merchantDefinedInformation): void
    {
        $this->merchantDefinedInformation = $merchantDefinedInformation;
    }

    /**
     * Returns Merchant Defined Secure Information.
     */
    public function getMerchantDefinedSecureInformation(): ?MerchantDefinedSecureInformation2
    {
        return $this->merchantDefinedSecureInformation;
    }

    /**
     * Sets Merchant Defined Secure Information.
     *
     * @maps merchantDefinedSecureInformation
     */
    public function setMerchantDefinedSecureInformation(
        ?MerchantDefinedSecureInformation2 $merchantDefinedSecureInformation
    ): void {
        $this->merchantDefinedSecureInformation = $merchantDefinedSecureInformation;
    }

    /**
     * Returns Installment Information.
     */
    public function getInstallmentInformation(): ?InstallmentInformation
    {
        return $this->installmentInformation;
    }

    /**
     * Sets Installment Information.
     *
     * @maps installmentInformation
     */
    public function setInstallmentInformation(?InstallmentInformation $installmentInformation): void
    {
        $this->installmentInformation = $installmentInformation;
    }

    /**
     * Returns Travel Information.
     */
    public function getTravelInformation(): ?TravelInformation
    {
        return $this->travelInformation;
    }

    /**
     * Sets Travel Information.
     *
     * @maps travelInformation
     */
    public function setTravelInformation(?TravelInformation $travelInformation): void
    {
        $this->travelInformation = $travelInformation;
    }

    /**
     * Returns Health Care Information.
     */
    public function getHealthCareInformation(): ?HealthCareInformation
    {
        return $this->healthCareInformation;
    }

    /**
     * Sets Health Care Information.
     *
     * @maps healthCareInformation
     */
    public function setHealthCareInformation(?HealthCareInformation $healthCareInformation): void
    {
        $this->healthCareInformation = $healthCareInformation;
    }

    /**
     * Returns Promotion Information.
     */
    public function getPromotionInformation(): ?PromotionInformation
    {
        return $this->promotionInformation;
    }

    /**
     * Sets Promotion Information.
     *
     * @maps promotionInformation
     */
    public function setPromotionInformation(?PromotionInformation $promotionInformation): void
    {
        $this->promotionInformation = $promotionInformation;
    }

    /**
     * Returns Token Information.
     */
    public function getTokenInformation(): ?TokenInformation
    {
        return $this->tokenInformation;
    }

    /**
     * Sets Token Information.
     *
     * @maps tokenInformation
     */
    public function setTokenInformation(?TokenInformation $tokenInformation): void
    {
        $this->tokenInformation = $tokenInformation;
    }

    /**
     * Returns Invoice Details.
     */
    public function getInvoiceDetails(): ?InvoiceDetails13
    {
        return $this->invoiceDetails;
    }

    /**
     * Sets Invoice Details.
     *
     * @maps invoiceDetails
     */
    public function setInvoiceDetails(?InvoiceDetails13 $invoiceDetails): void
    {
        $this->invoiceDetails = $invoiceDetails;
    }

    /**
     * Returns Processor Information.
     */
    public function getProcessorInformation(): ?ProcessorInformation5
    {
        return $this->processorInformation;
    }

    /**
     * Sets Processor Information.
     *
     * @maps processorInformation
     */
    public function setProcessorInformation(?ProcessorInformation5 $processorInformation): void
    {
        $this->processorInformation = $processorInformation;
    }

    /**
     * Returns Agreement Information.
     */
    public function getAgreementInformation(): ?AgreementInformation
    {
        return $this->agreementInformation;
    }

    /**
     * Sets Agreement Information.
     *
     * @maps agreementInformation
     */
    public function setAgreementInformation(?AgreementInformation $agreementInformation): void
    {
        $this->agreementInformation = $agreementInformation;
    }

    /**
     * Returns Risk Information.
     */
    public function getRiskInformation(): ?RiskInformation3
    {
        return $this->riskInformation;
    }

    /**
     * Sets Risk Information.
     *
     * @maps riskInformation
     */
    public function setRiskInformation(?RiskInformation3 $riskInformation): void
    {
        $this->riskInformation = $riskInformation;
    }

    /**
     * Returns Acquirer Information.
     */
    public function getAcquirerInformation(): ?AcquirerInformation
    {
        return $this->acquirerInformation;
    }

    /**
     * Sets Acquirer Information.
     *
     * @maps acquirerInformation
     */
    public function setAcquirerInformation(?AcquirerInformation $acquirerInformation): void
    {
        $this->acquirerInformation = $acquirerInformation;
    }

    /**
     * Returns Recurring Payment Information.
     */
    public function getRecurringPaymentInformation(): ?RecurringPaymentInformation2
    {
        return $this->recurringPaymentInformation;
    }

    /**
     * Sets Recurring Payment Information.
     *
     * @maps recurringPaymentInformation
     */
    public function setRecurringPaymentInformation(?RecurringPaymentInformation2 $recurringPaymentInformation): void
    {
        $this->recurringPaymentInformation = $recurringPaymentInformation;
    }

    /**
     * Returns Unscheduled Payment Information.
     */
    public function getUnscheduledPaymentInformation(): ?UnscheduledPaymentInformation
    {
        return $this->unscheduledPaymentInformation;
    }

    /**
     * Sets Unscheduled Payment Information.
     *
     * @maps unscheduledPaymentInformation
     */
    public function setUnscheduledPaymentInformation(
        ?UnscheduledPaymentInformation $unscheduledPaymentInformation
    ): void {
        $this->unscheduledPaymentInformation = $unscheduledPaymentInformation;
    }

    /**
     * Returns Hosted Payment Information.
     */
    public function getHostedPaymentInformation(): ?HostedPaymentInformation
    {
        return $this->hostedPaymentInformation;
    }

    /**
     * Sets Hosted Payment Information.
     *
     * @maps hostedPaymentInformation
     */
    public function setHostedPaymentInformation(?HostedPaymentInformation $hostedPaymentInformation): void
    {
        $this->hostedPaymentInformation = $hostedPaymentInformation;
    }

    /**
     * Returns Watchlist Screening Information.
     */
    public function getWatchlistScreeningInformation(): ?WatchlistScreeningInformation
    {
        return $this->watchlistScreeningInformation;
    }

    /**
     * Sets Watchlist Screening Information.
     *
     * @maps watchlistScreeningInformation
     */
    public function setWatchlistScreeningInformation(
        ?WatchlistScreeningInformation $watchlistScreeningInformation
    ): void {
        $this->watchlistScreeningInformation = $watchlistScreeningInformation;
    }

    /**
     * Converts the CreatePaymentRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CreatePaymentRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreatePaymentRequest',
            [
                'clientReferenceInformation' => $this->clientReferenceInformation,
                'processingInformation' => $this->processingInformation,
                'issuerInformation' => $this->issuerInformation,
                'paymentInformation' => $this->paymentInformation,
                'orderInformation' => $this->orderInformation,
                'buyerInformation' => $this->buyerInformation,
                'senderInformation' => $this->senderInformation,
                'recipientInformation' => $this->recipientInformation,
                'deviceInformation' => $this->deviceInformation,
                'merchantInformation' => $this->merchantInformation,
                'aggregatorInformation' => $this->aggregatorInformation,
                'consumerAuthenticationInformation' => $this->consumerAuthenticationInformation,
                'pointOfSaleInformation' => $this->pointOfSaleInformation,
                'merchantDefinedInformation' => $this->merchantDefinedInformation,
                'merchantDefinedSecureInformation' => $this->merchantDefinedSecureInformation,
                'installmentInformation' => $this->installmentInformation,
                'travelInformation' => $this->travelInformation,
                'healthCareInformation' => $this->healthCareInformation,
                'promotionInformation' => $this->promotionInformation,
                'tokenInformation' => $this->tokenInformation,
                'invoiceDetails' => $this->invoiceDetails,
                'processorInformation' => $this->processorInformation,
                'agreementInformation' => $this->agreementInformation,
                'riskInformation' => $this->riskInformation,
                'acquirerInformation' => $this->acquirerInformation,
                'recurringPaymentInformation' => $this->recurringPaymentInformation,
                'unscheduledPaymentInformation' => $this->unscheduledPaymentInformation,
                'hostedPaymentInformation' => $this->hostedPaymentInformation,
                'watchlistScreeningInformation' => $this->watchlistScreeningInformation,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'clientReferenceInformation',
        'processingInformation',
        'issuerInformation',
        'paymentInformation',
        'orderInformation',
        'buyerInformation',
        'senderInformation',
        'recipientInformation',
        'deviceInformation',
        'merchantInformation',
        'aggregatorInformation',
        'consumerAuthenticationInformation',
        'pointOfSaleInformation',
        'merchantDefinedInformation',
        'merchantDefinedSecureInformation',
        'installmentInformation',
        'travelInformation',
        'healthCareInformation',
        'promotionInformation',
        'tokenInformation',
        'invoiceDetails',
        'processorInformation',
        'agreementInformation',
        'riskInformation',
        'acquirerInformation',
        'recurringPaymentInformation',
        'unscheduledPaymentInformation',
        'hostedPaymentInformation',
        'watchlistScreeningInformation'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->clientReferenceInformation)) {
            $json['clientReferenceInformation']        = $this->clientReferenceInformation;
        }
        if (isset($this->processingInformation)) {
            $json['processingInformation']             = $this->processingInformation;
        }
        if (isset($this->issuerInformation)) {
            $json['issuerInformation']                 = $this->issuerInformation;
        }
        if (isset($this->paymentInformation)) {
            $json['paymentInformation']                = $this->paymentInformation;
        }
        if (isset($this->orderInformation)) {
            $json['orderInformation']                  = $this->orderInformation;
        }
        if (isset($this->buyerInformation)) {
            $json['buyerInformation']                  = $this->buyerInformation;
        }
        if (isset($this->senderInformation)) {
            $json['senderInformation']                 = $this->senderInformation;
        }
        if (isset($this->recipientInformation)) {
            $json['recipientInformation']              = $this->recipientInformation;
        }
        if (isset($this->deviceInformation)) {
            $json['deviceInformation']                 = $this->deviceInformation;
        }
        if (isset($this->merchantInformation)) {
            $json['merchantInformation']               = $this->merchantInformation;
        }
        if (isset($this->aggregatorInformation)) {
            $json['aggregatorInformation']             = $this->aggregatorInformation;
        }
        if (isset($this->consumerAuthenticationInformation)) {
            $json['consumerAuthenticationInformation'] = $this->consumerAuthenticationInformation;
        }
        if (isset($this->pointOfSaleInformation)) {
            $json['pointOfSaleInformation']            = $this->pointOfSaleInformation;
        }
        if (isset($this->merchantDefinedInformation)) {
            $json['merchantDefinedInformation']        = $this->merchantDefinedInformation;
        }
        if (isset($this->merchantDefinedSecureInformation)) {
            $json['merchantDefinedSecureInformation']  = $this->merchantDefinedSecureInformation;
        }
        if (isset($this->installmentInformation)) {
            $json['installmentInformation']            = $this->installmentInformation;
        }
        if (isset($this->travelInformation)) {
            $json['travelInformation']                 = $this->travelInformation;
        }
        if (isset($this->healthCareInformation)) {
            $json['healthCareInformation']             = $this->healthCareInformation;
        }
        if (isset($this->promotionInformation)) {
            $json['promotionInformation']              = $this->promotionInformation;
        }
        if (isset($this->tokenInformation)) {
            $json['tokenInformation']                  = $this->tokenInformation;
        }
        if (isset($this->invoiceDetails)) {
            $json['invoiceDetails']                    = $this->invoiceDetails;
        }
        if (isset($this->processorInformation)) {
            $json['processorInformation']              = $this->processorInformation;
        }
        if (isset($this->agreementInformation)) {
            $json['agreementInformation']              = $this->agreementInformation;
        }
        if (isset($this->riskInformation)) {
            $json['riskInformation']                   = $this->riskInformation;
        }
        if (isset($this->acquirerInformation)) {
            $json['acquirerInformation']               = $this->acquirerInformation;
        }
        if (isset($this->recurringPaymentInformation)) {
            $json['recurringPaymentInformation']       = $this->recurringPaymentInformation;
        }
        if (isset($this->unscheduledPaymentInformation)) {
            $json['unscheduledPaymentInformation']     = $this->unscheduledPaymentInformation;
        }
        if (isset($this->hostedPaymentInformation)) {
            $json['hostedPaymentInformation']          = $this->hostedPaymentInformation;
        }
        if (isset($this->watchlistScreeningInformation)) {
            $json['watchlistScreeningInformation']     = $this->watchlistScreeningInformation;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
