<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

/**
 * Contains embedded actions, that includes status and response for every actions in the list.
 */
class EmbeddedActions implements \JsonSerializable
{
    /**
     * @var Capture1|null
     */
    private $capture;

    /**
     * @var Decision|null
     */
    private $decision;

    /**
     * @var Consumerauthentication|null
     */
    private $consumerAuthentication;

    /**
     * @var Validateconsumerauthentication|null
     */
    private $validateConsumerAuthentication;

    /**
     * @var Watchlistscreening|null
     */
    private $watchlistScreening;

    /**
     * @var Tokencreate|null
     */
    private $tokenCreate;

    /**
     * @var Tokenupdate|null
     */
    private $tokenUpdate;

    /**
     * Returns Capture.
     */
    public function getCapture(): ?Capture1
    {
        return $this->capture;
    }

    /**
     * Sets Capture.
     *
     * @maps CAPTURE
     */
    public function setCapture(?Capture1 $capture): void
    {
        $this->capture = $capture;
    }

    /**
     * Returns Decision.
     */
    public function getDecision(): ?Decision
    {
        return $this->decision;
    }

    /**
     * Sets Decision.
     *
     * @maps DECISION
     */
    public function setDecision(?Decision $decision): void
    {
        $this->decision = $decision;
    }

    /**
     * Returns Consumer Authentication.
     */
    public function getConsumerAuthentication(): ?Consumerauthentication
    {
        return $this->consumerAuthentication;
    }

    /**
     * Sets Consumer Authentication.
     *
     * @maps CONSUMER_AUTHENTICATION
     */
    public function setConsumerAuthentication(?Consumerauthentication $consumerAuthentication): void
    {
        $this->consumerAuthentication = $consumerAuthentication;
    }

    /**
     * Returns Validate Consumer Authentication.
     */
    public function getValidateConsumerAuthentication(): ?Validateconsumerauthentication
    {
        return $this->validateConsumerAuthentication;
    }

    /**
     * Sets Validate Consumer Authentication.
     *
     * @maps VALIDATE_CONSUMER_AUTHENTICATION
     */
    public function setValidateConsumerAuthentication(
        ?Validateconsumerauthentication $validateConsumerAuthentication
    ): void {
        $this->validateConsumerAuthentication = $validateConsumerAuthentication;
    }

    /**
     * Returns Watchlist Screening.
     */
    public function getWatchlistScreening(): ?Watchlistscreening
    {
        return $this->watchlistScreening;
    }

    /**
     * Sets Watchlist Screening.
     *
     * @maps WATCHLIST_SCREENING
     */
    public function setWatchlistScreening(?Watchlistscreening $watchlistScreening): void
    {
        $this->watchlistScreening = $watchlistScreening;
    }

    /**
     * Returns Token Create.
     */
    public function getTokenCreate(): ?Tokencreate
    {
        return $this->tokenCreate;
    }

    /**
     * Sets Token Create.
     *
     * @maps TOKEN_CREATE
     */
    public function setTokenCreate(?Tokencreate $tokenCreate): void
    {
        $this->tokenCreate = $tokenCreate;
    }

    /**
     * Returns Token Update.
     */
    public function getTokenUpdate(): ?Tokenupdate
    {
        return $this->tokenUpdate;
    }

    /**
     * Sets Token Update.
     *
     * @maps TOKEN_UPDATE
     */
    public function setTokenUpdate(?Tokenupdate $tokenUpdate): void
    {
        $this->tokenUpdate = $tokenUpdate;
    }

    /**
     * Converts the EmbeddedActions object to a human-readable string representation.
     *
     * @return string The string representation of the EmbeddedActions object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EmbeddedActions',
            [
                'capture' => $this->capture,
                'decision' => $this->decision,
                'consumerAuthentication' => $this->consumerAuthentication,
                'validateConsumerAuthentication' => $this->validateConsumerAuthentication,
                'watchlistScreening' => $this->watchlistScreening,
                'tokenCreate' => $this->tokenCreate,
                'tokenUpdate' => $this->tokenUpdate,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'CAPTURE',
        'DECISION',
        'CONSUMER_AUTHENTICATION',
        'VALIDATE_CONSUMER_AUTHENTICATION',
        'WATCHLIST_SCREENING',
        'TOKEN_CREATE',
        'TOKEN_UPDATE'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->capture)) {
            $json['CAPTURE']                          = $this->capture;
        }
        if (isset($this->decision)) {
            $json['DECISION']                         = $this->decision;
        }
        if (isset($this->consumerAuthentication)) {
            $json['CONSUMER_AUTHENTICATION']          = $this->consumerAuthentication;
        }
        if (isset($this->validateConsumerAuthentication)) {
            $json['VALIDATE_CONSUMER_AUTHENTICATION'] = $this->validateConsumerAuthentication;
        }
        if (isset($this->watchlistScreening)) {
            $json['WATCHLIST_SCREENING']              = $this->watchlistScreening;
        }
        if (isset($this->tokenCreate)) {
            $json['TOKEN_CREATE']                     = $this->tokenCreate;
        }
        if (isset($this->tokenUpdate)) {
            $json['TOKEN_UPDATE']                     = $this->tokenUpdate;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
