<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class Emv implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $tags;

    /**
     * @var int|null
     */
    private $cardholderVerificationMethodUsed;

    /**
     * @var string|null
     */
    private $cardSequenceNumber;

    /**
     * @var bool|null
     */
    private $fallback;

    /**
     * @var int|null
     */
    private $fallbackCondition;

    /**
     * @var bool|null
     */
    private $isRepeat;

    /**
     * Returns Tags.
     * EMV data that is transmitted from the chip card to the issuer, and from the issuer to the chip card.
     * The EMV
     * data is in the tag-length-value format and includes chip card tags, terminal tags, and transaction
     * detail tags.
     *
     * For information about the individual tags, see the “Application Specification” section in the EMV 4.
     * 3 Specifications:
     *
     * **Note** Card present information about EMV applies only to credit card processing and PIN debit
     * processing.
     * All other card present information applies only to credit card processing. PIN debit processing is
     * available only
     * on FDC Nashville Global.
     *
     * **Important** The following tags contain sensitive information and **must not** be included in this
     * field:
     *
     * - `56`: Track 1 equivalent data
     * - `57`: Track 2 equivalent data
     * - `5A`: Application PAN
     * - `5F20`: Cardholder name
     * - `5F24`: Application expiration date (This sensitivity has been relaxed for Credit Mutuel-CIC,
     * American Express Direct, FDC Nashville Global, First Data Merchant Solutions, and SIX)
     * - `99`: Transaction PIN
     * - `9F0B`: Cardholder name (extended)
     * - `9F1F`: Track 1 discretionary data
     * - `9F20`: Track 2 discretionary data
     *
     * For captures, this field is required for contact EMV transactions. Otherwise, it is optional.
     *
     * For credits, this field is required for contact EMV stand-alone credits and contactless EMV stand-
     * alone credits.
     * Otherwise, it is optional.
     *
     * **Important** For contact EMV captures, contact EMV stand-alone credits, and contactless EMV stand-
     * alone credits,
     * you must include the following tags in this field. For all other types of EMV transactions, the
     * following tags
     * are optional.
     *
     * - `95`: Terminal verification results
     * - `9F10`: Issuer application data
     * - `9F26`: Application cryptogram
     *
     *
     * #### Visa Acceptance through VisaNet
     * - In Japan: 199 bytes
     * - In other countries: String (252)
     *
     * For Mastercard Transactions, Optionally Tag 9F60 (Authenticated Application Data) and
     * Tag 96 (Kernel Identifier - Terminal) can be included in the Field.
     *
     * #### GPX
     * This field only supports transactions from the following card types:
     * - Visa
     * - Mastercard
     * - AMEX
     * - Discover
     * - Diners
     * - JCB
     * - Union Pay International
     *
     * #### JCN Gateway
     * The following tags must be included:
     * - `4F`: Application identifier
     * - `84`: Dedicated file name
     *
     * Data length: 199 bytes
     *
     * #### All other processors:
     * String (999)
     *
     * #### Used by
     * Authorization: Optional
     * Authorization Reversal: Optional
     * Credit: Optional
     * PIN Debit processing (purchase, credit and reversal): Optional
     */
    public function getTags(): ?string
    {
        return $this->tags;
    }

    /**
     * Sets Tags.
     * EMV data that is transmitted from the chip card to the issuer, and from the issuer to the chip card.
     * The EMV
     * data is in the tag-length-value format and includes chip card tags, terminal tags, and transaction
     * detail tags.
     *
     * For information about the individual tags, see the “Application Specification” section in the EMV 4.
     * 3 Specifications:
     *
     * **Note** Card present information about EMV applies only to credit card processing and PIN debit
     * processing.
     * All other card present information applies only to credit card processing. PIN debit processing is
     * available only
     * on FDC Nashville Global.
     *
     * **Important** The following tags contain sensitive information and **must not** be included in this
     * field:
     *
     * - `56`: Track 1 equivalent data
     * - `57`: Track 2 equivalent data
     * - `5A`: Application PAN
     * - `5F20`: Cardholder name
     * - `5F24`: Application expiration date (This sensitivity has been relaxed for Credit Mutuel-CIC,
     * American Express Direct, FDC Nashville Global, First Data Merchant Solutions, and SIX)
     * - `99`: Transaction PIN
     * - `9F0B`: Cardholder name (extended)
     * - `9F1F`: Track 1 discretionary data
     * - `9F20`: Track 2 discretionary data
     *
     * For captures, this field is required for contact EMV transactions. Otherwise, it is optional.
     *
     * For credits, this field is required for contact EMV stand-alone credits and contactless EMV stand-
     * alone credits.
     * Otherwise, it is optional.
     *
     * **Important** For contact EMV captures, contact EMV stand-alone credits, and contactless EMV stand-
     * alone credits,
     * you must include the following tags in this field. For all other types of EMV transactions, the
     * following tags
     * are optional.
     *
     * - `95`: Terminal verification results
     * - `9F10`: Issuer application data
     * - `9F26`: Application cryptogram
     *
     *
     * #### Visa Acceptance through VisaNet
     * - In Japan: 199 bytes
     * - In other countries: String (252)
     *
     * For Mastercard Transactions, Optionally Tag 9F60 (Authenticated Application Data) and
     * Tag 96 (Kernel Identifier - Terminal) can be included in the Field.
     *
     * #### GPX
     * This field only supports transactions from the following card types:
     * - Visa
     * - Mastercard
     * - AMEX
     * - Discover
     * - Diners
     * - JCB
     * - Union Pay International
     *
     * #### JCN Gateway
     * The following tags must be included:
     * - `4F`: Application identifier
     * - `84`: Dedicated file name
     *
     * Data length: 199 bytes
     *
     * #### All other processors:
     * String (999)
     *
     * #### Used by
     * Authorization: Optional
     * Authorization Reversal: Optional
     * Credit: Optional
     * PIN Debit processing (purchase, credit and reversal): Optional
     *
     * @maps tags
     */
    public function setTags(?string $tags): void
    {
        $this->tags = $tags;
    }

    /**
     * Returns Cardholder Verification Method Used.
     * Method that was used to verify the cardholder's identity.
     *
     * Possible values:
     * - `0`: No verification
     * - `1`: Signature
     *
     * This field is supported only on **American Express Direct**.
     */
    public function getCardholderVerificationMethodUsed(): ?int
    {
        return $this->cardholderVerificationMethodUsed;
    }

    /**
     * Sets Cardholder Verification Method Used.
     * Method that was used to verify the cardholder's identity.
     *
     * Possible values:
     * - `0`: No verification
     * - `1`: Signature
     *
     * This field is supported only on **American Express Direct**.
     *
     * @maps cardholderVerificationMethodUsed
     */
    public function setCardholderVerificationMethodUsed(?int $cardholderVerificationMethodUsed): void
    {
        $this->cardholderVerificationMethodUsed = $cardholderVerificationMethodUsed;
    }

    /**
     * Returns Card Sequence Number.
     * Number assigned to a specific card when two or more cards are associated with the same primary
     * account number.
     *
     * This value enables issuers to distinguish among multiple cards that are linked to the same account.
     *
     * This value can also act as a tracking tool when reissuing cards.
     *
     * When this value is available, it is provided by the chip reader.
     *
     * When the chip reader does not provide this value, do not include this field in your request.
     *
     * When sequence number is not provided via this API field, the value is extracted from EMV tag 5F34
     * for Visa and Mastercard transactions. To enable this feature please call support.
     *
     * **Note** Card present information about EMV applies only to credit card processing and PIN debit
     * processing.
     *
     * All other card present information applies only to credit card processing.
     *
     * PIN debit processing is available only on Visa Acceptance through VisaNet and FDC Nashville Global.
     *
     * #### Used by
     * Authorization: Optional
     * PIN Debit processing: Optional
     *
     * #### GPX
     *
     * This field only supports transactions from the following card types:
     * - Visa
     * - Mastercard
     * - AMEX
     * - Discover
     * - Diners
     * - JCB
     * - Union Pay International
     */
    public function getCardSequenceNumber(): ?string
    {
        return $this->cardSequenceNumber;
    }

    /**
     * Sets Card Sequence Number.
     * Number assigned to a specific card when two or more cards are associated with the same primary
     * account number.
     *
     * This value enables issuers to distinguish among multiple cards that are linked to the same account.
     *
     * This value can also act as a tracking tool when reissuing cards.
     *
     * When this value is available, it is provided by the chip reader.
     *
     * When the chip reader does not provide this value, do not include this field in your request.
     *
     * When sequence number is not provided via this API field, the value is extracted from EMV tag 5F34
     * for Visa and Mastercard transactions. To enable this feature please call support.
     *
     * **Note** Card present information about EMV applies only to credit card processing and PIN debit
     * processing.
     *
     * All other card present information applies only to credit card processing.
     *
     * PIN debit processing is available only on Visa Acceptance through VisaNet and FDC Nashville Global.
     *
     * #### Used by
     * Authorization: Optional
     * PIN Debit processing: Optional
     *
     * #### GPX
     *
     * This field only supports transactions from the following card types:
     * - Visa
     * - Mastercard
     * - AMEX
     * - Discover
     * - Diners
     * - JCB
     * - Union Pay International
     *
     * @maps cardSequenceNumber
     */
    public function setCardSequenceNumber(?string $cardSequenceNumber): void
    {
        $this->cardSequenceNumber = $cardSequenceNumber;
    }

    /**
     * Returns Fallback.
     * Indicates whether a fallback method was used to enter credit card information into the POS terminal.
     * When a
     * technical problem prevents a successful exchange of information between a chip card and a chip-
     * capable terminal:
     *
     * 1. Swipe the card or key the credit card information into the POS terminal.
     * 2. Use the pointOfSaleInformation.entryMode field to indicate whether the information was swiped or
     * keyed.
     *
     *
     * Possible values:
     * - `true`: Fallback method was used.
     * - `false` (default): Fallback method was not used.
     *
     * This field is supported only on American Express Direct, Chase Paymentech Solutions, Visa Acceptance
     * through VisaNet,
     * FDC Nashville Global, GPN, JCN Gateway, OmniPay Direct, and SIX.
     */
    public function getFallback(): ?bool
    {
        return $this->fallback;
    }

    /**
     * Sets Fallback.
     * Indicates whether a fallback method was used to enter credit card information into the POS terminal.
     * When a
     * technical problem prevents a successful exchange of information between a chip card and a chip-
     * capable terminal:
     *
     * 1. Swipe the card or key the credit card information into the POS terminal.
     * 2. Use the pointOfSaleInformation.entryMode field to indicate whether the information was swiped or
     * keyed.
     *
     *
     * Possible values:
     * - `true`: Fallback method was used.
     * - `false` (default): Fallback method was not used.
     *
     * This field is supported only on American Express Direct, Chase Paymentech Solutions, Visa Acceptance
     * through VisaNet,
     * FDC Nashville Global, GPN, JCN Gateway, OmniPay Direct, and SIX.
     *
     * @maps fallback
     */
    public function setFallback(?bool $fallback): void
    {
        $this->fallback = $fallback;
    }

    /**
     * Returns Fallback Condition.
     * Reason for the EMV fallback transaction. An EMV fallback transaction occurs when an EMV transaction
     * fails for
     * one of these reasons:
     *
     * - Technical failure: the EMV terminal or EMV card cannot read and process chip data.
     * - Empty candidate list failure: the EMV terminal does not have any applications in common with the
     * EMV card.
     * EMV terminals are coded to determine whether the terminal and EMV card have any applications in
     * common.
     * EMV terminals provide this information to you.
     *
     * Possible values:
     *
     * - `1`: Transaction was initiated with information from a magnetic stripe, and the previous
     * transaction at the
     * EMV terminal either used information from a successful chip read or it was not a chip
     * transaction.
     * - `2`: Transaction was initiated with information from a magnetic stripe, and the previous
     * transaction at the
     * EMV terminal was an EMV fallback transaction because the attempted chip read was unsuccessful.
     *
     * This field is supported only on **GPN** and **JCN Gateway**.
     * **NOTE**: This field is required when an EMV transaction fails for a technical reason. Do not
     * include this field
     * when the EMV terminal does not have any applications in common with the EMV card.
     */
    public function getFallbackCondition(): ?int
    {
        return $this->fallbackCondition;
    }

    /**
     * Sets Fallback Condition.
     * Reason for the EMV fallback transaction. An EMV fallback transaction occurs when an EMV transaction
     * fails for
     * one of these reasons:
     *
     * - Technical failure: the EMV terminal or EMV card cannot read and process chip data.
     * - Empty candidate list failure: the EMV terminal does not have any applications in common with the
     * EMV card.
     * EMV terminals are coded to determine whether the terminal and EMV card have any applications in
     * common.
     * EMV terminals provide this information to you.
     *
     * Possible values:
     *
     * - `1`: Transaction was initiated with information from a magnetic stripe, and the previous
     * transaction at the
     * EMV terminal either used information from a successful chip read or it was not a chip
     * transaction.
     * - `2`: Transaction was initiated with information from a magnetic stripe, and the previous
     * transaction at the
     * EMV terminal was an EMV fallback transaction because the attempted chip read was unsuccessful.
     *
     * This field is supported only on **GPN** and **JCN Gateway**.
     * **NOTE**: This field is required when an EMV transaction fails for a technical reason. Do not
     * include this field
     * when the EMV terminal does not have any applications in common with the EMV card.
     *
     * @maps fallbackCondition
     */
    public function setFallbackCondition(?int $fallbackCondition): void
    {
        $this->fallbackCondition = $fallbackCondition;
    }

    /**
     * Returns Is Repeat.
     * #### Visa Platform Connect
     * Value “true” indicates this transaction is intentionally duplicated . The field contains value
     * “true” which
     * indicates that merchant has intentionally duplicated single tap transaction. Merchant is
     * intentionally sending
     * a duplicate auth request for a single tap txn because the issuer requested a PIN.
     */
    public function getIsRepeat(): ?bool
    {
        return $this->isRepeat;
    }

    /**
     * Sets Is Repeat.
     * #### Visa Platform Connect
     * Value “true” indicates this transaction is intentionally duplicated . The field contains value
     * “true” which
     * indicates that merchant has intentionally duplicated single tap transaction. Merchant is
     * intentionally sending
     * a duplicate auth request for a single tap txn because the issuer requested a PIN.
     *
     * @maps isRepeat
     */
    public function setIsRepeat(?bool $isRepeat): void
    {
        $this->isRepeat = $isRepeat;
    }

    /**
     * Converts the Emv object to a human-readable string representation.
     *
     * @return string The string representation of the Emv object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Emv',
            [
                'tags' => $this->tags,
                'cardholderVerificationMethodUsed' => $this->cardholderVerificationMethodUsed,
                'cardSequenceNumber' => $this->cardSequenceNumber,
                'fallback' => $this->fallback,
                'fallbackCondition' => $this->fallbackCondition,
                'isRepeat' => $this->isRepeat,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'tags',
        'cardholderVerificationMethodUsed',
        'cardSequenceNumber',
        'fallback',
        'fallbackCondition',
        'isRepeat'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->tags)) {
            $json['tags']                             = $this->tags;
        }
        if (isset($this->cardholderVerificationMethodUsed)) {
            $json['cardholderVerificationMethodUsed'] = $this->cardholderVerificationMethodUsed;
        }
        if (isset($this->cardSequenceNumber)) {
            $json['cardSequenceNumber']               = $this->cardSequenceNumber;
        }
        if (isset($this->fallback)) {
            $json['fallback']                         = $this->fallback;
        }
        if (isset($this->fallbackCondition)) {
            $json['fallbackCondition']                = $this->fallbackCondition;
        }
        if (isset($this->isRepeat)) {
            $json['isRepeat']                         = $this->isRepeat;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
