<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class GenerateUnifiedCheckoutCaptureContextException implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $correlationId;

    /**
     * @var Detail66[]|null
     */
    private $details;

    /**
     * @var string|null
     */
    private $informationLink;

    /**
     * @var string
     */
    private $message;

    /**
     * @var string
     */
    private $reason;

    /**
     * @param string $message
     * @param string $reason
     */
    public function __construct(string $message, string $reason)
    {
        $this->message = $message;
        $this->reason = $reason;
    }

    /**
     * Returns Correlation Id.
     */
    public function getCorrelationId(): ?string
    {
        return $this->correlationId;
    }

    /**
     * Sets Correlation Id.
     *
     * @maps correlationId
     */
    public function setCorrelationId(?string $correlationId): void
    {
        $this->correlationId = $correlationId;
    }

    /**
     * Returns Details.
     *
     * @return Detail66[]|null
     */
    public function getDetails(): ?array
    {
        return $this->details;
    }

    /**
     * Sets Details.
     *
     * @maps details
     *
     * @param Detail66[]|null $details
     */
    public function setDetails(?array $details): void
    {
        $this->details = $details;
    }

    /**
     * Returns Information Link.
     */
    public function getInformationLink(): ?string
    {
        return $this->informationLink;
    }

    /**
     * Sets Information Link.
     *
     * @maps informationLink
     */
    public function setInformationLink(?string $informationLink): void
    {
        $this->informationLink = $informationLink;
    }

    /**
     * Returns Message.
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     *
     * @required
     * @maps message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Reason.
     */
    public function getReason(): string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     *
     * @required
     * @maps reason
     */
    public function setReason(string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Converts the GenerateUnifiedCheckoutCaptureContextException object to a human-readable string
     * representation.
     *
     * @return string The string representation of the GenerateUnifiedCheckoutCaptureContextException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GenerateUnifiedCheckoutCaptureContextException',
            [
                'correlationId' => $this->correlationId,
                'details' => $this->details,
                'informationLink' => $this->informationLink,
                'message' => $this->message,
                'reason' => $this->reason,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['correlationId', 'details', 'informationLink', 'message', 'reason'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->correlationId)) {
            $json['correlationId']   = $this->correlationId;
        }
        if (isset($this->details)) {
            $json['details']         = $this->details;
        }
        if (isset($this->informationLink)) {
            $json['informationLink'] = $this->informationLink;
        }
        $json['message']             = $this->message;
        $json['reason']              = $this->reason;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
