<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class LoanOptions implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $assetType;

    /**
     * Returns Type.
     * Type of loan based on an agreement between you and the issuer.
     * Examples: AGROCUSTEIO, AGRO-INVEST, BNDES-Type1, CBN, FINAME.
     * This field is supported only for these kinds of payments:
     * - BNDES transactions on Visa Acceptance through VisaNet.
     * - Installment payments with Mastercard on Visa Acceptance through VisaNet in Brazil.
     *
     * For BNDES transactions, the value for this field corresponds to the following data in the TC 33
     * capture file:
     * - Record: CP07 TCR2, Position: 27-46, Field: Loan Type
     *
     * For installment payments with Mastercard in Brazil, the value for this field corresponds to the
     * following data in the TC 33 capture file:
     * - Record: CP07 TCR4, Position: 5-24,Field: Financing Type
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Type of loan based on an agreement between you and the issuer.
     * Examples: AGROCUSTEIO, AGRO-INVEST, BNDES-Type1, CBN, FINAME.
     * This field is supported only for these kinds of payments:
     * - BNDES transactions on Visa Acceptance through VisaNet.
     * - Installment payments with Mastercard on Visa Acceptance through VisaNet in Brazil.
     *
     * For BNDES transactions, the value for this field corresponds to the following data in the TC 33
     * capture file:
     * - Record: CP07 TCR2, Position: 27-46, Field: Loan Type
     *
     * For installment payments with Mastercard in Brazil, the value for this field corresponds to the
     * following data in the TC 33 capture file:
     * - Record: CP07 TCR4, Position: 5-24,Field: Financing Type
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Asset Type.
     * Indicates whether a loan is for a recoverable item or a non-recoverable item.
     * Possible values:
     * - `N`: non-recoverable item
     * - `R`: recoverable item
     * This field is supported only for BNDES transactions on Visa Acceptance through VisaNet.
     * The value for this field corresponds to the following data in the TC 33 capture file5:
     * Record: CP07 TCR2, Position: 26, Field: Asset Indicator
     */
    public function getAssetType(): ?string
    {
        return $this->assetType;
    }

    /**
     * Sets Asset Type.
     * Indicates whether a loan is for a recoverable item or a non-recoverable item.
     * Possible values:
     * - `N`: non-recoverable item
     * - `R`: recoverable item
     * This field is supported only for BNDES transactions on Visa Acceptance through VisaNet.
     * The value for this field corresponds to the following data in the TC 33 capture file5:
     * Record: CP07 TCR2, Position: 26, Field: Asset Indicator
     *
     * @maps assetType
     */
    public function setAssetType(?string $assetType): void
    {
        $this->assetType = $assetType;
    }

    /**
     * Converts the LoanOptions object to a human-readable string representation.
     *
     * @return string The string representation of the LoanOptions object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'LoanOptions',
            [
                'type' => $this->type,
                'assetType' => $this->assetType,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['type', 'assetType'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->type)) {
            $json['type']      = $this->type;
        }
        if (isset($this->assetType)) {
            $json['assetType'] = $this->assetType;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
