<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class MerchantDefinedInformation7 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $value;

    /**
     * Returns Name.
     * The number you assign as the name for your merchant-defined data or secure field. Possible Values
     * are data1 to data4 and sensitive1 to sensitive4
     *
     * For example, to set the name for merchant-defined data 2 field, you would reference
     * merchantDefinedInformation[x].name as data2
     * Possible Values:
     * - data1
     * - data2
     * - data3
     * - data4
     * - sensitive1
     * - sensitive2
     * - sensitive3
     * - sensitive4
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The number you assign as the name for your merchant-defined data or secure field. Possible Values
     * are data1 to data4 and sensitive1 to sensitive4
     *
     * For example, to set the name for merchant-defined data 2 field, you would reference
     * merchantDefinedInformation[x].name as data2
     * Possible Values:
     * - data1
     * - data2
     * - data3
     * - data4
     * - sensitive1
     * - sensitive2
     * - sensitive3
     * - sensitive4
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Value.
     * The value you assign for your merchant-defined data field.
     *
     * **Warning** Merchant-defined data fields are not intended to and must not be used to capture
     * personally identifying information. Accordingly, merchants are prohibited from capturing, obtaining,
     * and/or transmitting any personally identifying information in or via the merchant-defined data
     * fields. Personally identifying information includes, but is not
     * limited to, address, credit card number, social security number, driver's license number, state-
     * issued identification number, passport number, and card verification numbers (CVV,
     * CVC2, CVV2, CID, CVN). In the event it is discovered a merchant is capturing and/or transmitting
     * personally identifying information via the merchant-defined data fields, whether or not
     * intentionally, the merchant's account will immediately be suspended, which will result in a
     * rejection of any and all transaction requests submitted by the merchant after the point of
     * suspension.
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * The value you assign for your merchant-defined data field.
     *
     * **Warning** Merchant-defined data fields are not intended to and must not be used to capture
     * personally identifying information. Accordingly, merchants are prohibited from capturing, obtaining,
     * and/or transmitting any personally identifying information in or via the merchant-defined data
     * fields. Personally identifying information includes, but is not
     * limited to, address, credit card number, social security number, driver's license number, state-
     * issued identification number, passport number, and card verification numbers (CVV,
     * CVC2, CVV2, CID, CVN). In the event it is discovered a merchant is capturing and/or transmitting
     * personally identifying information via the merchant-defined data fields, whether or not
     * intentionally, the merchant's account will immediately be suspended, which will result in a
     * rejection of any and all transaction requests submitted by the merchant after the point of
     * suspension.
     *
     * @maps value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Converts the MerchantDefinedInformation7 object to a human-readable string representation.
     *
     * @return string The string representation of the MerchantDefinedInformation7 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MerchantDefinedInformation7',
            ['name' => $this->name, 'value' => $this->value, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['name', 'value'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']  = $this->name;
        }
        if (isset($this->value)) {
            $json['value'] = $this->value;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
