<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

/**
 * The object containing the secure data that the merchant defines.
 */
class MerchantDefinedSecureInformation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $secure1;

    /**
     * @var string|null
     */
    private $secure2;

    /**
     * @var string|null
     */
    private $secure3;

    /**
     * @var string|null
     */
    private $secure4;

    /**
     * Returns Secure 1.
     * The value you assign for your merchant-secure data field 1.
     */
    public function getSecure1(): ?string
    {
        return $this->secure1;
    }

    /**
     * Sets Secure 1.
     * The value you assign for your merchant-secure data field 1.
     *
     * @maps secure1
     */
    public function setSecure1(?string $secure1): void
    {
        $this->secure1 = $secure1;
    }

    /**
     * Returns Secure 2.
     * The value you assign for your merchant-secure data field 2.
     */
    public function getSecure2(): ?string
    {
        return $this->secure2;
    }

    /**
     * Sets Secure 2.
     * The value you assign for your merchant-secure data field 2.
     *
     * @maps secure2
     */
    public function setSecure2(?string $secure2): void
    {
        $this->secure2 = $secure2;
    }

    /**
     * Returns Secure 3.
     * The value you assign for your merchant-secure data field 3.
     */
    public function getSecure3(): ?string
    {
        return $this->secure3;
    }

    /**
     * Sets Secure 3.
     * The value you assign for your merchant-secure data field 3.
     *
     * @maps secure3
     */
    public function setSecure3(?string $secure3): void
    {
        $this->secure3 = $secure3;
    }

    /**
     * Returns Secure 4.
     * The value you assign for your merchant-secure data field 4.
     */
    public function getSecure4(): ?string
    {
        return $this->secure4;
    }

    /**
     * Sets Secure 4.
     * The value you assign for your merchant-secure data field 4.
     *
     * @maps secure4
     */
    public function setSecure4(?string $secure4): void
    {
        $this->secure4 = $secure4;
    }

    /**
     * Converts the MerchantDefinedSecureInformation object to a human-readable string representation.
     *
     * @return string The string representation of the MerchantDefinedSecureInformation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MerchantDefinedSecureInformation',
            [
                'secure1' => $this->secure1,
                'secure2' => $this->secure2,
                'secure3' => $this->secure3,
                'secure4' => $this->secure4,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['secure1', 'secure2', 'secure3', 'secure4'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->secure1)) {
            $json['secure1'] = $this->secure1;
        }
        if (isset($this->secure2)) {
            $json['secure2'] = $this->secure2;
        }
        if (isset($this->secure3)) {
            $json['secure3'] = $this->secure3;
        }
        if (isset($this->secure4)) {
            $json['secure4'] = $this->secure4;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
