<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class MerchantInitiatedTransactionObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $reason;

    /**
     * @var string|null
     */
    private $previousTransactionId;

    /**
     * @var string|null
     */
    private $originalAuthorizedAmount;

    /**
     * @var string|null
     */
    private $agreementId;

    /**
     * Returns Reason.
     * Reason for the merchant-initiated transaction or incremental authorization. Possible values:
     * - `1`: Resubmission
     * - `2`: Delayed charge
     * - `3`: Reauthorization for split shipment
     * - `4`: No show
     * - `5`: Account top up
     * This field is required only for the five kinds of transactions in the preceding list.
     * This field is supported only for merchant-initiated transactions and incremental authorizations.
     *
     * #### Visa Acceptance through VisaNet
     * The value for this field corresponds to the following data in the TC 33 capture file5:
     * - Record: CP01 TCR0
     * - Position: 160-163
     * - Field: Message Reason Code
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * Reason for the merchant-initiated transaction or incremental authorization. Possible values:
     * - `1`: Resubmission
     * - `2`: Delayed charge
     * - `3`: Reauthorization for split shipment
     * - `4`: No show
     * - `5`: Account top up
     * This field is required only for the five kinds of transactions in the preceding list.
     * This field is supported only for merchant-initiated transactions and incremental authorizations.
     *
     * #### Visa Acceptance through VisaNet
     * The value for this field corresponds to the following data in the TC 33 capture file5:
     * - Record: CP01 TCR0
     * - Position: 160-163
     * - Field: Message Reason Code
     *
     * @maps reason
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Returns Previous Transaction Id.
     * Network transaction identifier that was returned in the payment response field _processorInformation.
     * transactionID_
     * in the reply message for either the original merchant-initiated payment in the series or the
     * previous
     * merchant-initiated payment in the series.
     *
     * If the current payment request includes a token instead of an account number, the following time
     * limits apply for the value of this field:
     * - For a **resubmission**, the transaction ID must be less than 14 days old.
     * - For a **delayed charge** or **reauthorization**, the transaction ID must be less than 30 days old.
     *
     * **NOTE**: The value for this field does not correspond to any data in the TC 33 capture file5. This
     * field is supported
     * only for Visa transactions on Visa Acceptance through VisaNet.
     */
    public function getPreviousTransactionId(): ?string
    {
        return $this->previousTransactionId;
    }

    /**
     * Sets Previous Transaction Id.
     * Network transaction identifier that was returned in the payment response field _processorInformation.
     * transactionID_
     * in the reply message for either the original merchant-initiated payment in the series or the
     * previous
     * merchant-initiated payment in the series.
     *
     * If the current payment request includes a token instead of an account number, the following time
     * limits apply for the value of this field:
     * - For a **resubmission**, the transaction ID must be less than 14 days old.
     * - For a **delayed charge** or **reauthorization**, the transaction ID must be less than 30 days old.
     *
     * **NOTE**: The value for this field does not correspond to any data in the TC 33 capture file5. This
     * field is supported
     * only for Visa transactions on Visa Acceptance through VisaNet.
     *
     * @maps previousTransactionId
     */
    public function setPreviousTransactionId(?string $previousTransactionId): void
    {
        $this->previousTransactionId = $previousTransactionId;
    }

    /**
     * Returns Original Authorized Amount.
     * Amount of the original authorization.
     *
     * This field is supported only for Apple Pay, Google Pay, and Samsung Pay transactions with Discover
     * on FDC Nashville Global and Chase Paymentech.
     */
    public function getOriginalAuthorizedAmount(): ?string
    {
        return $this->originalAuthorizedAmount;
    }

    /**
     * Sets Original Authorized Amount.
     * Amount of the original authorization.
     *
     * This field is supported only for Apple Pay, Google Pay, and Samsung Pay transactions with Discover
     * on FDC Nashville Global and Chase Paymentech.
     *
     * @maps originalAuthorizedAmount
     */
    public function setOriginalAuthorizedAmount(?string $originalAuthorizedAmount): void
    {
        $this->originalAuthorizedAmount = $originalAuthorizedAmount;
    }

    /**
     * Returns Agreement Id.
     * This field contains the predetermined agrement id with the merchant
     */
    public function getAgreementId(): ?string
    {
        return $this->agreementId;
    }

    /**
     * Sets Agreement Id.
     * This field contains the predetermined agrement id with the merchant
     *
     * @maps agreementId
     */
    public function setAgreementId(?string $agreementId): void
    {
        $this->agreementId = $agreementId;
    }

    /**
     * Converts the MerchantInitiatedTransactionObject object to a human-readable string representation.
     *
     * @return string The string representation of the MerchantInitiatedTransactionObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MerchantInitiatedTransactionObject',
            [
                'reason' => $this->reason,
                'previousTransactionId' => $this->previousTransactionId,
                'originalAuthorizedAmount' => $this->originalAuthorizedAmount,
                'agreementId' => $this->agreementId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['reason', 'previousTransactionId', 'originalAuthorizedAmount', 'agreementId'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reason)) {
            $json['reason']                   = $this->reason;
        }
        if (isset($this->previousTransactionId)) {
            $json['previousTransactionId']    = $this->previousTransactionId;
        }
        if (isset($this->originalAuthorizedAmount)) {
            $json['originalAuthorizedAmount'] = $this->originalAuthorizedAmount;
        }
        if (isset($this->agreementId)) {
            $json['agreementId']              = $this->agreementId;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
