<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class MerchantInformation14 implements \JsonSerializable
{
    /**
     * @var MerchantDescriptor|null
     */
    private $merchantDescriptor;

    /**
     * @var string|null
     */
    private $cancelUrl;

    /**
     * @var string|null
     */
    private $successUrl;

    /**
     * @var string|null
     */
    private $failureUrl;

    /**
     * @var string|null
     */
    private $noteToBuyer;

    /**
     * Returns Merchant Descriptor.
     */
    public function getMerchantDescriptor(): ?MerchantDescriptor
    {
        return $this->merchantDescriptor;
    }

    /**
     * Sets Merchant Descriptor.
     *
     * @maps merchantDescriptor
     */
    public function setMerchantDescriptor(?MerchantDescriptor $merchantDescriptor): void
    {
        $this->merchantDescriptor = $merchantDescriptor;
    }

    /**
     * Returns Cancel Url.
     * customer would be redirected to this url based on the decision of the transaction
     */
    public function getCancelUrl(): ?string
    {
        return $this->cancelUrl;
    }

    /**
     * Sets Cancel Url.
     * customer would be redirected to this url based on the decision of the transaction
     *
     * @maps cancelUrl
     */
    public function setCancelUrl(?string $cancelUrl): void
    {
        $this->cancelUrl = $cancelUrl;
    }

    /**
     * Returns Success Url.
     * customer would be redirected to this url based on the decision of the transaction
     */
    public function getSuccessUrl(): ?string
    {
        return $this->successUrl;
    }

    /**
     * Sets Success Url.
     * customer would be redirected to this url based on the decision of the transaction
     *
     * @maps successUrl
     */
    public function setSuccessUrl(?string $successUrl): void
    {
        $this->successUrl = $successUrl;
    }

    /**
     * Returns Failure Url.
     * customer would be redirected to this url based on the decision of the transaction
     */
    public function getFailureUrl(): ?string
    {
        return $this->failureUrl;
    }

    /**
     * Sets Failure Url.
     * customer would be redirected to this url based on the decision of the transaction
     *
     * @maps failureUrl
     */
    public function setFailureUrl(?string $failureUrl): void
    {
        $this->failureUrl = $failureUrl;
    }

    /**
     * Returns Note to Buyer.
     * Free-form text field.
     */
    public function getNoteToBuyer(): ?string
    {
        return $this->noteToBuyer;
    }

    /**
     * Sets Note to Buyer.
     * Free-form text field.
     *
     * @maps noteToBuyer
     */
    public function setNoteToBuyer(?string $noteToBuyer): void
    {
        $this->noteToBuyer = $noteToBuyer;
    }

    /**
     * Converts the MerchantInformation14 object to a human-readable string representation.
     *
     * @return string The string representation of the MerchantInformation14 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MerchantInformation14',
            [
                'merchantDescriptor' => $this->merchantDescriptor,
                'cancelUrl' => $this->cancelUrl,
                'successUrl' => $this->successUrl,
                'failureUrl' => $this->failureUrl,
                'noteToBuyer' => $this->noteToBuyer,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['merchantDescriptor', 'cancelUrl', 'successUrl', 'failureUrl', 'noteToBuyer'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchantDescriptor)) {
            $json['merchantDescriptor'] = $this->merchantDescriptor;
        }
        if (isset($this->cancelUrl)) {
            $json['cancelUrl']          = $this->cancelUrl;
        }
        if (isset($this->successUrl)) {
            $json['successUrl']         = $this->successUrl;
        }
        if (isset($this->failureUrl)) {
            $json['failureUrl']         = $this->failureUrl;
        }
        if (isset($this->noteToBuyer)) {
            $json['noteToBuyer']        = $this->noteToBuyer;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
