<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class OrderInformation32 implements \JsonSerializable
{
    /**
     * @var ShipTo13|null
     */
    private $shipTo;

    /**
     * Returns Ship To.
     */
    public function getShipTo(): ?ShipTo13
    {
        return $this->shipTo;
    }

    /**
     * Sets Ship To.
     *
     * @maps shipTo
     */
    public function setShipTo(?ShipTo13 $shipTo): void
    {
        $this->shipTo = $shipTo;
    }

    /**
     * Converts the OrderInformation32 object to a human-readable string representation.
     *
     * @return string The string representation of the OrderInformation32 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrderInformation32',
            ['shipTo' => $this->shipTo, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['shipTo'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->shipTo)) {
            $json['shipTo'] = $this->shipTo;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
