<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class PaymentInformation18 implements \JsonSerializable
{
    /**
     * @var EWallet6|null
     */
    private $eWallet;

    /**
     * @var Bank9|null
     */
    private $bank;

    /**
     * Returns E Wallet.
     */
    public function getEWallet(): ?EWallet6
    {
        return $this->eWallet;
    }

    /**
     * Sets E Wallet.
     *
     * @maps eWallet
     */
    public function setEWallet(?EWallet6 $eWallet): void
    {
        $this->eWallet = $eWallet;
    }

    /**
     * Returns Bank.
     */
    public function getBank(): ?Bank9
    {
        return $this->bank;
    }

    /**
     * Sets Bank.
     *
     * @maps bank
     */
    public function setBank(?Bank9 $bank): void
    {
        $this->bank = $bank;
    }

    /**
     * Converts the PaymentInformation18 object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentInformation18 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentInformation18',
            [
                'eWallet' => $this->eWallet,
                'bank' => $this->bank,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['eWallet', 'bank'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->eWallet)) {
            $json['eWallet'] = $this->eWallet;
        }
        if (isset($this->bank)) {
            $json['bank']    = $this->bank;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
