<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class PaymentInstrumentList implements \JsonSerializable
{
    /**
     * @var Links66|null
     */
    private $links;

    /**
     * @var int|null
     */
    private $offset = 0;

    /**
     * @var int|null
     */
    private $limit = 20;

    /**
     * @var int|null
     */
    private $count;

    /**
     * @var int|null
     */
    private $total;

    /**
     * @var Embedded12|null
     */
    private $embedded;

    /**
     * Returns Links.
     */
    public function getLinks(): ?Links66
    {
        return $this->links;
    }

    /**
     * Sets Links.
     *
     * @maps _links
     */
    public function setLinks(?Links66 $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Offset.
     * The offset parameter supplied in the request.
     */
    public function getOffset(): ?int
    {
        return $this->offset;
    }

    /**
     * Sets Offset.
     * The offset parameter supplied in the request.
     *
     * @maps offset
     */
    public function setOffset(?int $offset): void
    {
        $this->offset = $offset;
    }

    /**
     * Returns Limit.
     * The limit parameter supplied in the request.
     */
    public function getLimit(): ?int
    {
        return $this->limit;
    }

    /**
     * Sets Limit.
     * The limit parameter supplied in the request.
     *
     * @maps limit
     */
    public function setLimit(?int $limit): void
    {
        $this->limit = $limit;
    }

    /**
     * Returns Count.
     * The number of Payment Instruments returned in the array.
     */
    public function getCount(): ?int
    {
        return $this->count;
    }

    /**
     * Sets Count.
     * The number of Payment Instruments returned in the array.
     *
     * @maps count
     */
    public function setCount(?int $count): void
    {
        $this->count = $count;
    }

    /**
     * Returns Total.
     * The total number of Payment Instruments associated with the Customer or Instrument Identifier.
     */
    public function getTotal(): ?int
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * The total number of Payment Instruments associated with the Customer or Instrument Identifier.
     *
     * @maps total
     */
    public function setTotal(?int $total): void
    {
        $this->total = $total;
    }

    /**
     * Returns Embedded.
     */
    public function getEmbedded(): ?Embedded12
    {
        return $this->embedded;
    }

    /**
     * Sets Embedded.
     *
     * @maps _embedded
     */
    public function setEmbedded(?Embedded12 $embedded): void
    {
        $this->embedded = $embedded;
    }

    /**
     * Converts the PaymentInstrumentList object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentInstrumentList object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentInstrumentList',
            [
                'links' => $this->links,
                'offset' => $this->offset,
                'limit' => $this->limit,
                'count' => $this->count,
                'total' => $this->total,
                'embedded' => $this->embedded,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['_links', 'offset', 'limit', 'count', 'total', '_embedded'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->links)) {
            $json['_links']    = $this->links;
        }
        if (isset($this->offset)) {
            $json['offset']    = $this->offset;
        }
        if (isset($this->limit)) {
            $json['limit']     = $this->limit;
        }
        if (isset($this->count)) {
            $json['count']     = $this->count;
        }
        if (isset($this->total)) {
            $json['total']     = $this->total;
        }
        if (isset($this->embedded)) {
            $json['_embedded'] = $this->embedded;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
