<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class PaymentType11 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var Method2|null
     */
    private $method;

    /**
     * Returns Name.
     * A Payment Type is an agreed means for a payee to receive legal tender from a payer. The way one pays
     * for a commercial financial transaction. Examples: Card, Bank Transfer, Digital, Direct Debit.
     * Possible values:
     * - `CARD` (use this for a PIN debit transaction)
     * - `CHECK` (use this for all eCheck payment transactions - ECP Debit, ECP Follow-on Credit, ECP
     * StandAlone Credit)
     * - `bankTransfer` (use for Online Bank Transafer for methods such as P24, iDeal, Estonia Bank, KCP)
     * - `localCard` (KCP Local card via Altpay)
     * - `carrierBilling` (KCP Carrier Billing via Altpay)
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * A Payment Type is an agreed means for a payee to receive legal tender from a payer. The way one pays
     * for a commercial financial transaction. Examples: Card, Bank Transfer, Digital, Direct Debit.
     * Possible values:
     * - `CARD` (use this for a PIN debit transaction)
     * - `CHECK` (use this for all eCheck payment transactions - ECP Debit, ECP Follow-on Credit, ECP
     * StandAlone Credit)
     * - `bankTransfer` (use for Online Bank Transafer for methods such as P24, iDeal, Estonia Bank, KCP)
     * - `localCard` (KCP Local card via Altpay)
     * - `carrierBilling` (KCP Carrier Billing via Altpay)
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Method.
     */
    public function getMethod(): ?Method2
    {
        return $this->method;
    }

    /**
     * Sets Method.
     *
     * @maps method
     */
    public function setMethod(?Method2 $method): void
    {
        $this->method = $method;
    }

    /**
     * Converts the PaymentType11 object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentType11 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentType11',
            [
                'name' => $this->name,
                'method' => $this->method,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['name', 'method'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']   = $this->name;
        }
        if (isset($this->method)) {
            $json['method'] = $this->method;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
