<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class ProcessorInformation24 implements \JsonSerializable
{
    /**
     * @var Processor|null
     */
    private $processor;

    /**
     * @var MultiProcessorRouting[]|null
     */
    private $multiProcessorRouting;

    /**
     * @var string|null
     */
    private $transactionId;

    /**
     * @var string|null
     */
    private $networkTransactionId;

    /**
     * @var string|null
     */
    private $retrievalReferenceNumber;

    /**
     * @var string|null
     */
    private $responseId;

    /**
     * @var string|null
     */
    private $approvalCode;

    /**
     * @var string|null
     */
    private $responseCode;

    /**
     * @var Avs|null
     */
    private $avs;

    /**
     * @var CardVerification1|null
     */
    private $cardVerification;

    /**
     * @var AchVerification|null
     */
    private $achVerification;

    /**
     * @var ElectronicVerificationResults1|null
     */
    private $electronicVerificationResults;

    /**
     * @var string|null
     */
    private $eventStatus;

    /**
     * @var string|null
     */
    private $systemTraceAuditNumber;

    /**
     * @var string|null
     */
    private $responseCodeSource;

    /**
     * @var string|null
     */
    private $paymentAccountReferenceNumber;

    /**
     * @var Routing|null
     */
    private $routing;

    /**
     * Returns Processor.
     */
    public function getProcessor(): ?Processor
    {
        return $this->processor;
    }

    /**
     * Sets Processor.
     *
     * @maps processor
     */
    public function setProcessor(?Processor $processor): void
    {
        $this->processor = $processor;
    }

    /**
     * Returns Multi Processor Routing.
     * An array of object that contains the list of acquirer response codes & reasons if a transaction is
     * routed to multiple acquirers.
     *
     * @return MultiProcessorRouting[]|null
     */
    public function getMultiProcessorRouting(): ?array
    {
        return $this->multiProcessorRouting;
    }

    /**
     * Sets Multi Processor Routing.
     * An array of object that contains the list of acquirer response codes & reasons if a transaction is
     * routed to multiple acquirers.
     *
     * @maps multiProcessorRouting
     *
     * @param MultiProcessorRouting[]|null $multiProcessorRouting
     */
    public function setMultiProcessorRouting(?array $multiProcessorRouting): void
    {
        $this->multiProcessorRouting = $multiProcessorRouting;
    }

    /**
     * Returns Transaction Id.
     * Network transaction identifier (TID). You can use this value to identify a specific transaction when
     * you are
     * discussing the transaction with your processor. Not all processors provide this value.
     *
     * Returned by the authorization service.
     *
     * #### PIN debit
     * Transaction identifier generated by the processor.
     *
     * Returned by PIN debit credit.
     *
     * #### GPX
     * Processor transaction ID.
     *
     * #### Cielo
     * For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The
     * value is generated by Cielo or the issuing bank.
     *
     * #### Comercio Latino
     * For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated
     * by the acquirers Cielo and Rede, or the issuing bank.
     *
     * #### Visa Acceptance through VisaNet and GPN
     * For details about this value for Visa Acceptance through VisaNet and GPN, see "processorInformation.
     * networkTransactionId" in [REST API Fields](
     *
     * #### Moneris
     * This value identifies the transaction on a host system. It contains the following information:
     * - Terminal used to process the transaction
     * - Shift during which the transaction took place
     * - Batch number
     * - Transaction number within the batch
     * You must store this value. If you give the customer a receipt, display this value on the receipt.
     *
     * **Example** For the value
     * 66012345001069003:
     * - Terminal ID = 66012345
     * - Shift number = 001
     * - Batch number = 069
     * - Transaction number = 003
     */
    public function getTransactionId(): ?string
    {
        return $this->transactionId;
    }

    /**
     * Sets Transaction Id.
     * Network transaction identifier (TID). You can use this value to identify a specific transaction when
     * you are
     * discussing the transaction with your processor. Not all processors provide this value.
     *
     * Returned by the authorization service.
     *
     * #### PIN debit
     * Transaction identifier generated by the processor.
     *
     * Returned by PIN debit credit.
     *
     * #### GPX
     * Processor transaction ID.
     *
     * #### Cielo
     * For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The
     * value is generated by Cielo or the issuing bank.
     *
     * #### Comercio Latino
     * For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated
     * by the acquirers Cielo and Rede, or the issuing bank.
     *
     * #### Visa Acceptance through VisaNet and GPN
     * For details about this value for Visa Acceptance through VisaNet and GPN, see "processorInformation.
     * networkTransactionId" in [REST API Fields](
     *
     * #### Moneris
     * This value identifies the transaction on a host system. It contains the following information:
     * - Terminal used to process the transaction
     * - Shift during which the transaction took place
     * - Batch number
     * - Transaction number within the batch
     * You must store this value. If you give the customer a receipt, display this value on the receipt.
     *
     * **Example** For the value
     * 66012345001069003:
     * - Terminal ID = 66012345
     * - Shift number = 001
     * - Batch number = 069
     * - Transaction number = 003
     *
     * @maps transactionId
     */
    public function setTransactionId(?string $transactionId): void
    {
        $this->transactionId = $transactionId;
    }

    /**
     * Returns Network Transaction Id.
     * Same value as `processorInformation.transactionId`
     */
    public function getNetworkTransactionId(): ?string
    {
        return $this->networkTransactionId;
    }

    /**
     * Sets Network Transaction Id.
     * Same value as `processorInformation.transactionId`
     *
     * @maps networkTransactionId
     */
    public function setNetworkTransactionId(?string $networkTransactionId): void
    {
        $this->networkTransactionId = $networkTransactionId;
    }

    /**
     * Returns Retrieval Reference Number.
     * #### Ingenico ePayments
     * Unique number that Visa Acceptance generates to identify the transaction. You can use this value to
     * identify transactions in the Ingenico ePayments Collections Report, which provides settlement
     * information. Contact customer support for information about the report.
     *
     * ### Visa Acceptance through VisaNet
     * Retrieval request number.
     */
    public function getRetrievalReferenceNumber(): ?string
    {
        return $this->retrievalReferenceNumber;
    }

    /**
     * Sets Retrieval Reference Number.
     * #### Ingenico ePayments
     * Unique number that Visa Acceptance generates to identify the transaction. You can use this value to
     * identify transactions in the Ingenico ePayments Collections Report, which provides settlement
     * information. Contact customer support for information about the report.
     *
     * ### Visa Acceptance through VisaNet
     * Retrieval request number.
     *
     * @maps retrievalReferenceNumber
     */
    public function setRetrievalReferenceNumber(?string $retrievalReferenceNumber): void
    {
        $this->retrievalReferenceNumber = $retrievalReferenceNumber;
    }

    /**
     * Returns Response Id.
     * Response ID sent from the processor.
     */
    public function getResponseId(): ?string
    {
        return $this->responseId;
    }

    /**
     * Sets Response Id.
     * Response ID sent from the processor.
     *
     * @maps responseId
     */
    public function setResponseId(?string $responseId): void
    {
        $this->responseId = $responseId;
    }

    /**
     * Returns Approval Code.
     * Authorization code. Returned only when the processor returns this value.
     *
     * The length of this value depends on your processor.
     *
     * Returned by authorization service.
     *
     * #### PIN debit
     * Authorization code that is returned by the processor.
     *
     * Returned by PIN debit credit.
     *
     * #### Elavon Encrypted Account Number Program
     * The returned value is OFFLINE.
     *
     * #### TSYS Acquiring Solutions
     * The returned value for a successful zero amount authorization is 000000.
     */
    public function getApprovalCode(): ?string
    {
        return $this->approvalCode;
    }

    /**
     * Sets Approval Code.
     * Authorization code. Returned only when the processor returns this value.
     *
     * The length of this value depends on your processor.
     *
     * Returned by authorization service.
     *
     * #### PIN debit
     * Authorization code that is returned by the processor.
     *
     * Returned by PIN debit credit.
     *
     * #### Elavon Encrypted Account Number Program
     * The returned value is OFFLINE.
     *
     * #### TSYS Acquiring Solutions
     * The returned value for a successful zero amount authorization is 000000.
     *
     * @maps approvalCode
     */
    public function setApprovalCode(?string $approvalCode): void
    {
        $this->approvalCode = $approvalCode;
    }

    /**
     * Returns Response Code.
     * For most processors, this is the error message sent directly from the bank. Returned only when the
     * processor
     * returns this value.
     *
     * **Important** Do not use this field to evaluate the result of the authorization.
     *
     * #### PIN debit
     * Response value that is returned by the processor or bank.
     * **Important** Do not use this field to evaluate the results of the transaction request.
     *
     * Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.
     *
     * #### AIBMS
     * If this value is `08`, you can accept the transaction if the customer provides you with
     * identification.
     *
     * #### Atos
     * This value is the response code sent from Atos and it might also include the response code from the
     * bank.
     * Format: `aa,bb` with the two values separated by a comma and where:
     * - `aa` is the two-digit error message from Atos.
     * - `bb` is the optional two-digit error message from the bank.
     *
     * #### Comercio Latino
     * This value is the status code and the error or response code received from the processor separated
     * by a colon.
     * Format: [status code]:E[error code] or [status code]:R[response code]
     * Example `2:R06`
     *
     * #### JCN Gateway
     * Processor-defined detail error code. The associated response category code is in the
     * `processorInformation.responseCategoryCode` field.
     * String (3)
     *
     * #### paypalgateway
     * Processor generated ID for the itemized detail.
     */
    public function getResponseCode(): ?string
    {
        return $this->responseCode;
    }

    /**
     * Sets Response Code.
     * For most processors, this is the error message sent directly from the bank. Returned only when the
     * processor
     * returns this value.
     *
     * **Important** Do not use this field to evaluate the result of the authorization.
     *
     * #### PIN debit
     * Response value that is returned by the processor or bank.
     * **Important** Do not use this field to evaluate the results of the transaction request.
     *
     * Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.
     *
     * #### AIBMS
     * If this value is `08`, you can accept the transaction if the customer provides you with
     * identification.
     *
     * #### Atos
     * This value is the response code sent from Atos and it might also include the response code from the
     * bank.
     * Format: `aa,bb` with the two values separated by a comma and where:
     * - `aa` is the two-digit error message from Atos.
     * - `bb` is the optional two-digit error message from the bank.
     *
     * #### Comercio Latino
     * This value is the status code and the error or response code received from the processor separated
     * by a colon.
     * Format: [status code]:E[error code] or [status code]:R[response code]
     * Example `2:R06`
     *
     * #### JCN Gateway
     * Processor-defined detail error code. The associated response category code is in the
     * `processorInformation.responseCategoryCode` field.
     * String (3)
     *
     * #### paypalgateway
     * Processor generated ID for the itemized detail.
     *
     * @maps responseCode
     */
    public function setResponseCode(?string $responseCode): void
    {
        $this->responseCode = $responseCode;
    }

    /**
     * Returns Avs.
     */
    public function getAvs(): ?Avs
    {
        return $this->avs;
    }

    /**
     * Sets Avs.
     *
     * @maps avs
     */
    public function setAvs(?Avs $avs): void
    {
        $this->avs = $avs;
    }

    /**
     * Returns Card Verification.
     */
    public function getCardVerification(): ?CardVerification1
    {
        return $this->cardVerification;
    }

    /**
     * Sets Card Verification.
     *
     * @maps cardVerification
     */
    public function setCardVerification(?CardVerification1 $cardVerification): void
    {
        $this->cardVerification = $cardVerification;
    }

    /**
     * Returns Ach Verification.
     */
    public function getAchVerification(): ?AchVerification
    {
        return $this->achVerification;
    }

    /**
     * Sets Ach Verification.
     *
     * @maps achVerification
     */
    public function setAchVerification(?AchVerification $achVerification): void
    {
        $this->achVerification = $achVerification;
    }

    /**
     * Returns Electronic Verification Results.
     */
    public function getElectronicVerificationResults(): ?ElectronicVerificationResults1
    {
        return $this->electronicVerificationResults;
    }

    /**
     * Sets Electronic Verification Results.
     *
     * @maps electronicVerificationResults
     */
    public function setElectronicVerificationResults(
        ?ElectronicVerificationResults1 $electronicVerificationResults
    ): void {
        $this->electronicVerificationResults = $electronicVerificationResults;
    }

    /**
     * Returns Event Status.
     * The event status.
     */
    public function getEventStatus(): ?string
    {
        return $this->eventStatus;
    }

    /**
     * Sets Event Status.
     * The event status.
     *
     * @maps eventStatus
     */
    public function setEventStatus(?string $eventStatus): void
    {
        $this->eventStatus = $eventStatus;
    }

    /**
     * Returns System Trace Audit Number.
     * This field is returned only for **American Express Direct** and **Visa Acceptance through VisaNet**.
     * Returned by authorization and incremental authorization services.
     *
     * #### American Express Direct
     *
     * System trace audit number (STAN). This value identifies the transaction and is useful when
     * investigating a
     * chargeback dispute.
     *
     * #### Visa Acceptance through VisaNet
     *
     * System trace number that must be printed on the customer’s receipt.
     */
    public function getSystemTraceAuditNumber(): ?string
    {
        return $this->systemTraceAuditNumber;
    }

    /**
     * Sets System Trace Audit Number.
     * This field is returned only for **American Express Direct** and **Visa Acceptance through VisaNet**.
     * Returned by authorization and incremental authorization services.
     *
     * #### American Express Direct
     *
     * System trace audit number (STAN). This value identifies the transaction and is useful when
     * investigating a
     * chargeback dispute.
     *
     * #### Visa Acceptance through VisaNet
     *
     * System trace number that must be printed on the customer’s receipt.
     *
     * @maps systemTraceAuditNumber
     */
    public function setSystemTraceAuditNumber(?string $systemTraceAuditNumber): void
    {
        $this->systemTraceAuditNumber = $systemTraceAuditNumber;
    }

    /**
     * Returns Response Code Source.
     * Used by Visa only and contains the response source/reason code that identifies the source of the
     * response decision.
     */
    public function getResponseCodeSource(): ?string
    {
        return $this->responseCodeSource;
    }

    /**
     * Sets Response Code Source.
     * Used by Visa only and contains the response source/reason code that identifies the source of the
     * response decision.
     *
     * @maps responseCodeSource
     */
    public function setResponseCodeSource(?string $responseCodeSource): void
    {
        $this->responseCodeSource = $responseCodeSource;
    }

    /**
     * Returns Payment Account Reference Number.
     * Payment Account Reference (PAR) is a non-financial reference assigned to each unique payment account
     * and used to link a payment account to associated network tokens, i.e. the same PAR is returned for
     * PAN-based and tokenized transactions, such as from digital wallets. PAR can be returned in
     * authorisation responses for requests initiated with both real PANs and tokenized PANs. PAR can be
     * used by merchants for fraud detection and regulatory compliance across different channels and
     * digital wallets. PAR allows all participants in the payments chain to have a single, non-sensitive
     * value assigned to a consumer. This value can be used in place of sensitive card holder
     * identification fields, and transmitted across the payments ecosystem to facilitate card holder
     * identification.
     *
     * **Note** On Visa Acceptance through VisaNet, the value for this field corresponds to the following
     * data in the TC 33 capture file:
     * - Record: CP01 TCR8
     * - Position: 79-110
     * - Field: Payment Account Reference
     *
     * The TC 33 Capture file contains information about the purchases and refunds that a merchant submits
     * to Visa Acceptance.
     * Visa Acceptance through VisaNet creates the TC 33 Capture file at the end of the day and sends it to
     * the merchant’s acquirer,
     * who uses this information to facilitate end-of-day clearing processing with payment networks.
     */
    public function getPaymentAccountReferenceNumber(): ?string
    {
        return $this->paymentAccountReferenceNumber;
    }

    /**
     * Sets Payment Account Reference Number.
     * Payment Account Reference (PAR) is a non-financial reference assigned to each unique payment account
     * and used to link a payment account to associated network tokens, i.e. the same PAR is returned for
     * PAN-based and tokenized transactions, such as from digital wallets. PAR can be returned in
     * authorisation responses for requests initiated with both real PANs and tokenized PANs. PAR can be
     * used by merchants for fraud detection and regulatory compliance across different channels and
     * digital wallets. PAR allows all participants in the payments chain to have a single, non-sensitive
     * value assigned to a consumer. This value can be used in place of sensitive card holder
     * identification fields, and transmitted across the payments ecosystem to facilitate card holder
     * identification.
     *
     * **Note** On Visa Acceptance through VisaNet, the value for this field corresponds to the following
     * data in the TC 33 capture file:
     * - Record: CP01 TCR8
     * - Position: 79-110
     * - Field: Payment Account Reference
     *
     * The TC 33 Capture file contains information about the purchases and refunds that a merchant submits
     * to Visa Acceptance.
     * Visa Acceptance through VisaNet creates the TC 33 Capture file at the end of the day and sends it to
     * the merchant’s acquirer,
     * who uses this information to facilitate end-of-day clearing processing with payment networks.
     *
     * @maps paymentAccountReferenceNumber
     */
    public function setPaymentAccountReferenceNumber(?string $paymentAccountReferenceNumber): void
    {
        $this->paymentAccountReferenceNumber = $paymentAccountReferenceNumber;
    }

    /**
     * Returns Routing.
     */
    public function getRouting(): ?Routing
    {
        return $this->routing;
    }

    /**
     * Sets Routing.
     *
     * @maps routing
     */
    public function setRouting(?Routing $routing): void
    {
        $this->routing = $routing;
    }

    /**
     * Converts the ProcessorInformation24 object to a human-readable string representation.
     *
     * @return string The string representation of the ProcessorInformation24 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ProcessorInformation24',
            [
                'processor' => $this->processor,
                'multiProcessorRouting' => $this->multiProcessorRouting,
                'transactionId' => $this->transactionId,
                'networkTransactionId' => $this->networkTransactionId,
                'retrievalReferenceNumber' => $this->retrievalReferenceNumber,
                'responseId' => $this->responseId,
                'approvalCode' => $this->approvalCode,
                'responseCode' => $this->responseCode,
                'avs' => $this->avs,
                'cardVerification' => $this->cardVerification,
                'achVerification' => $this->achVerification,
                'electronicVerificationResults' => $this->electronicVerificationResults,
                'eventStatus' => $this->eventStatus,
                'systemTraceAuditNumber' => $this->systemTraceAuditNumber,
                'responseCodeSource' => $this->responseCodeSource,
                'paymentAccountReferenceNumber' => $this->paymentAccountReferenceNumber,
                'routing' => $this->routing,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'processor',
        'multiProcessorRouting',
        'transactionId',
        'networkTransactionId',
        'retrievalReferenceNumber',
        'responseId',
        'approvalCode',
        'responseCode',
        'avs',
        'cardVerification',
        'achVerification',
        'electronicVerificationResults',
        'eventStatus',
        'systemTraceAuditNumber',
        'responseCodeSource',
        'paymentAccountReferenceNumber',
        'routing'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->processor)) {
            $json['processor']                     = $this->processor;
        }
        if (isset($this->multiProcessorRouting)) {
            $json['multiProcessorRouting']         = $this->multiProcessorRouting;
        }
        if (isset($this->transactionId)) {
            $json['transactionId']                 = $this->transactionId;
        }
        if (isset($this->networkTransactionId)) {
            $json['networkTransactionId']          = $this->networkTransactionId;
        }
        if (isset($this->retrievalReferenceNumber)) {
            $json['retrievalReferenceNumber']      = $this->retrievalReferenceNumber;
        }
        if (isset($this->responseId)) {
            $json['responseId']                    = $this->responseId;
        }
        if (isset($this->approvalCode)) {
            $json['approvalCode']                  = $this->approvalCode;
        }
        if (isset($this->responseCode)) {
            $json['responseCode']                  = $this->responseCode;
        }
        if (isset($this->avs)) {
            $json['avs']                           = $this->avs;
        }
        if (isset($this->cardVerification)) {
            $json['cardVerification']              = $this->cardVerification;
        }
        if (isset($this->achVerification)) {
            $json['achVerification']               = $this->achVerification;
        }
        if (isset($this->electronicVerificationResults)) {
            $json['electronicVerificationResults'] = $this->electronicVerificationResults;
        }
        if (isset($this->eventStatus)) {
            $json['eventStatus']                   = $this->eventStatus;
        }
        if (isset($this->systemTraceAuditNumber)) {
            $json['systemTraceAuditNumber']        = $this->systemTraceAuditNumber;
        }
        if (isset($this->responseCodeSource)) {
            $json['responseCodeSource']            = $this->responseCodeSource;
        }
        if (isset($this->paymentAccountReferenceNumber)) {
            $json['paymentAccountReferenceNumber'] = $this->paymentAccountReferenceNumber;
        }
        if (isset($this->routing)) {
            $json['routing']                       = $this->routing;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
