<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class ProcessorInformation15 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $transactionId;

    /**
     * @var string|null
     */
    private $tradeNumber;

    /**
     * @var string|null
     */
    private $rawResponse;

    /**
     * @var string|null
     */
    private $rawResponseLocal;

    /**
     * @var string|null
     */
    private $responseDetails;

    /**
     * @var string|null
     */
    private $responseCode;

    /**
     * @var SellerProtection|null
     */
    private $sellerProtection;

    /**
     * @var Avs1|null
     */
    private $avs;

    /**
     * Returns Transaction Id.
     * Network transaction identifier (TID). You can use this value to identify a specific transaction when
     * you are
     * discussing the transaction with your processor. Not all processors provide this value.
     *
     * Returned by the authorization service.
     *
     * #### PIN debit
     * Transaction identifier generated by the processor.
     *
     * Returned by PIN debit credit.
     *
     * #### GPX
     * Processor transaction ID.
     *
     * #### Cielo
     * For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The
     * value is generated by Cielo or the issuing bank.
     *
     * #### Comercio Latino
     * For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated
     * by the acquirers Cielo and Rede, or the issuing bank.
     *
     * #### Visa Acceptance through VisaNet and GPN
     * For details about this value for Visa Acceptance through VisaNet and GPN, see "processorInformation.
     * networkTransactionId" in [REST API Fields](
     *
     * #### Moneris
     * This value identifies the transaction on a host system. It contains the following information:
     * - Terminal used to process the transaction
     * - Shift during which the transaction took place
     * - Batch number
     * - Transaction number within the batch
     * You must store this value. If you give the customer a receipt, display this value on the receipt.
     *
     * **Example** For the value
     * 66012345001069003:
     * - Terminal ID = 66012345
     * - Shift number = 001
     * - Batch number = 069
     * - Transaction number = 003
     */
    public function getTransactionId(): ?string
    {
        return $this->transactionId;
    }

    /**
     * Sets Transaction Id.
     * Network transaction identifier (TID). You can use this value to identify a specific transaction when
     * you are
     * discussing the transaction with your processor. Not all processors provide this value.
     *
     * Returned by the authorization service.
     *
     * #### PIN debit
     * Transaction identifier generated by the processor.
     *
     * Returned by PIN debit credit.
     *
     * #### GPX
     * Processor transaction ID.
     *
     * #### Cielo
     * For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The
     * value is generated by Cielo or the issuing bank.
     *
     * #### Comercio Latino
     * For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated
     * by the acquirers Cielo and Rede, or the issuing bank.
     *
     * #### Visa Acceptance through VisaNet and GPN
     * For details about this value for Visa Acceptance through VisaNet and GPN, see "processorInformation.
     * networkTransactionId" in [REST API Fields](
     *
     * #### Moneris
     * This value identifies the transaction on a host system. It contains the following information:
     * - Terminal used to process the transaction
     * - Shift during which the transaction took place
     * - Batch number
     * - Transaction number within the batch
     * You must store this value. If you give the customer a receipt, display this value on the receipt.
     *
     * **Example** For the value
     * 66012345001069003:
     * - Terminal ID = 66012345
     * - Shift number = 001
     * - Batch number = 069
     * - Transaction number = 003
     *
     * @maps transactionId
     */
    public function setTransactionId(?string $transactionId): void
    {
        $this->transactionId = $transactionId;
    }

    /**
     * Returns Trade Number.
     * The description for this field is not available.
     */
    public function getTradeNumber(): ?string
    {
        return $this->tradeNumber;
    }

    /**
     * Sets Trade Number.
     * The description for this field is not available.
     *
     * @maps tradeNumber
     */
    public function setTradeNumber(?string $tradeNumber): void
    {
        $this->tradeNumber = $tradeNumber;
    }

    /**
     * Returns Raw Response.
     * This field is set to the value of failure reason returned by the processor.
     */
    public function getRawResponse(): ?string
    {
        return $this->rawResponse;
    }

    /**
     * Sets Raw Response.
     * This field is set to the value of failure reason returned by the processor.
     *
     * @maps rawResponse
     */
    public function setRawResponse(?string $rawResponse): void
    {
        $this->rawResponse = $rawResponse;
    }

    /**
     * Returns Raw Response Local.
     * This field is set to the value of failure reason returned by the processor in the local language of
     * the processor.
     */
    public function getRawResponseLocal(): ?string
    {
        return $this->rawResponseLocal;
    }

    /**
     * Sets Raw Response Local.
     * This field is set to the value of failure reason returned by the processor in the local language of
     * the processor.
     *
     * @maps rawResponseLocal
     */
    public function setRawResponseLocal(?string $rawResponseLocal): void
    {
        $this->rawResponseLocal = $rawResponseLocal;
    }

    /**
     * Returns Response Details.
     * This field might contain information about a decline.
     */
    public function getResponseDetails(): ?string
    {
        return $this->responseDetails;
    }

    /**
     * Sets Response Details.
     * This field might contain information about a decline.
     *
     * @maps responseDetails
     */
    public function setResponseDetails(?string $responseDetails): void
    {
        $this->responseDetails = $responseDetails;
    }

    /**
     * Returns Response Code.
     * This field is set to the value of response code returned by the processor.
     */
    public function getResponseCode(): ?string
    {
        return $this->responseCode;
    }

    /**
     * Sets Response Code.
     * This field is set to the value of response code returned by the processor.
     *
     * @maps responseCode
     */
    public function setResponseCode(?string $responseCode): void
    {
        $this->responseCode = $responseCode;
    }

    /**
     * Returns Seller Protection.
     */
    public function getSellerProtection(): ?SellerProtection
    {
        return $this->sellerProtection;
    }

    /**
     * Sets Seller Protection.
     *
     * @maps sellerProtection
     */
    public function setSellerProtection(?SellerProtection $sellerProtection): void
    {
        $this->sellerProtection = $sellerProtection;
    }

    /**
     * Returns Avs.
     */
    public function getAvs(): ?Avs1
    {
        return $this->avs;
    }

    /**
     * Sets Avs.
     *
     * @maps avs
     */
    public function setAvs(?Avs1 $avs): void
    {
        $this->avs = $avs;
    }

    /**
     * Converts the ProcessorInformation15 object to a human-readable string representation.
     *
     * @return string The string representation of the ProcessorInformation15 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ProcessorInformation15',
            [
                'transactionId' => $this->transactionId,
                'tradeNumber' => $this->tradeNumber,
                'rawResponse' => $this->rawResponse,
                'rawResponseLocal' => $this->rawResponseLocal,
                'responseDetails' => $this->responseDetails,
                'responseCode' => $this->responseCode,
                'sellerProtection' => $this->sellerProtection,
                'avs' => $this->avs,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'transactionId',
        'tradeNumber',
        'rawResponse',
        'rawResponseLocal',
        'responseDetails',
        'responseCode',
        'sellerProtection',
        'avs'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->transactionId)) {
            $json['transactionId']    = $this->transactionId;
        }
        if (isset($this->tradeNumber)) {
            $json['tradeNumber']      = $this->tradeNumber;
        }
        if (isset($this->rawResponse)) {
            $json['rawResponse']      = $this->rawResponse;
        }
        if (isset($this->rawResponseLocal)) {
            $json['rawResponseLocal'] = $this->rawResponseLocal;
        }
        if (isset($this->responseDetails)) {
            $json['responseDetails']  = $this->responseDetails;
        }
        if (isset($this->responseCode)) {
            $json['responseCode']     = $this->responseCode;
        }
        if (isset($this->sellerProtection)) {
            $json['sellerProtection'] = $this->sellerProtection;
        }
        if (isset($this->avs)) {
            $json['avs']              = $this->avs;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
