<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class PtsV2PaymentsPost201Response1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $submitTimeUtc;

    /**
     * @var ProcessorInformation15|null
     */
    private $processorInformation;

    /**
     * @var string|null
     */
    private $reconciliationId;

    /**
     * @var PaymentInformation15|null
     */
    private $paymentInformation;

    /**
     * @var OrderInformation19|null
     */
    private $orderInformation;

    /**
     * @var ClientReferenceInformation3|null
     */
    private $clientReferenceInformation;

    /**
     * @var IssuerInformation5|null
     */
    private $issuerInformation;

    /**
     * @var ErrorInformation17|null
     */
    private $errorInformation;

    /**
     * Returns Id.
     * An unique identification number generated by Visa Acceptance to identify the submitted request.
     * Returned by all services.
     * It is also appended to the endpoint of the resource.
     * On incremental authorizations, this value with be the same as the identification number returned in
     * the original authorization response.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * An unique identification number generated by Visa Acceptance to identify the submitted request.
     * Returned by all services.
     * It is also appended to the endpoint of the resource.
     * On incremental authorizations, this value with be the same as the identification number returned in
     * the original authorization response.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Status.
     * The status of the submitted transaction.
     *
     * Possible values:
     * - AUTHORIZED
     * - PARTIAL_AUTHORIZED
     * - AUTHORIZED_PENDING_REVIEW
     * - AUTHORIZED_RISK_DECLINED
     * - PENDING_AUTHENTICATION
     * - PENDING_REVIEW
     * - DECLINED
     * - INVALID_REQUEST
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the submitted transaction.
     *
     * Possible values:
     * - AUTHORIZED
     * - PARTIAL_AUTHORIZED
     * - AUTHORIZED_PENDING_REVIEW
     * - AUTHORIZED_RISK_DECLINED
     * - PENDING_AUTHENTICATION
     * - PENDING_REVIEW
     * - DECLINED
     * - INVALID_REQUEST
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Submit Time Utc.
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`
     * **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.).
     * The `T` separates the date and the time. The `Z` indicates UTC.
     *
     * Returned by Visa Acceptance for all services.
     */
    public function getSubmitTimeUtc(): ?string
    {
        return $this->submitTimeUtc;
    }

    /**
     * Sets Submit Time Utc.
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`
     * **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.).
     * The `T` separates the date and the time. The `Z` indicates UTC.
     *
     * Returned by Visa Acceptance for all services.
     *
     * @maps submitTimeUtc
     */
    public function setSubmitTimeUtc(?string $submitTimeUtc): void
    {
        $this->submitTimeUtc = $submitTimeUtc;
    }

    /**
     * Returns Processor Information.
     */
    public function getProcessorInformation(): ?ProcessorInformation15
    {
        return $this->processorInformation;
    }

    /**
     * Sets Processor Information.
     *
     * @maps processorInformation
     */
    public function setProcessorInformation(?ProcessorInformation15 $processorInformation): void
    {
        $this->processorInformation = $processorInformation;
    }

    /**
     * Returns Reconciliation Id.
     * Reference number for the transaction.
     * Depending on how your Visa Acceptance account is configured, this value could either be provided in
     * the API request or generated by Visa Acceptance.
     * The actual value used in the request to the processor is provided back to you by Visa Acceptance in
     * the response.
     */
    public function getReconciliationId(): ?string
    {
        return $this->reconciliationId;
    }

    /**
     * Sets Reconciliation Id.
     * Reference number for the transaction.
     * Depending on how your Visa Acceptance account is configured, this value could either be provided in
     * the API request or generated by Visa Acceptance.
     * The actual value used in the request to the processor is provided back to you by Visa Acceptance in
     * the response.
     *
     * @maps reconciliationId
     */
    public function setReconciliationId(?string $reconciliationId): void
    {
        $this->reconciliationId = $reconciliationId;
    }

    /**
     * Returns Payment Information.
     */
    public function getPaymentInformation(): ?PaymentInformation15
    {
        return $this->paymentInformation;
    }

    /**
     * Sets Payment Information.
     *
     * @maps paymentInformation
     */
    public function setPaymentInformation(?PaymentInformation15 $paymentInformation): void
    {
        $this->paymentInformation = $paymentInformation;
    }

    /**
     * Returns Order Information.
     */
    public function getOrderInformation(): ?OrderInformation19
    {
        return $this->orderInformation;
    }

    /**
     * Sets Order Information.
     *
     * @maps orderInformation
     */
    public function setOrderInformation(?OrderInformation19 $orderInformation): void
    {
        $this->orderInformation = $orderInformation;
    }

    /**
     * Returns Client Reference Information.
     */
    public function getClientReferenceInformation(): ?ClientReferenceInformation3
    {
        return $this->clientReferenceInformation;
    }

    /**
     * Sets Client Reference Information.
     *
     * @maps clientReferenceInformation
     */
    public function setClientReferenceInformation(?ClientReferenceInformation3 $clientReferenceInformation): void
    {
        $this->clientReferenceInformation = $clientReferenceInformation;
    }

    /**
     * Returns Issuer Information.
     */
    public function getIssuerInformation(): ?IssuerInformation5
    {
        return $this->issuerInformation;
    }

    /**
     * Sets Issuer Information.
     *
     * @maps issuerInformation
     */
    public function setIssuerInformation(?IssuerInformation5 $issuerInformation): void
    {
        $this->issuerInformation = $issuerInformation;
    }

    /**
     * Returns Error Information.
     */
    public function getErrorInformation(): ?ErrorInformation17
    {
        return $this->errorInformation;
    }

    /**
     * Sets Error Information.
     *
     * @maps errorInformation
     */
    public function setErrorInformation(?ErrorInformation17 $errorInformation): void
    {
        $this->errorInformation = $errorInformation;
    }

    /**
     * Converts the PtsV2PaymentsPost201Response1 object to a human-readable string representation.
     *
     * @return string The string representation of the PtsV2PaymentsPost201Response1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PtsV2PaymentsPost201Response1',
            [
                'id' => $this->id,
                'status' => $this->status,
                'submitTimeUtc' => $this->submitTimeUtc,
                'processorInformation' => $this->processorInformation,
                'reconciliationId' => $this->reconciliationId,
                'paymentInformation' => $this->paymentInformation,
                'orderInformation' => $this->orderInformation,
                'clientReferenceInformation' => $this->clientReferenceInformation,
                'issuerInformation' => $this->issuerInformation,
                'errorInformation' => $this->errorInformation,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'status',
        'submitTimeUtc',
        'processorInformation',
        'reconciliationId',
        'paymentInformation',
        'orderInformation',
        'clientReferenceInformation',
        'issuerInformation',
        'errorInformation'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']                         = $this->id;
        }
        if (isset($this->status)) {
            $json['status']                     = $this->status;
        }
        if (isset($this->submitTimeUtc)) {
            $json['submitTimeUtc']              = $this->submitTimeUtc;
        }
        if (isset($this->processorInformation)) {
            $json['processorInformation']       = $this->processorInformation;
        }
        if (isset($this->reconciliationId)) {
            $json['reconciliationId']           = $this->reconciliationId;
        }
        if (isset($this->paymentInformation)) {
            $json['paymentInformation']         = $this->paymentInformation;
        }
        if (isset($this->orderInformation)) {
            $json['orderInformation']           = $this->orderInformation;
        }
        if (isset($this->clientReferenceInformation)) {
            $json['clientReferenceInformation'] = $this->clientReferenceInformation;
        }
        if (isset($this->issuerInformation)) {
            $json['issuerInformation']          = $this->issuerInformation;
        }
        if (isset($this->errorInformation)) {
            $json['errorInformation']           = $this->errorInformation;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
