<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class RecipientInformation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountId;

    /**
     * @var string|null
     */
    private $accountType;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $middleName;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var string|null
     */
    private $address1;

    /**
     * @var string|null
     */
    private $administrativeArea;

    /**
     * @var string|null
     */
    private $postalCode;

    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $dateOfBirth;

    /**
     * @var string|null
     */
    private $beneficiaryId;

    /**
     * @var string|null
     */
    private $beneficiaryName;

    /**
     * @var string|null
     */
    private $beneficiaryAddress;

    /**
     * @var string|null
     */
    private $aliasName;

    /**
     * @var string|null
     */
    private $nationality;

    /**
     * @var string|null
     */
    private $countryOfBirth;

    /**
     * @var string|null
     */
    private $occupation;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $locality;

    /**
     * Returns Account Id.
     * Identifier for the recipient’s account.
     * This field is applicable for AFT transactions.
     */
    public function getAccountId(): ?string
    {
        return $this->accountId;
    }

    /**
     * Sets Account Id.
     * Identifier for the recipient’s account.
     * This field is applicable for AFT transactions.
     *
     * @maps accountId
     */
    public function setAccountId(?string $accountId): void
    {
        $this->accountId = $accountId;
    }

    /**
     * Returns Account Type.
     * Identifies the recipient’s account type.
     * This field is applicable for AFT transactions.
     *
     * Valid values are:
     * - `00` for Other
     * - `01` for Routing Transit Number (RTN) + Bank Account Number (BAN)
     * - `02` for International Bank Account Number (IBAN)
     * - `03` for Card Account
     * - `06` for Bank Account Number (BAN) + Bank Identification Code (BIC), also known as a SWIFT code
     */
    public function getAccountType(): ?string
    {
        return $this->accountType;
    }

    /**
     * Sets Account Type.
     * Identifies the recipient’s account type.
     * This field is applicable for AFT transactions.
     *
     * Valid values are:
     * - `00` for Other
     * - `01` for Routing Transit Number (RTN) + Bank Account Number (BAN)
     * - `02` for International Bank Account Number (IBAN)
     * - `03` for Card Account
     * - `06` for Bank Account Number (BAN) + Bank Identification Code (BIC), also known as a SWIFT code
     *
     * @maps accountType
     */
    public function setAccountType(?string $accountType): void
    {
        $this->accountType = $accountType;
    }

    /**
     * Returns First Name.
     * First name of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set,
     * are not supported and will be stripped before being sent to sent to the processor.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     * First name of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set,
     * are not supported and will be stripped before being sent to sent to the processor.
     *
     * @maps firstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Middle Name.
     * Middle name of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set,
     * are not supported and will be stripped before being sent to sent to the processor.
     */
    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    /**
     * Sets Middle Name.
     * Middle name of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set,
     * are not supported and will be stripped before being sent to sent to the processor.
     *
     * @maps middleName
     */
    public function setMiddleName(?string $middleName): void
    {
        $this->middleName = $middleName;
    }

    /**
     * Returns Last Name.
     * Last name of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set,
     * are not supported and will be stripped before being sent to sent to the processor.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     * Last name of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set,
     * are not supported and will be stripped before being sent to sent to the processor.
     *
     * @maps lastName
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Address 1.
     * The street address of the recipient
     * This field is applicable for AFT and OCT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set
     * are not supported and will be stripped before being sent to sent to the processor.
     */
    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    /**
     * Sets Address 1.
     * The street address of the recipient
     * This field is applicable for AFT and OCT transactions.
     *
     * Only alpha numeric values are supported. Special characters not in the standard ASCII character set
     * are not supported and will be stripped before being sent to sent to the processor.
     *
     * @maps address1
     */
    public function setAddress1(?string $address1): void
    {
        $this->address1 = $address1;
    }

    /**
     * Returns Administrative Area.
     * The state or province of the recipient.
     * This field is applicable for AFT transactions when the recipient country is US or CA. Else it is
     * optional.
     *
     * Must be a two character value
     */
    public function getAdministrativeArea(): ?string
    {
        return $this->administrativeArea;
    }

    /**
     * Sets Administrative Area.
     * The state or province of the recipient.
     * This field is applicable for AFT transactions when the recipient country is US or CA. Else it is
     * optional.
     *
     * Must be a two character value
     *
     * @maps administrativeArea
     */
    public function setAdministrativeArea(?string $administrativeArea): void
    {
        $this->administrativeArea = $administrativeArea;
    }

    /**
     * Returns Postal Code.
     * Partial postal code for the recipient’s address. For example, if the postal code is **NN5 7SG**, the
     * value for
     * this field should be the first part of the postal code: **NN5**. This field is a _pass-through_,
     * which means that
     * Visa Acceptance does not verify the value or modify it in any way before sending it to the processor.
     * If the field
     * is not required for the transaction, Visa Acceptance does not forward it to the processor.
     */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * Sets Postal Code.
     * Partial postal code for the recipient’s address. For example, if the postal code is **NN5 7SG**, the
     * value for
     * this field should be the first part of the postal code: **NN5**. This field is a _pass-through_,
     * which means that
     * Visa Acceptance does not verify the value or modify it in any way before sending it to the processor.
     * If the field
     * is not required for the transaction, Visa Acceptance does not forward it to the processor.
     *
     * @maps postalCode
     */
    public function setPostalCode(?string $postalCode): void
    {
        $this->postalCode = $postalCode;
    }

    /**
     * Returns Country.
     * The country associated with the address of the recipient.
     * This field is applicable for AFT and OCT transactions.
     *
     * Must be a two character ISO country code.
     * For example, see [ISO Country Code](
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * The country associated with the address of the recipient.
     * This field is applicable for AFT and OCT transactions.
     *
     * Must be a two character ISO country code.
     * For example, see [ISO Country Code](
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Date of Birth.
     * Recipient’s date of birth. **Format**: `YYYYMMDD`.
     *
     * This field is a `pass-through`, which means that Visa Acceptance ensures that the value is eight
     * numeric characters
     * but otherwise does not verify the value or modify it in any way before sending it to the processor.
     * If the field
     * is not required for the transaction, Visa Acceptance does not forward it to the processor.
     */
    public function getDateOfBirth(): ?string
    {
        return $this->dateOfBirth;
    }

    /**
     * Sets Date of Birth.
     * Recipient’s date of birth. **Format**: `YYYYMMDD`.
     *
     * This field is a `pass-through`, which means that Visa Acceptance ensures that the value is eight
     * numeric characters
     * but otherwise does not verify the value or modify it in any way before sending it to the processor.
     * If the field
     * is not required for the transaction, Visa Acceptance does not forward it to the processor.
     *
     * @maps dateOfBirth
     */
    public function setDateOfBirth(?string $dateOfBirth): void
    {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * Returns Beneficiary Id.
     * Only for e-wallets: ID, username, hash or anything uniquely identifying
     * the ultimate beneficiary.
     */
    public function getBeneficiaryId(): ?string
    {
        return $this->beneficiaryId;
    }

    /**
     * Sets Beneficiary Id.
     * Only for e-wallets: ID, username, hash or anything uniquely identifying
     * the ultimate beneficiary.
     *
     * @maps beneficiaryId
     */
    public function setBeneficiaryId(?string $beneficiaryId): void
    {
        $this->beneficiaryId = $beneficiaryId;
    }

    /**
     * Returns Beneficiary Name.
     * Only for e-wallets: The ultimate beneficiary’s full name.
     */
    public function getBeneficiaryName(): ?string
    {
        return $this->beneficiaryName;
    }

    /**
     * Sets Beneficiary Name.
     * Only for e-wallets: The ultimate beneficiary’s full name.
     *
     * @maps beneficiaryName
     */
    public function setBeneficiaryName(?string $beneficiaryName): void
    {
        $this->beneficiaryName = $beneficiaryName;
    }

    /**
     * Returns Beneficiary Address.
     * Only for e-wallets: The ultimate beneficiary’s street address (street,
     * zip code, city), excluding the country. Example: “Main street 1, 12345,
     * Barcelona
     */
    public function getBeneficiaryAddress(): ?string
    {
        return $this->beneficiaryAddress;
    }

    /**
     * Sets Beneficiary Address.
     * Only for e-wallets: The ultimate beneficiary’s street address (street,
     * zip code, city), excluding the country. Example: “Main street 1, 12345,
     * Barcelona
     *
     * @maps beneficiaryAddress
     */
    public function setBeneficiaryAddress(?string $beneficiaryAddress): void
    {
        $this->beneficiaryAddress = $beneficiaryAddress;
    }

    /**
     * Returns Alias Name.
     * Account owner alias name.
     */
    public function getAliasName(): ?string
    {
        return $this->aliasName;
    }

    /**
     * Sets Alias Name.
     * Account owner alias name.
     *
     * @maps aliasName
     */
    public function setAliasName(?string $aliasName): void
    {
        $this->aliasName = $aliasName;
    }

    /**
     * Returns Nationality.
     * Account Owner Nationality
     */
    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    /**
     * Sets Nationality.
     * Account Owner Nationality
     *
     * @maps nationality
     */
    public function setNationality(?string $nationality): void
    {
        $this->nationality = $nationality;
    }

    /**
     * Returns Country of Birth.
     * Account Owner Country of Birth
     */
    public function getCountryOfBirth(): ?string
    {
        return $this->countryOfBirth;
    }

    /**
     * Sets Country of Birth.
     * Account Owner Country of Birth
     *
     * @maps countryOfBirth
     */
    public function setCountryOfBirth(?string $countryOfBirth): void
    {
        $this->countryOfBirth = $countryOfBirth;
    }

    /**
     * Returns Occupation.
     * Account Owner Occupation
     */
    public function getOccupation(): ?string
    {
        return $this->occupation;
    }

    /**
     * Sets Occupation.
     * Account Owner Occupation
     *
     * @maps occupation
     */
    public function setOccupation(?string $occupation): void
    {
        $this->occupation = $occupation;
    }

    /**
     * Returns Email.
     * Account Owner email address
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * Account Owner email address
     *
     * @maps email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Locality.
     * The city of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported.
     * Special characters not in the standard ASCII character set are not supported and will be stripped
     * before being sent to sent to the processor.
     */
    public function getLocality(): ?string
    {
        return $this->locality;
    }

    /**
     * Sets Locality.
     * The city of the recipient.
     * This field is applicable for AFT transactions.
     *
     * Only alpha numeric values are supported.
     * Special characters not in the standard ASCII character set are not supported and will be stripped
     * before being sent to sent to the processor.
     *
     * @maps locality
     */
    public function setLocality(?string $locality): void
    {
        $this->locality = $locality;
    }

    /**
     * Converts the RecipientInformation object to a human-readable string representation.
     *
     * @return string The string representation of the RecipientInformation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RecipientInformation',
            [
                'accountId' => $this->accountId,
                'accountType' => $this->accountType,
                'firstName' => $this->firstName,
                'middleName' => $this->middleName,
                'lastName' => $this->lastName,
                'address1' => $this->address1,
                'administrativeArea' => $this->administrativeArea,
                'postalCode' => $this->postalCode,
                'country' => $this->country,
                'dateOfBirth' => $this->dateOfBirth,
                'beneficiaryId' => $this->beneficiaryId,
                'beneficiaryName' => $this->beneficiaryName,
                'beneficiaryAddress' => $this->beneficiaryAddress,
                'aliasName' => $this->aliasName,
                'nationality' => $this->nationality,
                'countryOfBirth' => $this->countryOfBirth,
                'occupation' => $this->occupation,
                'email' => $this->email,
                'locality' => $this->locality,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'accountId',
        'accountType',
        'firstName',
        'middleName',
        'lastName',
        'address1',
        'administrativeArea',
        'postalCode',
        'country',
        'dateOfBirth',
        'beneficiaryId',
        'beneficiaryName',
        'beneficiaryAddress',
        'aliasName',
        'nationality',
        'countryOfBirth',
        'occupation',
        'email',
        'locality'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountId)) {
            $json['accountId']          = $this->accountId;
        }
        if (isset($this->accountType)) {
            $json['accountType']        = $this->accountType;
        }
        if (isset($this->firstName)) {
            $json['firstName']          = $this->firstName;
        }
        if (isset($this->middleName)) {
            $json['middleName']         = $this->middleName;
        }
        if (isset($this->lastName)) {
            $json['lastName']           = $this->lastName;
        }
        if (isset($this->address1)) {
            $json['address1']           = $this->address1;
        }
        if (isset($this->administrativeArea)) {
            $json['administrativeArea'] = $this->administrativeArea;
        }
        if (isset($this->postalCode)) {
            $json['postalCode']         = $this->postalCode;
        }
        if (isset($this->country)) {
            $json['country']            = $this->country;
        }
        if (isset($this->dateOfBirth)) {
            $json['dateOfBirth']        = $this->dateOfBirth;
        }
        if (isset($this->beneficiaryId)) {
            $json['beneficiaryId']      = $this->beneficiaryId;
        }
        if (isset($this->beneficiaryName)) {
            $json['beneficiaryName']    = $this->beneficiaryName;
        }
        if (isset($this->beneficiaryAddress)) {
            $json['beneficiaryAddress'] = $this->beneficiaryAddress;
        }
        if (isset($this->aliasName)) {
            $json['aliasName']          = $this->aliasName;
        }
        if (isset($this->nationality)) {
            $json['nationality']        = $this->nationality;
        }
        if (isset($this->countryOfBirth)) {
            $json['countryOfBirth']     = $this->countryOfBirth;
        }
        if (isset($this->occupation)) {
            $json['occupation']         = $this->occupation;
        }
        if (isset($this->email)) {
            $json['email']              = $this->email;
        }
        if (isset($this->locality)) {
            $json['locality']           = $this->locality;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
