<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class ReturnAddress implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $city;

    /**
     * @var string|null
     */
    private $state;

    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $locationId;

    /**
     * @var string|null
     */
    private $address1;

    /**
     * @var string|null
     */
    private $postalCode;

    /**
     * @var string|null
     */
    private $location;

    /**
     * Returns City.
     * City where the auto was returned to the rental agency.
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * City where the auto was returned to the rental agency.
     *
     * @maps city
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns State.
     * State in which the auto was returned to the rental agency. Use the [State, Province, and Territory
     * Codes for the United States and Canada](
     *
     * For authorizations, this field is supported for Visa, MasterCard, and American Express.
     *
     * For captures, this field is supported only for MasterCard and American Express.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     * State in which the auto was returned to the rental agency. Use the [State, Province, and Territory
     * Codes for the United States and Canada](
     *
     * For authorizations, this field is supported for Visa, MasterCard, and American Express.
     *
     * For captures, this field is supported only for MasterCard and American Express.
     *
     * @maps state
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Country.
     * Country where the auto was returned to the rental agency. Use the [ISO Standard Country Codes](
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * Country where the auto was returned to the rental agency. Use the [ISO Standard Country Codes](
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Location Id.
     * Code, address, phone number, etc. used to identify the location of the auto rental return.
     * This field is supported only for MasterCard and American Express.
     */
    public function getLocationId(): ?string
    {
        return $this->locationId;
    }

    /**
     * Sets Location Id.
     * Code, address, phone number, etc. used to identify the location of the auto rental return.
     * This field is supported only for MasterCard and American Express.
     *
     * @maps locationId
     */
    public function setLocationId(?string $locationId): void
    {
        $this->locationId = $locationId;
    }

    /**
     * Returns Address 1.
     * When merchant wants to send the rental address's street address.
     */
    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    /**
     * Sets Address 1.
     * When merchant wants to send the rental address's street address.
     *
     * @maps address1
     */
    public function setAddress1(?string $address1): void
    {
        $this->address1 = $address1;
    }

    /**
     * Returns Postal Code.
     * When merchant wants to send the return address's postal code.
     */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * Sets Postal Code.
     * When merchant wants to send the return address's postal code.
     *
     * @maps postalCode
     */
    public function setPostalCode(?string $postalCode): void
    {
        $this->postalCode = $postalCode;
    }

    /**
     * Returns Location.
     * This field contains the location where the taxi passenger was dropped off or where the auto rental
     * vehicle was returned.
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Sets Location.
     * This field contains the location where the taxi passenger was dropped off or where the auto rental
     * vehicle was returned.
     *
     * @maps location
     */
    public function setLocation(?string $location): void
    {
        $this->location = $location;
    }

    /**
     * Converts the ReturnAddress object to a human-readable string representation.
     *
     * @return string The string representation of the ReturnAddress object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ReturnAddress',
            [
                'city' => $this->city,
                'state' => $this->state,
                'country' => $this->country,
                'locationId' => $this->locationId,
                'address1' => $this->address1,
                'postalCode' => $this->postalCode,
                'location' => $this->location,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['city', 'state', 'country', 'locationId', 'address1', 'postalCode', 'location'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->city)) {
            $json['city']       = $this->city;
        }
        if (isset($this->state)) {
            $json['state']      = $this->state;
        }
        if (isset($this->country)) {
            $json['country']    = $this->country;
        }
        if (isset($this->locationId)) {
            $json['locationId'] = $this->locationId;
        }
        if (isset($this->address1)) {
            $json['address1']   = $this->address1;
        }
        if (isset($this->postalCode)) {
            $json['postalCode'] = $this->postalCode;
        }
        if (isset($this->location)) {
            $json['location']   = $this->location;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
