<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class Rule implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $decision;

    /**
     * Returns Name.
     * Description of the rule as it appears in the Profile Editor.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Description of the rule as it appears in the Profile Editor.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Decision.
     * Summarizes the result for the rule according to the setting that you chose in the Profile Editor.
     * This field can contain one of the following values:
     * - `IGNORE`
     * - `REVIEW`
     * - `REJECT`
     * - `ACCEPT`
     */
    public function getDecision(): ?string
    {
        return $this->decision;
    }

    /**
     * Sets Decision.
     * Summarizes the result for the rule according to the setting that you chose in the Profile Editor.
     * This field can contain one of the following values:
     * - `IGNORE`
     * - `REVIEW`
     * - `REJECT`
     * - `ACCEPT`
     *
     * @maps decision
     */
    public function setDecision(?string $decision): void
    {
        $this->decision = $decision;
    }

    /**
     * Converts the Rule object to a human-readable string representation.
     *
     * @return string The string representation of the Rule object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Rule',
            [
                'name' => $this->name,
                'decision' => $this->decision,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['name', 'decision'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']     = $this->name;
        }
        if (isset($this->decision)) {
            $json['decision'] = $this->decision;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
