<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class Score1 implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $factorCodes;

    /**
     * @var int|null
     */
    private $result;

    /**
     * Returns Factor Codes.
     * Array of factor codes.
     *
     * @return string[]|null
     */
    public function getFactorCodes(): ?array
    {
        return $this->factorCodes;
    }

    /**
     * Sets Factor Codes.
     * Array of factor codes.
     *
     * @maps factorCodes
     *
     * @param string[]|null $factorCodes
     */
    public function setFactorCodes(?array $factorCodes): void
    {
        $this->factorCodes = $factorCodes;
    }

    /**
     * Returns Result.
     * The description for this field is not available.
     */
    public function getResult(): ?int
    {
        return $this->result;
    }

    /**
     * Sets Result.
     * The description for this field is not available.
     *
     * @maps result
     */
    public function setResult(?int $result): void
    {
        $this->result = $result;
    }

    /**
     * Converts the Score1 object to a human-readable string representation.
     *
     * @return string The string representation of the Score1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Score1',
            [
                'factorCodes' => $this->factorCodes,
                'result' => $this->result,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['factorCodes', 'result'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->factorCodes)) {
            $json['factorCodes'] = $this->factorCodes;
        }
        if (isset($this->result)) {
            $json['result']      = $this->result;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
