<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

class TokenProvider
{
    public const VTS = 'vts';

    public const MDES = 'mdes';

    public const AMEX = 'amex';

    public const MSCOF = 'mscof';
}
