<?php

declare(strict_types=1);

/*
 * VisaAcceptanceMergedSpecLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VisaAcceptanceMergedSpecLib\Models;

use stdClass;
use VisaAcceptanceMergedSpecLib\ApiHelper;

class Travel implements \JsonSerializable
{
    /**
     * @var ActualFinalDestination|null
     */
    private $actualFinalDestination;

    /**
     * @var FirstDeparture|null
     */
    private $firstDeparture;

    /**
     * @var FirstDestination|null
     */
    private $firstDestination;

    /**
     * @var LastDestination|null
     */
    private $lastDestination;

    /**
     * Returns Actual Final Destination.
     */
    public function getActualFinalDestination(): ?ActualFinalDestination
    {
        return $this->actualFinalDestination;
    }

    /**
     * Sets Actual Final Destination.
     *
     * @maps actualFinalDestination
     */
    public function setActualFinalDestination(?ActualFinalDestination $actualFinalDestination): void
    {
        $this->actualFinalDestination = $actualFinalDestination;
    }

    /**
     * Returns First Departure.
     */
    public function getFirstDeparture(): ?FirstDeparture
    {
        return $this->firstDeparture;
    }

    /**
     * Sets First Departure.
     *
     * @maps firstDeparture
     */
    public function setFirstDeparture(?FirstDeparture $firstDeparture): void
    {
        $this->firstDeparture = $firstDeparture;
    }

    /**
     * Returns First Destination.
     */
    public function getFirstDestination(): ?FirstDestination
    {
        return $this->firstDestination;
    }

    /**
     * Sets First Destination.
     *
     * @maps firstDestination
     */
    public function setFirstDestination(?FirstDestination $firstDestination): void
    {
        $this->firstDestination = $firstDestination;
    }

    /**
     * Returns Last Destination.
     */
    public function getLastDestination(): ?LastDestination
    {
        return $this->lastDestination;
    }

    /**
     * Sets Last Destination.
     *
     * @maps lastDestination
     */
    public function setLastDestination(?LastDestination $lastDestination): void
    {
        $this->lastDestination = $lastDestination;
    }

    /**
     * Converts the Travel object to a human-readable string representation.
     *
     * @return string The string representation of the Travel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Travel',
            [
                'actualFinalDestination' => $this->actualFinalDestination,
                'firstDeparture' => $this->firstDeparture,
                'firstDestination' => $this->firstDestination,
                'lastDestination' => $this->lastDestination,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['actualFinalDestination', 'firstDeparture', 'firstDestination', 'lastDestination'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->actualFinalDestination)) {
            $json['actualFinalDestination'] = $this->actualFinalDestination;
        }
        if (isset($this->firstDeparture)) {
            $json['firstDeparture']         = $this->firstDeparture;
        }
        if (isset($this->firstDestination)) {
            $json['firstDestination']       = $this->firstDestination;
        }
        if (isset($this->lastDestination)) {
            $json['lastDestination']        = $this->lastDestination;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
